//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudlogHelper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language_zh_hans {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_zh_hans() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudlogHelper.Resources.Language.zh-hans", typeof(Language_zh_hans).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接受.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高级设置.
        /// </summary>
        public static string advancedsettings {
            get {
                return ResourceManager.GetString("advancedsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许外部控制.
        /// </summary>
        public static string allowexternalcontrol {
            get {
                return ResourceManager.GetString("allowexternalcontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许请求代理.
        /// </summary>
        public static string allowproxy {
            get {
                return ResourceManager.GetString("allowproxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动上传QSO.
        /// </summary>
        public static string autoqsoupload {
            get {
                return ResourceManager.GetString("autoqsoupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电台数据自动上报.
        /// </summary>
        public static string autoupdateriginfo {
            get {
                return ResourceManager.GetString("autoupdateriginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动上传QSO到.
        /// </summary>
        public static string autoupload2 {
            get {
                return ResourceManager.GetString("autoupload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本信息.
        /// </summary>
        public static string basicinfo {
            get {
                return ResourceManager.GetString("basicinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础设置.
        /// </summary>
        public static string basicsettings {
            get {
                return ResourceManager.GetString("basicsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波特率.
        /// </summary>
        public static string baudrate {
            get {
                return ResourceManager.GetString("baudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动失败！是否尝试重置所有设置？.
        /// </summary>
        public static string bootfail {
            get {
                return ResourceManager.GetString("bootfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算中....
        /// </summary>
        public static string calculating {
            get {
                return ResourceManager.GetString("calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 呼号.
        /// </summary>
        public static string callsign {
            get {
                return ResourceManager.GetString("callsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查电台连接！.
        /// </summary>
        public static string checkrigconn {
            get {
                return ResourceManager.GetString("checkrigconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭窗口.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您希望最小化到托盘还是关闭本程序？.
        /// </summary>
        public static string closeormin {
            get {
                return ResourceManager.GetString("closeormin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 填写您的apikey。这个key需要具备读/写权限。可在主页账号的下拉框中找到。.
        /// </summary>
        public static string cloudlogapihelp {
            get {
                return ResourceManager.GetString("cloudlogapihelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以在主页账号的下拉框中“站点地址”找到。.
        /// </summary>
        public static string cloudlogstationid {
            get {
                return ResourceManager.GetString("cloudlogstationid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只需填写域名，不需要包含index.php/api/qso，程序会自动填充。.
        /// </summary>
        public static string cloudlogurlhelp {
            get {
                return ResourceManager.GetString("cloudlogurlhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clublog设置.
        /// </summary>
        public static string clublogsettings {
            get {
                return ResourceManager.GetString("clublogsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果此字段不为空，软件将使用填写的内容作为启动rigctld的默认参数，其他所有配置将被忽略。.
        /// </summary>
        public static string cmdarghelp {
            get {
                return ResourceManager.GetString("cmdarghelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudlog配置无效，请在设置中修改！.
        /// </summary>
        public static string confcloudlogfirst {
            get {
                return ResourceManager.GetString("confcloudlogfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamlib配置无效，请在设置中修改！.
        /// </summary>
        public static string confhamlibfirst {
            get {
                return ResourceManager.GetString("confhamlibfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到进程 {replace01} 正在运行，可能影响电台数据自动上报功能！.
        /// </summary>
        public static string conflicthamlib {
            get {
                return ResourceManager.GetString("conflicthamlib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前频率.
        /// </summary>
        public static string currentfreq {
            get {
                return ResourceManager.GetString("currentfreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前模式.
        /// </summary>
        public static string currrentmode {
            get {
                return ResourceManager.GetString("currrentmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色模式.
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据位.
        /// </summary>
        public static string databit {
            get {
                return ResourceManager.GetString("databit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今日QSO数.
        /// </summary>
        public static string dayqsos {
            get {
                return ResourceManager.GetString("dayqsos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中项.
        /// </summary>
        public static string delsel {
            get {
                return ResourceManager.GetString("delsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拒绝.
        /// </summary>
        public static string deny {
            get {
                return ResourceManager.GetString("deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备端口.
        /// </summary>
        public static string deviceport {
            get {
                return ResourceManager.GetString("deviceport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用PTT控制.
        /// </summary>
        public static string disableptt {
            get {
                return ResourceManager.GetString("disableptt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部分Linux发行版中如果不禁用rts/dtr可能导致PTT无法正确初始化，表现为PTT始终处于触发状态。.
        /// </summary>
        public static string disableptthelp {
            get {
                return ResourceManager.GetString("disableptthelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string discard {
            get {
                return ResourceManager.GetString("discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎使用Cloudlog Helper v{1}!
        ///
        ///在您开始使用前，请先阅读并同意下方的【免责声明与用户协议】
        ///
        ///【免责声明与用户协议】
        ///本软件采用The Unlicense协议开源，按“原样”提供，仅供技术交流与学习之用。使用者需自行承担所有风险。
        ///开发者对因使用本软件而产生的任何数据丢失、设备损坏或其他损失概不负责。
        ///继续使用即表示您已阅读并同意上述条款及项目主页上的完整免责声明 (https://github.com/sydneyowl/cloudlog-helper)。
        ///.
        /// </summary>
        public static string disclaimer {
            get {
                return ResourceManager.GetString("disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 双击查看更多.
        /// </summary>
        public static string doubletap2seemore {
            get {
                return ResourceManager.GetString("doubletap2seemore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序已在运行！.
        /// </summary>
        public static string dupeinstance {
            get {
                return ResourceManager.GetString("dupeinstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高级设置.
        /// </summary>
        public static string enableadvanced {
            get {
                return ResourceManager.GetString("enableadvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许外部连接.
        /// </summary>
        public static string enableoutsideconn {
            get {
                return ResourceManager.GetString("enableoutsideconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用UDP服务器.
        /// </summary>
        public static string enableudpserver {
            get {
                return ResourceManager.GetString("enableudpserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出错啦！.
        /// </summary>
        public static string errorccurred {
            get {
                return ResourceManager.GetString("errorccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出为adi.
        /// </summary>
        public static string export2adif {
            get {
                return ResourceManager.GetString("export2adif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigctld服务地址.
        /// </summary>
        public static string externalrigctldhost {
            get {
                return ResourceManager.GetString("externalrigctldhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败！.
        /// </summary>
        public static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此QSO上传失败。.
        /// </summary>
        public static string failedqso {
            get {
                return ResourceManager.GetString("failedqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法获取电台数据！.
        /// </summary>
        public static string failedriginfo {
            get {
                return ResourceManager.GetString("failedriginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法获取站点信息！.
        /// </summary>
        public static string failedstationinfo {
            get {
                return ResourceManager.GetString("failedstationinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法获取站点数据！.
        /// </summary>
        public static string failedstationstat {
            get {
                return ResourceManager.GetString("failedstationstat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO同步出错：.
        /// </summary>
        public static string failedsyncqso {
            get {
                return ResourceManager.GetString("failedsyncqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法从命令行参数中提取端口号。请显式使用参数-t指明。.
        /// </summary>
        public static string failextractinfo {
            get {
                return ResourceManager.GetString("failextractinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 与电台通信失败！.
        /// </summary>
        public static string failrigcomm {
            get {
                return ResourceManager.GetString("failrigcomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法上传到{addr}，请查看日志！.
        /// </summary>
        public static string failuploadriginfoto {
            get {
                return ResourceManager.GetString("failuploadriginfoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请完整填写所有信息！.
        /// </summary>
        public static string fillall {
            get {
                return ResourceManager.GetString("fillall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转发UDP数据包到.
        /// </summary>
        public static string forwardmsg {
            get {
                return ResourceManager.GetString("forwardmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转发地址.
        /// </summary>
        public static string forwardto {
            get {
                return ResourceManager.GetString("forwardto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取数据中....
        /// </summary>
        public static string gettinginfo {
            get {
                return ResourceManager.GetString("gettinginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 坐标.
        /// </summary>
        public static string grid {
            get {
                return ResourceManager.GetString("grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HamCQ设置.
        /// </summary>
        public static string hamcqsettings {
            get {
                return ResourceManager.GetString("hamcqsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 希望您能将出错信息反馈到Github，帮助开发者修正此BUG！.
        /// </summary>
        public static string helpfeedback {
            get {
                return ResourceManager.GetString("helpfeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此QSO已被忽略 - 是不是把所有第三方日志的上传功能都关了？.
        /// </summary>
        public static string ignoreqso {
            get {
                return ResourceManager.GetString("ignoreqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此操作将永久忽略选中的QSO，后续QSO助手扫描本地QSO时将忽略这些项。是否继续？.
        /// </summary>
        public static string ignoreqsopermanently {
            get {
                return ResourceManager.GetString("ignoreqsopermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamlib初始化失败!.
        /// </summary>
        public static string inithamlibfailed {
            get {
                return ResourceManager.GetString("inithamlibfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您使用的后端服务似乎是{replace01}而不是Cloudlog，因此软件部分功能可能不受支持。.
        /// </summary>
        public static string instanceuncompitable {
            get {
                return ResourceManager.GetString("instanceuncompitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址无效！.
        /// </summary>
        public static string invalidaddr {
            get {
                return ResourceManager.GetString("invalidaddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此APIKEY无效！.
        /// </summary>
        public static string invalidapikey {
            get {
                return ResourceManager.GetString("invalidapikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置无效！.
        /// </summary>
        public static string invalidconf {
            get {
                return ResourceManager.GetString("invalidconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口号无效.
        /// </summary>
        public static string invalidport {
            get {
                return ResourceManager.GetString("invalidport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP服务器配置无效！.
        /// </summary>
        public static string invalidudpconf {
            get {
                return ResourceManager.GetString("invalidudpconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL无效！.
        /// </summary>
        public static string invalidurl {
            get {
                return ResourceManager.GetString("invalidurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIKEY需要读/写权限但提供的apikey只有读权限！.
        /// </summary>
        public static string lackwriteaccess {
            get {
                return ResourceManager.GetString("lackwriteaccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色模式.
        /// </summary>
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本月QSO数.
        /// </summary>
        public static string monthqsos {
            get {
                return ResourceManager.GetString("monthqsos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下次上报时间.
        /// </summary>
        public static string nextuploadtime {
            get {
                return ResourceManager.GetString("nextuploadtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意.
        /// </summary>
        public static string notice {
            get {
                return ResourceManager.GetString("notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此项不能为空！.
        /// </summary>
        public static string notnull {
            get {
                return ResourceManager.GetString("notnull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只需输入主域名，不允许以/api/qso结尾！.
        /// </summary>
        public static string onlymaindomain {
            get {
                return ResourceManager.GetString("onlymaindomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作员.
        /// </summary>
        public static string op {
            get {
                return ResourceManager.GetString("op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此QSO正在等待上传。.
        /// </summary>
        public static string pendingqso {
            get {
                return ResourceManager.GetString("pendingqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请在设置中打开“电台数组自动上报”.
        /// </summary>
        public static string polldisabled {
            get {
                return ResourceManager.GetString("polldisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轮询间隔（秒）.
        /// </summary>
        public static string pollinterval {
            get {
                return ResourceManager.GetString("pollinterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轮询间隔必须为整数且大于1！.
        /// </summary>
        public static string pollintervalreq {
            get {
                return ResourceManager.GetString("pollintervalreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口号.
        /// </summary>
        public static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许代理其他应用程序发送的请求。用于避免同时向rigctld发送请求时可能造成的冲突。.
        /// </summary>
        public static string proxyhelp {
            get {
                return ResourceManager.GetString("proxyhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先勾选QSO!.
        /// </summary>
        public static string pseselfirst {
            get {
                return ResourceManager.GetString("pseselfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO上传助手.
        /// </summary>
        public static string qsoassistant {
            get {
                return ResourceManager.GetString("qsoassistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO速率：.
        /// </summary>
        public static string qsorate {
            get {
                return ResourceManager.GetString("qsorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO上传失败重试次数.
        /// </summary>
        public static string qsoretrycount {
            get {
                return ResourceManager.GetString("qsoretrycount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在同步QSO....
        /// </summary>
        public static string qsosyncing {
            get {
                return ResourceManager.GetString("qsosyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO同步成功！.
        /// </summary>
        public static string qsosyncsucc {
            get {
                return ResourceManager.GetString("qsosyncsucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 呼号: {0}
        ///• 国家: {1} (CQ区: {2}, ITU区: {3})
        ///• 大洲: {4}
        ///• 位置: 纬度 {5}°, 经度 {6}° (GMT{7})
        ///• DXCC: {8}
        ///• 网格: {9}
        ///• 频率: {10} ({11})
        ///• 模式: {12} (父模式: {13})
        ///• 时间: {14} 至 {15}
        ///• 信号报告: 发送 &apos;{16}&apos; / 接收 &apos;{17}&apos;
        ///• 功率: {18}
        ///• 操作员: {19}
        ///• 本机呼号: {20}
        ///• 本机网格: {21}
        ///• 交换信息: 发送 &apos;{22}&apos; / 接收 &apos;{23}&apos;
        ///• 传播模式: {24}
        ///• 姓名: {25}
        ///• 备注: {26}
        ///• 客户端: {27}
        ///• 上传状态: {28}
        ///• 失败原因: {29}.
        /// </summary>
        public static string qsotemplate {
            get {
                return ResourceManager.GetString("qsotemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO自动上传功能未启用。.
        /// </summary>
        public static string qsouploaddisabled {
            get {
                return ResourceManager.GetString("qsouploaddisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTH别名（可选）.
        /// </summary>
        public static string qthnick {
            get {
                return ResourceManager.GetString("qthnick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轮询间隔应当大于一秒！.
        /// </summary>
        public static string reachminiumpollinterval {
            get {
                return ResourceManager.GetString("reachminiumpollinterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已完成的QSO信息.
        /// </summary>
        public static string recvqso {
            get {
                return ResourceManager.GetString("recvqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住我的选择.
        /// </summary>
        public static string remembermychoice {
            get {
                return ResourceManager.GetString("remembermychoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报告发射功率.
        /// </summary>
        public static string reportpwr {
            get {
                return ResourceManager.GetString("reportpwr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报告异频信息.
        /// </summary>
        public static string reportsplit {
            get {
                return ResourceManager.GetString("reportsplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重试次数应为大于0的整数！.
        /// </summary>
        public static string retrycountreq {
            get {
                return ResourceManager.GetString("retrycountreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在重试上传.
        /// </summary>
        public static string retryingqso {
            get {
                return ResourceManager.GetString("retryingqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重传选中项.
        /// </summary>
        public static string reuploadsel {
            get {
                return ResourceManager.GetString("reuploadsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部分电台不支持读取发射功率或读取的数据错误，因此本功能默认未开启。.
        /// </summary>
        public static string rfpowerhelp {
            get {
                return ResourceManager.GetString("rfpowerhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigctld命令行参数.
        /// </summary>
        public static string rigctldcmdarg {
            get {
                return ResourceManager.GetString("rigctldcmdarg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigctld服务未启动，请检查设置！.
        /// </summary>
        public static string rigctldnotstart {
            get {
                return ResourceManager.GetString("rigctldnotstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电台数据.
        /// </summary>
        public static string rigdata {
            get {
                return ResourceManager.GetString("rigdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电台型号.
        /// </summary>
        public static string rigmodel {
            get {
                return ResourceManager.GetString("rigmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 与电台通信超时，请检查链接！.
        /// </summary>
        public static string rigtimeout {
            get {
                return ResourceManager.GetString("rigtimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用更改.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存日志.
        /// </summary>
        public static string savelog {
            get {
                return ResourceManager.GetString("savelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存日志到...
        /// </summary>
        public static string savelogto {
            get {
                return ResourceManager.GetString("savelogto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全选.
        /// </summary>
        public static string selall {
            get {
                return ResourceManager.GetString("selall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅显示上传失败项.
        /// </summary>
        public static string showfailonly {
            get {
                return ResourceManager.GetString("showfailonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭程序.
        /// </summary>
        public static string shutdown {
            get {
                return ResourceManager.GetString("shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字符串前后不允许空格.
        /// </summary>
        public static string spacenotallowed {
            get {
                return ResourceManager.GetString("spacenotallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用分号分隔的地址.
        /// </summary>
        public static string spiltby {
            get {
                return ResourceManager.GetString("spiltby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部分电台不支持读取异频信息或读取的数据错误，因此本功能默认未开启。.
        /// </summary>
        public static string splithelp {
            get {
                return ResourceManager.GetString("splithelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL 必须以 http:// 或 https:// 开头！.
        /// </summary>
        public static string startwithhttp {
            get {
                return ResourceManager.GetString("startwithhttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudlog 站点ID.
        /// </summary>
        public static string stationid {
            get {
                return ResourceManager.GetString("stationid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止位.
        /// </summary>
        public static string stopbit {
            get {
                return ResourceManager.GetString("stopbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功！.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此QSO上传成功。.
        /// </summary>
        public static string successqso {
            get {
                return ResourceManager.GetString("successqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同时报告电台信息到.
        /// </summary>
        public static string syncrigto {
            get {
                return ResourceManager.GetString("syncrigto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传失败.
        /// </summary>
        public static string t_Fail {
            get {
                return ResourceManager.GetString("t_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略上传.
        /// </summary>
        public static string t_Ignored {
            get {
                return ResourceManager.GetString("t_Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待中....
        /// </summary>
        public static string t_Pending {
            get {
                return ResourceManager.GetString("t_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重试中....
        /// </summary>
        public static string t_Retrying {
            get {
                return ResourceManager.GetString("t_Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传成功.
        /// </summary>
        public static string t_Success {
            get {
                return ResourceManager.GetString("t_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传中...
        /// </summary>
        public static string t_Uploading {
            get {
                return ResourceManager.GetString("t_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试.
        /// </summary>
        public static string testconn {
            get {
                return ResourceManager.GetString("testconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试中....
        /// </summary>
        public static string testing {
            get {
                return ResourceManager.GetString("testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题色.
        /// </summary>
        public static string themecolor {
            get {
                return ResourceManager.GetString("themecolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第三方日志系统.
        /// </summary>
        public static string thirdpartylogsys {
            get {
                return ResourceManager.GetString("thirdpartylogsys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string titleerror {
            get {
                return ResourceManager.GetString("titleerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string titleinfo {
            get {
                return ResourceManager.GetString("titleinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        public static string titlesuccess {
            get {
                return ResourceManager.GetString("titlesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意.
        /// </summary>
        public static string titlewarning {
            get {
                return ResourceManager.GetString("titlewarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具.
        /// </summary>
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总解码数 / QSO数：.
        /// </summary>
        public static string totaldivqso {
            get {
                return ResourceManager.GetString("totaldivqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小化到托盘.
        /// </summary>
        public static string totray {
            get {
                return ResourceManager.GetString("totray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发射中....
        /// </summary>
        public static string txing {
            get {
                return ResourceManager.GetString("txing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口号应与JTDX/wsjt-x中设置的一致.默认为2237.
        /// </summary>
        public static string udpporthelp {
            get {
                return ResourceManager.GetString("udpporthelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP服务器.
        /// </summary>
        public static string udpserver {
            get {
                return ResourceManager.GetString("udpserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP连接超时！.
        /// </summary>
        public static string udptimeout {
            get {
                return ResourceManager.GetString("udptimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法检查apikey的可用性；请检查输入的地址是否正确！.
        /// </summary>
        public static string unable2checkapi {
            get {
                return ResourceManager.GetString("unable2checkapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知.
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持的电台频率：.
        /// </summary>
        public static string unsupportedrigfreq {
            get {
                return ResourceManager.GetString("unsupportedrigfreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持的电台模式:.
        /// </summary>
        public static string unsupportedrigmode {
            get {
                return ResourceManager.GetString("unsupportedrigmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动上传QSO到Cloudlog.
        /// </summary>
        public static string upload2cloudlog {
            get {
                return ResourceManager.GetString("upload2cloudlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动上传QSO到Clublog.
        /// </summary>
        public static string upload2clublog {
            get {
                return ResourceManager.GetString("upload2clublog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动上传QSO到HamCQ.
        /// </summary>
        public static string upload2hamcq {
            get {
                return ResourceManager.GetString("upload2hamcq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传中....
        /// </summary>
        public static string uploading {
            get {
                return ResourceManager.GetString("uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在上传此QSO。.
        /// </summary>
        public static string uploadingqso {
            get {
                return ResourceManager.GetString("uploadingqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上报状态.
        /// </summary>
        public static string uploadstatus {
            get {
                return ResourceManager.GetString("uploadstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 示例: http://cloudlog.com.
        /// </summary>
        public static string urlexample {
            get {
                return ResourceManager.GetString("urlexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL格式有误！.
        /// </summary>
        public static string urlformaterror {
            get {
                return ResourceManager.GetString("urlformaterror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用外部rigctld服务.
        /// </summary>
        public static string useexternalrigctld {
            get {
                return ResourceManager.GetString("useexternalrigctld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待连接...
        /// </summary>
        public static string waitconn {
            get {
                return ResourceManager.GetString("waitconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5分钟内取得的每分钟QSO平均值。.
        /// </summary>
        public static string within5min {
            get {
                return ResourceManager.GetString("within5min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年度QSO数.
        /// </summary>
        public static string yearqsos {
            get {
                return ResourceManager.GetString("yearqsos", resourceCulture);
            }
        }
    }
}
