name: Cloudlog Helper Cross Build

permissions:
  contents: write
  actions: write

on:
  push:
  pull_request:

jobs:
  exec-tests:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Execute test
        run: |
          dotnet test

  build-windows-release:
    needs: exec-tests
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build Windows application
        shell: pwsh
        run: |
          $tagName = "${{ github.ref_name }}"
          if ([string]::IsNullOrEmpty($tagName)) {
            $tagName = "dev"
          }else{
            $tagName = $tagName -replace '^[vV]', ''
          }
          ./ci.ps1 -Version "$tagName" -Platforms win-x64,win-x86,win-arm64
          
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs-windows
          path: src/CloudlogHelper/bin/*.zip

  build-nonwindows-release:
    needs: exec-tests
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Linux and macOS application
        shell: bash
        run: |
          tagName="${{ github.ref_name }}"
          if [ -z "$tagName" ]; then
            tagName="dev"
          else
            tagName="${tagName#[vV]}"
          fi

          chmod +x ./build.sh
          ./build.sh \
            --tag "$tagName" \
            --platforms linux-x64,linux-arm,linux-arm64,linux-musl-x64,osx-x64,osx-arm64 \
            --install-ubuntu-chain

      - name: Upload Linux and macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs-nonwindows
          path: src/CloudlogHelper/bin/*.zip
          
  release:
    needs:
      - build-windows-release
      - build-nonwindows-release
    runs-on: ubuntu-22.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-outputs-*
          merge-multiple: true
          path: ./downloaded-builds

      - name: Release it
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            downloaded-builds/*.zip
