//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudlogHelper.Resources.Language {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_ja_jp {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_ja_jp() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CloudlogHelper.Resources.Language.Language_ja_jp", typeof(Language_ja_jp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        internal static string advancedsettings {
            get {
                return ResourceManager.GetString("advancedsettings", resourceCulture);
            }
        }
        
        internal static string allowexternalcontrol {
            get {
                return ResourceManager.GetString("allowexternalcontrol", resourceCulture);
            }
        }
        
        internal static string allowproxy {
            get {
                return ResourceManager.GetString("allowproxy", resourceCulture);
            }
        }
        
        internal static string angweight {
            get {
                return ResourceManager.GetString("angweight", resourceCulture);
            }
        }
        
        internal static string apikey {
            get {
                return ResourceManager.GetString("apikey", resourceCulture);
            }
        }
        
        internal static string autopollstatus {
            get {
                return ResourceManager.GetString("autopollstatus", resourceCulture);
            }
        }
        
        internal static string autoqsoupload {
            get {
                return ResourceManager.GetString("autoqsoupload", resourceCulture);
            }
        }
        
        internal static string autosel {
            get {
                return ResourceManager.GetString("autosel", resourceCulture);
            }
        }
        
        internal static string autoupdateriginfo {
            get {
                return ResourceManager.GetString("autoupdateriginfo", resourceCulture);
            }
        }
        
        internal static string autoupload2 {
            get {
                return ResourceManager.GetString("autoupload2", resourceCulture);
            }
        }
        
        internal static string basicinfo {
            get {
                return ResourceManager.GetString("basicinfo", resourceCulture);
            }
        }
        
        internal static string basicsettings {
            get {
                return ResourceManager.GetString("basicsettings", resourceCulture);
            }
        }
        
        internal static string baudrate {
            get {
                return ResourceManager.GetString("baudrate", resourceCulture);
            }
        }
        
        internal static string bearingdeg {
            get {
                return ResourceManager.GetString("bearingdeg", resourceCulture);
            }
        }
        
        internal static string bootfail {
            get {
                return ResourceManager.GetString("bootfail", resourceCulture);
            }
        }
        
        internal static string calculating {
            get {
                return ResourceManager.GetString("calculating", resourceCulture);
            }
        }
        
        internal static string callsign {
            get {
                return ResourceManager.GetString("callsign", resourceCulture);
            }
        }
        
        internal static string charts {
            get {
                return ResourceManager.GetString("charts", resourceCulture);
            }
        }
        
        internal static string chartsdisabled {
            get {
                return ResourceManager.GetString("chartsdisabled", resourceCulture);
            }
        }
        
        internal static string checkrigconn {
            get {
                return ResourceManager.GetString("checkrigconn", resourceCulture);
            }
        }
        
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        internal static string clhhintinfo {
            get {
                return ResourceManager.GetString("clhhintinfo", resourceCulture);
            }
        }
        
        internal static string clhseraddr {
            get {
                return ResourceManager.GetString("clhseraddr", resourceCulture);
            }
        }
        
        internal static string clhserkey {
            get {
                return ResourceManager.GetString("clhserkey", resourceCulture);
            }
        }
        
        internal static string clhserport {
            get {
                return ResourceManager.GetString("clhserport", resourceCulture);
            }
        }
        
        internal static string clhserver {
            get {
                return ResourceManager.GetString("clhserver", resourceCulture);
            }
        }
        
        internal static string clhusetls {
            get {
                return ResourceManager.GetString("clhusetls", resourceCulture);
            }
        }
        
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        internal static string closeormin {
            get {
                return ResourceManager.GetString("closeormin", resourceCulture);
            }
        }
        
        internal static string cloudlogapihelp {
            get {
                return ResourceManager.GetString("cloudlogapihelp", resourceCulture);
            }
        }
        
        internal static string cloudlogstationid {
            get {
                return ResourceManager.GetString("cloudlogstationid", resourceCulture);
            }
        }
        
        internal static string cloudlogurlhelp {
            get {
                return ResourceManager.GetString("cloudlogurlhelp", resourceCulture);
            }
        }
        
        internal static string clublogsettings {
            get {
                return ResourceManager.GetString("clublogsettings", resourceCulture);
            }
        }
        
        internal static string cmdarghelp {
            get {
                return ResourceManager.GetString("cmdarghelp", resourceCulture);
            }
        }
        
        internal static string confcloudlogfirst {
            get {
                return ResourceManager.GetString("confcloudlogfirst", resourceCulture);
            }
        }
        
        internal static string confflrigfirst {
            get {
                return ResourceManager.GetString("confflrigfirst", resourceCulture);
            }
        }
        
        internal static string confhamlibfirst {
            get {
                return ResourceManager.GetString("confhamlibfirst", resourceCulture);
            }
        }
        
        internal static string conflicthamlib {
            get {
                return ResourceManager.GetString("conflicthamlib", resourceCulture);
            }
        }
        
        internal static string confomnifirst {
            get {
                return ResourceManager.GetString("confomnifirst", resourceCulture);
            }
        }
        
        internal static string controlpanel {
            get {
                return ResourceManager.GetString("controlpanel", resourceCulture);
            }
        }
        
        internal static string currentfreq {
            get {
                return ResourceManager.GetString("currentfreq", resourceCulture);
            }
        }
        
        internal static string currrentmode {
            get {
                return ResourceManager.GetString("currrentmode", resourceCulture);
            }
        }
        
        internal static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        internal static string databit {
            get {
                return ResourceManager.GetString("databit", resourceCulture);
            }
        }
        
        internal static string dayqsos {
            get {
                return ResourceManager.GetString("dayqsos", resourceCulture);
            }
        }
        
        internal static string delsel {
            get {
                return ResourceManager.GetString("delsel", resourceCulture);
            }
        }
        
        internal static string deny {
            get {
                return ResourceManager.GetString("deny", resourceCulture);
            }
        }
        
        internal static string deviceport {
            get {
                return ResourceManager.GetString("deviceport", resourceCulture);
            }
        }
        
        internal static string disablecharts {
            get {
                return ResourceManager.GetString("disablecharts", resourceCulture);
            }
        }
        
        internal static string disableptt {
            get {
                return ResourceManager.GetString("disableptt", resourceCulture);
            }
        }
        
        internal static string disableptthelp {
            get {
                return ResourceManager.GetString("disableptthelp", resourceCulture);
            }
        }
        
        internal static string discard {
            get {
                return ResourceManager.GetString("discard", resourceCulture);
            }
        }
        
        internal static string disclaimer {
            get {
                return ResourceManager.GetString("disclaimer", resourceCulture);
            }
        }
        
        internal static string distkm {
            get {
                return ResourceManager.GetString("distkm", resourceCulture);
            }
        }
        
        internal static string distweight {
            get {
                return ResourceManager.GetString("distweight", resourceCulture);
            }
        }
        
        internal static string doubletap2seemore {
            get {
                return ResourceManager.GetString("doubletap2seemore", resourceCulture);
            }
        }
        
        internal static string dupeinstance {
            get {
                return ResourceManager.GetString("dupeinstance", resourceCulture);
            }
        }
        
        internal static string duperigservdetected {
            get {
                return ResourceManager.GetString("duperigservdetected", resourceCulture);
            }
        }
        
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        internal static string enableadvanced {
            get {
                return ResourceManager.GetString("enableadvanced", resourceCulture);
            }
        }
        
        internal static string enableclhserver {
            get {
                return ResourceManager.GetString("enableclhserver", resourceCulture);
            }
        }
        
        internal static string enableoutsideconn {
            get {
                return ResourceManager.GetString("enableoutsideconn", resourceCulture);
            }
        }
        
        internal static string enableudpserver {
            get {
                return ResourceManager.GetString("enableudpserver", resourceCulture);
            }
        }
        
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        internal static string errorccurred {
            get {
                return ResourceManager.GetString("errorccurred", resourceCulture);
            }
        }
        
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        internal static string export2adif {
            get {
                return ResourceManager.GetString("export2adif", resourceCulture);
            }
        }
        
        internal static string externalrigctldhost {
            get {
                return ResourceManager.GetString("externalrigctldhost", resourceCulture);
            }
        }
        
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        internal static string failedqso {
            get {
                return ResourceManager.GetString("failedqso", resourceCulture);
            }
        }
        
        internal static string failedriginfo {
            get {
                return ResourceManager.GetString("failedriginfo", resourceCulture);
            }
        }
        
        internal static string failedstationinfo {
            get {
                return ResourceManager.GetString("failedstationinfo", resourceCulture);
            }
        }
        
        internal static string failedstationstat {
            get {
                return ResourceManager.GetString("failedstationstat", resourceCulture);
            }
        }
        
        internal static string failedsyncqso {
            get {
                return ResourceManager.GetString("failedsyncqso", resourceCulture);
            }
        }
        
        internal static string failextractinfo {
            get {
                return ResourceManager.GetString("failextractinfo", resourceCulture);
            }
        }
        
        internal static string failrigcomm {
            get {
                return ResourceManager.GetString("failrigcomm", resourceCulture);
            }
        }
        
        internal static string failuploadriginfoto {
            get {
                return ResourceManager.GetString("failuploadriginfoto", resourceCulture);
            }
        }
        
        internal static string fillall {
            get {
                return ResourceManager.GetString("fillall", resourceCulture);
            }
        }
        
        internal static string filterdupebycallsign {
            get {
                return ResourceManager.GetString("filterdupebycallsign", resourceCulture);
            }
        }
        
        internal static string forward2tcp {
            get {
                return ResourceManager.GetString("forward2tcp", resourceCulture);
            }
        }
        
        internal static string forwardmsg {
            get {
                return ResourceManager.GetString("forwardmsg", resourceCulture);
            }
        }
        
        internal static string forwardto {
            get {
                return ResourceManager.GetString("forwardto", resourceCulture);
            }
        }
        
        internal static string gettinginfo {
            get {
                return ResourceManager.GetString("gettinginfo", resourceCulture);
            }
        }
        
        internal static string grid {
            get {
                return ResourceManager.GetString("grid", resourceCulture);
            }
        }
        
        internal static string griderror {
            get {
                return ResourceManager.GetString("griderror", resourceCulture);
            }
        }
        
        internal static string hamcqsettings {
            get {
                return ResourceManager.GetString("hamcqsettings", resourceCulture);
            }
        }
        
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        internal static string helpfeedback {
            get {
                return ResourceManager.GetString("helpfeedback", resourceCulture);
            }
        }
        
        internal static string ignoreqso {
            get {
                return ResourceManager.GetString("ignoreqso", resourceCulture);
            }
        }
        
        internal static string ignoreqsopermanently {
            get {
                return ResourceManager.GetString("ignoreqsopermanently", resourceCulture);
            }
        }
        
        internal static string inithamlibfailed {
            get {
                return ResourceManager.GetString("inithamlibfailed", resourceCulture);
            }
        }
        
        internal static string instancename {
            get {
                return ResourceManager.GetString("instancename", resourceCulture);
            }
        }
        
        internal static string instancenamehint {
            get {
                return ResourceManager.GetString("instancenamehint", resourceCulture);
            }
        }
        
        internal static string instanceuncompitable {
            get {
                return ResourceManager.GetString("instanceuncompitable", resourceCulture);
            }
        }
        
        internal static string invalidaddr {
            get {
                return ResourceManager.GetString("invalidaddr", resourceCulture);
            }
        }
        
        internal static string invalidadif {
            get {
                return ResourceManager.GetString("invalidadif", resourceCulture);
            }
        }
        
        internal static string invalidapikey {
            get {
                return ResourceManager.GetString("invalidapikey", resourceCulture);
            }
        }
        
        internal static string invalidconf {
            get {
                return ResourceManager.GetString("invalidconf", resourceCulture);
            }
        }
        
        internal static string invalidport {
            get {
                return ResourceManager.GetString("invalidport", resourceCulture);
            }
        }
        
        internal static string invalidudpconf {
            get {
                return ResourceManager.GetString("invalidudpconf", resourceCulture);
            }
        }
        
        internal static string invalidurl {
            get {
                return ResourceManager.GetString("invalidurl", resourceCulture);
            }
        }
        
        internal static string kval {
            get {
                return ResourceManager.GetString("kval", resourceCulture);
            }
        }
        
        internal static string lackwriteaccess {
            get {
                return ResourceManager.GetString("lackwriteaccess", resourceCulture);
            }
        }
        
        internal static string latitude {
            get {
                return ResourceManager.GetString("latitude", resourceCulture);
            }
        }
        
        internal static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        internal static string longitude {
            get {
                return ResourceManager.GetString("longitude", resourceCulture);
            }
        }
        
        internal static string madeaqso {
            get {
                return ResourceManager.GetString("madeaqso", resourceCulture);
            }
        }
        
        internal static string maxsamplecount {
            get {
                return ResourceManager.GetString("maxsamplecount", resourceCulture);
            }
        }
        
        internal static string monthqsos {
            get {
                return ResourceManager.GetString("monthqsos", resourceCulture);
            }
        }
        
        internal static string mustverbose {
            get {
                return ResourceManager.GetString("mustverbose", resourceCulture);
            }
        }
        
        internal static string mygrid {
            get {
                return ResourceManager.GetString("mygrid", resourceCulture);
            }
        }
        
        internal static string nextuploadtime {
            get {
                return ResourceManager.GetString("nextuploadtime", resourceCulture);
            }
        }
        
        internal static string nodata {
            get {
                return ResourceManager.GetString("nodata", resourceCulture);
            }
        }
        
        internal static string notice {
            get {
                return ResourceManager.GetString("notice", resourceCulture);
            }
        }
        
        internal static string notnull {
            get {
                return ResourceManager.GetString("notnull", resourceCulture);
            }
        }
        
        internal static string omniinitfailed {
            get {
                return ResourceManager.GetString("omniinitfailed", resourceCulture);
            }
        }
        
        internal static string onlymaindomain {
            get {
                return ResourceManager.GetString("onlymaindomain", resourceCulture);
            }
        }
        
        internal static string op {
            get {
                return ResourceManager.GetString("op", resourceCulture);
            }
        }
        
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        internal static string openconfpath {
            get {
                return ResourceManager.GetString("openconfpath", resourceCulture);
            }
        }
        
        internal static string opentempfolder {
            get {
                return ResourceManager.GetString("opentempfolder", resourceCulture);
            }
        }
        
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        internal static string pendingqso {
            get {
                return ResourceManager.GetString("pendingqso", resourceCulture);
            }
        }
        
        internal static string polldisabled {
            get {
                return ResourceManager.GetString("polldisabled", resourceCulture);
            }
        }
        
        internal static string pollinterval {
            get {
                return ResourceManager.GetString("pollinterval", resourceCulture);
            }
        }
        
        internal static string pollintervalreq {
            get {
                return ResourceManager.GetString("pollintervalreq", resourceCulture);
            }
        }
        
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        internal static string proxyhelp {
            get {
                return ResourceManager.GetString("proxyhelp", resourceCulture);
            }
        }
        
        internal static string pseselfirst {
            get {
                return ResourceManager.GetString("pseselfirst", resourceCulture);
            }
        }
        
        internal static string pushnotificationon {
            get {
                return ResourceManager.GetString("pushnotificationon", resourceCulture);
            }
        }
        
        internal static string qsoassistant {
            get {
                return ResourceManager.GetString("qsoassistant", resourceCulture);
            }
        }
        
        internal static string qsoconcisetemplate {
            get {
                return ResourceManager.GetString("qsoconcisetemplate", resourceCulture);
            }
        }
        
        internal static string qsofinished {
            get {
                return ResourceManager.GetString("qsofinished", resourceCulture);
            }
        }
        
        internal static string qsorate {
            get {
                return ResourceManager.GetString("qsorate", resourceCulture);
            }
        }
        
        internal static string qsoretrycount {
            get {
                return ResourceManager.GetString("qsoretrycount", resourceCulture);
            }
        }
        
        internal static string qsosyncing {
            get {
                return ResourceManager.GetString("qsosyncing", resourceCulture);
            }
        }
        
        internal static string qsosyncsucc {
            get {
                return ResourceManager.GetString("qsosyncsucc", resourceCulture);
            }
        }
        
        internal static string qsotemplate {
            get {
                return ResourceManager.GetString("qsotemplate", resourceCulture);
            }
        }
        
        internal static string qsouploaddisabled {
            get {
                return ResourceManager.GetString("qsouploaddisabled", resourceCulture);
            }
        }
        
        internal static string qsouploaded {
            get {
                return ResourceManager.GetString("qsouploaded", resourceCulture);
            }
        }
        
        internal static string qthnick {
            get {
                return ResourceManager.GetString("qthnick", resourceCulture);
            }
        }
        
        internal static string qthnickname {
            get {
                return ResourceManager.GetString("qthnickname", resourceCulture);
            }
        }
        
        internal static string reachminiumpollinterval {
            get {
                return ResourceManager.GetString("reachminiumpollinterval", resourceCulture);
            }
        }
        
        internal static string recvqso {
            get {
                return ResourceManager.GetString("recvqso", resourceCulture);
            }
        }
        
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        internal static string remembermychoice {
            get {
                return ResourceManager.GetString("remembermychoice", resourceCulture);
            }
        }
        
        internal static string reportpwr {
            get {
                return ResourceManager.GetString("reportpwr", resourceCulture);
            }
        }
        
        internal static string reportsplit {
            get {
                return ResourceManager.GetString("reportsplit", resourceCulture);
            }
        }
        
        internal static string retrycountreq {
            get {
                return ResourceManager.GetString("retrycountreq", resourceCulture);
            }
        }
        
        internal static string retryingqso {
            get {
                return ResourceManager.GetString("retryingqso", resourceCulture);
            }
        }
        
        internal static string reuploadsel {
            get {
                return ResourceManager.GetString("reuploadsel", resourceCulture);
            }
        }
        
        internal static string rfpowerhelp {
            get {
                return ResourceManager.GetString("rfpowerhelp", resourceCulture);
            }
        }
        
        internal static string rigbackendsystem {
            get {
                return ResourceManager.GetString("rigbackendsystem", resourceCulture);
            }
        }
        
        internal static string rigctldcmdarg {
            get {
                return ResourceManager.GetString("rigctldcmdarg", resourceCulture);
            }
        }
        
        internal static string rigctldnotstart {
            get {
                return ResourceManager.GetString("rigctldnotstart", resourceCulture);
            }
        }
        
        internal static string rigdata {
            get {
                return ResourceManager.GetString("rigdata", resourceCulture);
            }
        }
        
        internal static string rigmodel {
            get {
                return ResourceManager.GetString("rigmodel", resourceCulture);
            }
        }
        
        internal static string rigtimeout {
            get {
                return ResourceManager.GetString("rigtimeout", resourceCulture);
            }
        }
        
        internal static string samplecount {
            get {
                return ResourceManager.GetString("samplecount", resourceCulture);
            }
        }
        
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        internal static string savelog {
            get {
                return ResourceManager.GetString("savelog", resourceCulture);
            }
        }
        
        internal static string savelogto {
            get {
                return ResourceManager.GetString("savelogto", resourceCulture);
            }
        }
        
        internal static string selall {
            get {
                return ResourceManager.GetString("selall", resourceCulture);
            }
        }
        
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        internal static string showdensitycolor {
            get {
                return ResourceManager.GetString("showdensitycolor", resourceCulture);
            }
        }
        
        internal static string showfailonly {
            get {
                return ResourceManager.GetString("showfailonly", resourceCulture);
            }
        }
        
        internal static string shutdown {
            get {
                return ResourceManager.GetString("shutdown", resourceCulture);
            }
        }
        
        internal static string signalcount {
            get {
                return ResourceManager.GetString("signalcount", resourceCulture);
            }
        }
        
        internal static string signalpolarchart {
            get {
                return ResourceManager.GetString("signalpolarchart", resourceCulture);
            }
        }
        
        internal static string spacenotallowed {
            get {
                return ResourceManager.GetString("spacenotallowed", resourceCulture);
            }
        }
        
        internal static string spiltby {
            get {
                return ResourceManager.GetString("spiltby", resourceCulture);
            }
        }
        
        internal static string splithelp {
            get {
                return ResourceManager.GetString("splithelp", resourceCulture);
            }
        }
        
        internal static string startwithhttp {
            get {
                return ResourceManager.GetString("startwithhttp", resourceCulture);
            }
        }
        
        internal static string stationbearing {
            get {
                return ResourceManager.GetString("stationbearing", resourceCulture);
            }
        }
        
        internal static string stationdistance {
            get {
                return ResourceManager.GetString("stationdistance", resourceCulture);
            }
        }
        
        internal static string stationid {
            get {
                return ResourceManager.GetString("stationid", resourceCulture);
            }
        }
        
        internal static string stationname {
            get {
                return ResourceManager.GetString("stationname", resourceCulture);
            }
        }
        
        internal static string stationstatisticgraph {
            get {
                return ResourceManager.GetString("stationstatisticgraph", resourceCulture);
            }
        }
        
        internal static string stopbit {
            get {
                return ResourceManager.GetString("stopbit", resourceCulture);
            }
        }
        
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        internal static string successqso {
            get {
                return ResourceManager.GetString("successqso", resourceCulture);
            }
        }
        
        internal static string syncrigto {
            get {
                return ResourceManager.GetString("syncrigto", resourceCulture);
            }
        }
        
        internal static string targetrig {
            get {
                return ResourceManager.GetString("targetrig", resourceCulture);
            }
        }
        
        internal static string testandapply {
            get {
                return ResourceManager.GetString("testandapply", resourceCulture);
            }
        }
        
        internal static string testconn {
            get {
                return ResourceManager.GetString("testconn", resourceCulture);
            }
        }
        
        internal static string testing {
            get {
                return ResourceManager.GetString("testing", resourceCulture);
            }
        }
        
        internal static string themecolor {
            get {
                return ResourceManager.GetString("themecolor", resourceCulture);
            }
        }
        
        internal static string thirdpartylogsys {
            get {
                return ResourceManager.GetString("thirdpartylogsys", resourceCulture);
            }
        }
        
        internal static string titleerror {
            get {
                return ResourceManager.GetString("titleerror", resourceCulture);
            }
        }
        
        internal static string titleinfo {
            get {
                return ResourceManager.GetString("titleinfo", resourceCulture);
            }
        }
        
        internal static string titlesuccess {
            get {
                return ResourceManager.GetString("titlesuccess", resourceCulture);
            }
        }
        
        internal static string titlewarning {
            get {
                return ResourceManager.GetString("titlewarning", resourceCulture);
            }
        }
        
        internal static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        internal static string top10decoded {
            get {
                return ResourceManager.GetString("top10decoded", resourceCulture);
            }
        }
        
        internal static string totaldec {
            get {
                return ResourceManager.GetString("totaldec", resourceCulture);
            }
        }
        
        internal static string totaldivqso {
            get {
                return ResourceManager.GetString("totaldivqso", resourceCulture);
            }
        }
        
        internal static string totalrec {
            get {
                return ResourceManager.GetString("totalrec", resourceCulture);
            }
        }
        
        internal static string totaluploaded {
            get {
                return ResourceManager.GetString("totaluploaded", resourceCulture);
            }
        }
        
        internal static string totray {
            get {
                return ResourceManager.GetString("totray", resourceCulture);
            }
        }
        
        internal static string tqslpassword {
            get {
                return ResourceManager.GetString("tqslpassword", resourceCulture);
            }
        }
        
        internal static string tqslpath {
            get {
                return ResourceManager.GetString("tqslpath", resourceCulture);
            }
        }
        
        internal static string transparency {
            get {
                return ResourceManager.GetString("transparency", resourceCulture);
            }
        }
        
        internal static string txing {
            get {
                return ResourceManager.GetString("txing", resourceCulture);
            }
        }
        
        internal static string t_Fail {
            get {
                return ResourceManager.GetString("t_Fail", resourceCulture);
            }
        }
        
        internal static string t_Ignored {
            get {
                return ResourceManager.GetString("t_Ignored", resourceCulture);
            }
        }
        
        internal static string t_Pending {
            get {
                return ResourceManager.GetString("t_Pending", resourceCulture);
            }
        }
        
        internal static string t_Retrying {
            get {
                return ResourceManager.GetString("t_Retrying", resourceCulture);
            }
        }
        
        internal static string t_Success {
            get {
                return ResourceManager.GetString("t_Success", resourceCulture);
            }
        }
        
        internal static string t_Uploading {
            get {
                return ResourceManager.GetString("t_Uploading", resourceCulture);
            }
        }
        
        internal static string udpporthelp {
            get {
                return ResourceManager.GetString("udpporthelp", resourceCulture);
            }
        }
        
        internal static string udpserver {
            get {
                return ResourceManager.GetString("udpserver", resourceCulture);
            }
        }
        
        internal static string udptimeout {
            get {
                return ResourceManager.GetString("udptimeout", resourceCulture);
            }
        }
        
        internal static string unable2checkapi {
            get {
                return ResourceManager.GetString("unable2checkapi", resourceCulture);
            }
        }
        
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        internal static string unsupportedrigfreq {
            get {
                return ResourceManager.GetString("unsupportedrigfreq", resourceCulture);
            }
        }
        
        internal static string unsupportedrigmode {
            get {
                return ResourceManager.GetString("unsupportedrigmode", resourceCulture);
            }
        }
        
        internal static string upload2cloudlog {
            get {
                return ResourceManager.GetString("upload2cloudlog", resourceCulture);
            }
        }
        
        internal static string upload2clublog {
            get {
                return ResourceManager.GetString("upload2clublog", resourceCulture);
            }
        }
        
        internal static string upload2hamcq {
            get {
                return ResourceManager.GetString("upload2hamcq", resourceCulture);
            }
        }
        
        internal static string uploadedaqso {
            get {
                return ResourceManager.GetString("uploadedaqso", resourceCulture);
            }
        }
        
        internal static string uploadfailedaqso {
            get {
                return ResourceManager.GetString("uploadfailedaqso", resourceCulture);
            }
        }
        
        internal static string uploading {
            get {
                return ResourceManager.GetString("uploading", resourceCulture);
            }
        }
        
        internal static string uploadingqso {
            get {
                return ResourceManager.GetString("uploadingqso", resourceCulture);
            }
        }
        
        internal static string uploadriginfo {
            get {
                return ResourceManager.GetString("uploadriginfo", resourceCulture);
            }
        }
        
        internal static string uploadstatus {
            get {
                return ResourceManager.GetString("uploadstatus", resourceCulture);
            }
        }
        
        internal static string urlexample {
            get {
                return ResourceManager.GetString("urlexample", resourceCulture);
            }
        }
        
        internal static string urlformaterror {
            get {
                return ResourceManager.GetString("urlformaterror", resourceCulture);
            }
        }
        
        internal static string useexternalrigctld {
            get {
                return ResourceManager.GetString("useexternalrigctld", resourceCulture);
            }
        }
        
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        internal static string waitconn {
            get {
                return ResourceManager.GetString("waitconn", resourceCulture);
            }
        }
        
        internal static string within5min {
            get {
                return ResourceManager.GetString("within5min", resourceCulture);
            }
        }
        
        internal static string worldheatmap {
            get {
                return ResourceManager.GetString("worldheatmap", resourceCulture);
            }
        }
        
        internal static string yearqsos {
            get {
                return ResourceManager.GetString("yearqsos", resourceCulture);
            }
        }
    }
}
