//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudlogHelper.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_ja_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_ja_jp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudlogHelper.Resources.Language.Language.ja-jp", typeof(Language_ja_jp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to について.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承諾.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細設定.
        /// </summary>
        internal static string advancedsettings {
            get {
                return ResourceManager.GetString("advancedsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部制御を許可.
        /// </summary>
        internal static string allowexternalcontrol {
            get {
                return ResourceManager.GetString("allowexternalcontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リクエストプロキシを許可.
        /// </summary>
        internal static string allowproxy {
            get {
                return ResourceManager.GetString("allowproxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角度の重み.
        /// </summary>
        internal static string angweight {
            get {
                return ResourceManager.GetString("angweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIキー.
        /// </summary>
        internal static string apikey {
            get {
                return ResourceManager.GetString("apikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動的にステーション情報を更新.
        /// </summary>
        internal static string autopollstatus {
            get {
                return ResourceManager.GetString("autopollstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSOを自動アップロード.
        /// </summary>
        internal static string autoqsoupload {
            get {
                return ResourceManager.GetString("autoqsoupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動選択.
        /// </summary>
        internal static string autosel {
            get {
                return ResourceManager.GetString("autosel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無線機データの自動報告.
        /// </summary>
        internal static string autoupdateriginfo {
            get {
                return ResourceManager.GetString("autoupdateriginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSOを自動アップロード先.
        /// </summary>
        internal static string autoupload2 {
            get {
                return ResourceManager.GetString("autoupload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本情報.
        /// </summary>
        internal static string basicinfo {
            get {
                return ResourceManager.GetString("basicinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本設定.
        /// </summary>
        internal static string basicsettings {
            get {
                return ResourceManager.GetString("basicsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ボーレート.
        /// </summary>
        internal static string baudrate {
            get {
                return ResourceManager.GetString("baudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角度（度）.
        /// </summary>
        internal static string bearingdeg {
            get {
                return ResourceManager.GetString("bearingdeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cty.datまたはbigcty.datをインポートするために選択できます。詳細はhttps://www.country-files.com/でご確認ください。
        ///.
        /// </summary>
        internal static string bigctyhint {
            get {
                return ResourceManager.GetString("bigctyhint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起動に失敗しました！すべての設定をリセットしますか？.
        /// </summary>
        internal static string bootfail {
            get {
                return ResourceManager.GetString("bootfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 計算中....
        /// </summary>
        internal static string calculating {
            get {
                return ResourceManager.GetString("calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コールサイン.
        /// </summary>
        internal static string callsign {
            get {
                return ResourceManager.GetString("callsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チャート.
        /// </summary>
        internal static string charts {
            get {
                return ResourceManager.GetString("charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チャート機能は無効です。設定で有効にしてください！.
        /// </summary>
        internal static string chartsdisabled {
            get {
                return ResourceManager.GetString("chartsdisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無線機の接続を確認してください！.
        /// </summary>
        internal static string checkrigconn {
            get {
                return ResourceManager.GetString("checkrigconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリア.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudlog HelperはCLH-Serverに接続でき、デコードされたデータモード情報および無線機情報をサーバーに自動報告します。特定のAndroidアプリを使用してサーバーに接続すると、サーバーからスマートフォンに情報がプッシュされます。.
        /// </summary>
        internal static string clhhintinfo {
            get {
                return ResourceManager.GetString("clhhintinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLHサーバーIP.
        /// </summary>
        internal static string clhseraddr {
            get {
                return ResourceManager.GetString("clhseraddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLHサーバーキー.
        /// </summary>
        internal static string clhserkey {
            get {
                return ResourceManager.GetString("clhserkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLHサーバーポート.
        /// </summary>
        internal static string clhserport {
            get {
                return ResourceManager.GetString("clhserport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLHサーバー.
        /// </summary>
        internal static string clhserver {
            get {
                return ResourceManager.GetString("clhserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLSを使用.
        /// </summary>
        internal static string clhusetls {
            get {
                return ResourceManager.GetString("clhusetls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウを閉じる.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to トレイに最小化しますか、それともプログラムを終了しますか？.
        /// </summary>
        internal static string closeormin {
            get {
                return ResourceManager.GetString("closeormin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIキーを入力してください。このキーには読み取り/書き込み権限が必要です。ホームページのアカウントドロップダウンメニューから確認できます。.
        /// </summary>
        internal static string cloudlogapihelp {
            get {
                return ResourceManager.GetString("cloudlogapihelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホームページのアカウントドロップダウンメニュー内の「ステーションアドレス」から確認できます。.
        /// </summary>
        internal static string cloudlogstationid {
            get {
                return ResourceManager.GetString("cloudlogstationid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドメイン名のみを入力してください。「index.php/api/qso」などのパスは不要です。プログラムが自動的に補完します。.
        /// </summary>
        internal static string cloudlogurlhelp {
            get {
                return ResourceManager.GetString("cloudlogurlhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clublog設定.
        /// </summary>
        internal static string clublogsettings {
            get {
                return ResourceManager.GetString("clublogsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このフィールドが空でない場合、ソフトウェアは入力された内容をrigctld起動時のデフォルト引数として使用し、他のすべての設定は無視されます。.
        /// </summary>
        internal static string cmdarghelp {
            get {
                return ResourceManager.GetString("cmdarghelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudlog設定が無効です。設定で修正してください！.
        /// </summary>
        internal static string confcloudlogfirst {
            get {
                return ResourceManager.GetString("confcloudlogfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLRIG設定に誤りがあります。設定で修正してください！.
        /// </summary>
        internal static string confflrigfirst {
            get {
                return ResourceManager.GetString("confflrigfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamlib設定が無効です。設定で修正してください！.
        /// </summary>
        internal static string confhamlibfirst {
            get {
                return ResourceManager.GetString("confhamlibfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロセス {replace01} が実行中のため、無線機データの自動報告機能に影響を与える可能性があります！.
        /// </summary>
        internal static string conflicthamlib {
            get {
                return ResourceManager.GetString("conflicthamlib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OmniRigの設定を確認してください！.
        /// </summary>
        internal static string confomnifirst {
            get {
                return ResourceManager.GetString("confomnifirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コントロールパネル.
        /// </summary>
        internal static string controlpanel {
            get {
                return ResourceManager.GetString("controlpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在の周波数.
        /// </summary>
        internal static string currentfreq {
            get {
                return ResourceManager.GetString("currentfreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在のモード.
        /// </summary>
        internal static string currrentmode {
            get {
                return ResourceManager.GetString("currrentmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダークモード.
        /// </summary>
        internal static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データビット.
        /// </summary>
        internal static string databit {
            get {
                return ResourceManager.GetString("databit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本日のQSO数.
        /// </summary>
        internal static string dayqsos {
            get {
                return ResourceManager.GetString("dayqsos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        internal static string delsel {
            get {
                return ResourceManager.GetString("delsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拒否.
        /// </summary>
        internal static string deny {
            get {
                return ResourceManager.GetString("deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デバイスポート.
        /// </summary>
        internal static string deviceport {
            get {
                return ResourceManager.GetString("deviceport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チャート機能を無効にする（低性能デバイス向け）.
        /// </summary>
        internal static string disablecharts {
            get {
                return ResourceManager.GetString("disablecharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTT制御を無効にする.
        /// </summary>
        internal static string disableptt {
            get {
                return ResourceManager.GetString("disableptt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一部のLinuxディストリビューションでは、rts/dtrを無効にしないとPTTが正しく初期化されず、常にトリガー状態になることがあります。.
        /// </summary>
        internal static string disableptthelp {
            get {
                return ResourceManager.GetString("disableptthelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string discard {
            get {
                return ResourceManager.GetString("discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudlog Helper v{1}へようこそ！
        ///
        ///使用を開始する前に、下記の【免責事項と利用規約】をお読みいただき、同意してください。n
        ///
        ///【免責事項と利用規約】
        ///本ソフトウェアはThe Unlicenseライセンスに基づきオープンソースとして提供されており、「現状のまま」技術交流および学習目的でのみ使用可能です。使用者は自己の責任において使用するものとし、本ソフトウェアの使用により生じたデータ損失、機器の損傷、その他の一切の損害について、開発者は一切の責任を負いません。
        ///
        ///継続して使用することにより、上記条項およびプロジェクトのGitHubページ（https://github.com/sydneyowl/cloudlog-helper）に記載された完全な免責事項に同意したものとみなされます。.
        /// </summary>
        internal static string disclaimer {
            get {
                return ResourceManager.GetString("disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 距離（km）.
        /// </summary>
        internal static string distkm {
            get {
                return ResourceManager.GetString("distkm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 距離の重み.
        /// </summary>
        internal static string distweight {
            get {
                return ResourceManager.GetString("distweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダブルクリックで詳細を表示.
        /// </summary>
        internal static string doubletap2seemore {
            get {
                return ResourceManager.GetString("doubletap2seemore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プログラムはすでに実行中です！.
        /// </summary>
        internal static string dupeinstance {
            get {
                return ResourceManager.GetString("dupeinstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2つの無線機バックエンド制御サービスを同時に有効にすることはできません！.
        /// </summary>
        internal static string duperigservdetected {
            get {
                return ResourceManager.GetString("duperigservdetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレス.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細設定.
        /// </summary>
        internal static string enableadvanced {
            get {
                return ResourceManager.GetString("enableadvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLHサーバーを有効化.
        /// </summary>
        internal static string enableclhserver {
            get {
                return ResourceManager.GetString("enableclhserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部接続を許可.
        /// </summary>
        internal static string enableoutsideconn {
            get {
                return ResourceManager.GetString("enableoutsideconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDPサーバーを有効化.
        /// </summary>
        internal static string enableudpserver {
            get {
                return ResourceManager.GetString("enableudpserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーが発生しました！.
        /// </summary>
        internal static string errorccurred {
            get {
                return ResourceManager.GetString("errorccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エクスポート.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADI形式でエクスポート.
        /// </summary>
        internal static string export2adif {
            get {
                return ResourceManager.GetString("export2adif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigctldサービスアドレス.
        /// </summary>
        internal static string externalrigctldhost {
            get {
                return ResourceManager.GetString("externalrigctldhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失敗！.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このQSOのアップロードに失敗しました。.
        /// </summary>
        internal static string failedqso {
            get {
                return ResourceManager.GetString("failedqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無線機データを取得できません！.
        /// </summary>
        internal static string failedriginfo {
            get {
                return ResourceManager.GetString("failedriginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステーション情報を取得できません！.
        /// </summary>
        internal static string failedstationinfo {
            get {
                return ResourceManager.GetString("failedstationinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステーションデータを取得できません！.
        /// </summary>
        internal static string failedstationstat {
            get {
                return ResourceManager.GetString("failedstationstat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO同期中にエラーが発生しました：.
        /// </summary>
        internal static string failedsyncqso {
            get {
                return ResourceManager.GetString("failedsyncqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドライン引数からポート番号を抽出できません。明示的に-tパラメータで指定してください。.
        /// </summary>
        internal static string failextractinfo {
            get {
                return ResourceManager.GetString("failextractinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無線機との通信に失敗しました！.
        /// </summary>
        internal static string failrigcomm {
            get {
                return ResourceManager.GetString("failrigcomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {addr}へのアップロードに失敗しました。ログを確認してください！.
        /// </summary>
        internal static string failuploadriginfoto {
            get {
                return ResourceManager.GetString("failuploadriginfoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべての情報を正しく入力してください！.
        /// </summary>
        internal static string fillall {
            get {
                return ResourceManager.GetString("fillall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重複サンプル（コールサイン）をフィルタリング.
        /// </summary>
        internal static string filterdupebycallsign {
            get {
                return ResourceManager.GetString("filterdupebycallsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デコード情報をHTTPサーバーに転送.
        /// </summary>
        internal static string forward2tcp {
            get {
                return ResourceManager.GetString("forward2tcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受信したUDPパケットを転送先.
        /// </summary>
        internal static string forwardmsg {
            get {
                return ResourceManager.GetString("forwardmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受信したUDPパケットを転送先.
        /// </summary>
        internal static string forwardto {
            get {
                return ResourceManager.GetString("forwardto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ取得中....
        /// </summary>
        internal static string gettinginfo {
            get {
                return ResourceManager.GetString("gettinginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 座標.
        /// </summary>
        internal static string grid {
            get {
                return ResourceManager.GetString("grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グリッド座標が空または不正です。設定を確認してください！.
        /// </summary>
        internal static string griderror {
            get {
                return ResourceManager.GetString("griderror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HamCQ設定.
        /// </summary>
        internal static string hamcqsettings {
            get {
                return ResourceManager.GetString("hamcqsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘルプ.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Githubにエラー情報をフィードバックして、開発者がこのバグを修正できるようにご協力ください！.
        /// </summary>
        internal static string helpfeedback {
            get {
                return ResourceManager.GetString("helpfeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このQSOは無視されました — すべてのサードパーティログのアップロード機能がオフになっていませんか？.
        /// </summary>
        internal static string ignoreqso {
            get {
                return ResourceManager.GetString("ignoreqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この操作により、選択されたQSOは今後永久に無視され、QSOアシスタントがローカルQSOをスキャンする際にこれらの項目をスキップします。よろしいですか？.
        /// </summary>
        internal static string ignoreqsopermanently {
            get {
                return ResourceManager.GetString("ignoreqsopermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamlibの初期化に失敗しました！.
        /// </summary>
        internal static string inithamlibfailed {
            get {
                return ResourceManager.GetString("inithamlibfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to インスタンス名.
        /// </summary>
        internal static string instancename {
            get {
                return ResourceManager.GetString("instancename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このフィールドは、ソフトウェアがclh-serverに登録する際に使用する名前です。この名前は一意である必要があります。.
        /// </summary>
        internal static string instancenamehint {
            get {
                return ResourceManager.GetString("instancenamehint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用中のバックエンドサービスは{replace01}のようで、Cloudlogではありません。そのため、一部の機能がサポートされない可能性があります。.
        /// </summary>
        internal static string instanceuncompitable {
            get {
                return ResourceManager.GetString("instanceuncompitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アドレスが無効です！.
        /// </summary>
        internal static string invalidaddr {
            get {
                return ResourceManager.GetString("invalidaddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADIF形式が無効です！.
        /// </summary>
        internal static string invalidadif {
            get {
                return ResourceManager.GetString("invalidadif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このAPIキーは無効です！.
        /// </summary>
        internal static string invalidapikey {
            get {
                return ResourceManager.GetString("invalidapikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定が無効です！.
        /// </summary>
        internal static string invalidconf {
            get {
                return ResourceManager.GetString("invalidconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポート番号が無効です.
        /// </summary>
        internal static string invalidport {
            get {
                return ResourceManager.GetString("invalidport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDPサーバー設定が無効です！.
        /// </summary>
        internal static string invalidudpconf {
            get {
                return ResourceManager.GetString("invalidudpconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLが無効です！.
        /// </summary>
        internal static string invalidurl {
            get {
                return ResourceManager.GetString("invalidurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K値（KNN）.
        /// </summary>
        internal static string kval {
            get {
                return ResourceManager.GetString("kval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIキーには読み取り/書き込み権限が必要ですが、提供されたキーは読み取り専用です！.
        /// </summary>
        internal static string lackwriteaccess {
            get {
                return ResourceManager.GetString("lackwriteaccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 緯度.
        /// </summary>
        internal static string latitude {
            get {
                return ResourceManager.GetString("latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ライトモード.
        /// </summary>
        internal static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 経度.
        /// </summary>
        internal static string longitude {
            get {
                return ResourceManager.GetString("longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅️ QSOが完了しました！.
        /// </summary>
        internal static string madeaqso {
            get {
                return ResourceManager.GetString("madeaqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大サンプルポイント数.
        /// </summary>
        internal static string maxsamplecount {
            get {
                return ResourceManager.GetString("maxsamplecount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今月のQSO数.
        /// </summary>
        internal static string monthqsos {
            get {
                return ResourceManager.GetString("monthqsos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンドライン引数に-vvvvvを追加する必要があります！.
        /// </summary>
        internal static string mustverbose {
            get {
                return ResourceManager.GetString("mustverbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to マイグリッド.
        /// </summary>
        internal static string mygrid {
            get {
                return ResourceManager.GetString("mygrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次回報告予定時刻.
        /// </summary>
        internal static string nextuploadtime {
            get {
                return ResourceManager.GetString("nextuploadtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （データなし）.
        /// </summary>
        internal static string nodata {
            get {
                return ResourceManager.GetString("nodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意.
        /// </summary>
        internal static string notice {
            get {
                return ResourceManager.GetString("notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この項目は必須です！.
        /// </summary>
        internal static string notnull {
            get {
                return ResourceManager.GetString("notnull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OmniRigが正しくインストールされているか確認してください。また、OmniRigは現在、AOTコンパイルされていないWindowsプラットフォームでのみサポートされています。.
        /// </summary>
        internal static string omniinitfailed {
            get {
                return ResourceManager.GetString("omniinitfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メインドメインのみを入力してください。「/api/qso」で終わってはいけません！.
        /// </summary>
        internal static string onlymaindomain {
            get {
                return ResourceManager.GetString("onlymaindomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オペレーター.
        /// </summary>
        internal static string op {
            get {
                return ResourceManager.GetString("op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開く.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定ディレクトリを開く.
        /// </summary>
        internal static string openconfpath {
            get {
                return ResourceManager.GetString("openconfpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャッシュディレクトリを開く.
        /// </summary>
        internal static string opentempfolder {
            get {
                return ResourceManager.GetString("opentempfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一時停止.
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このQSOはアップロード待ちです。.
        /// </summary>
        internal static string pendingqso {
            get {
                return ResourceManager.GetString("pendingqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定で「無線機データの自動報告」を有効にしてください.
        /// </summary>
        internal static string polldisabled {
            get {
                return ResourceManager.GetString("polldisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポーリング間隔（秒）.
        /// </summary>
        internal static string pollinterval {
            get {
                return ResourceManager.GetString("pollinterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポーリング間隔は1より大きい整数でなければなりません！.
        /// </summary>
        internal static string pollintervalreq {
            get {
                return ResourceManager.GetString("pollintervalreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポート番号.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他のアプリケーションからのリクエストをプロキシすることを許可します。これにより、rigctldへの同時リクエストによる競合を回避できます。.
        /// </summary>
        internal static string proxyhelp {
            get {
                return ResourceManager.GetString("proxyhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --選択してください--.
        /// </summary>
        internal static string psesel {
            get {
                return ResourceManager.GetString("psesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to まずQSOをチェックしてください！.
        /// </summary>
        internal static string pseselfirst {
            get {
                return ResourceManager.GetString("pseselfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下の状況でシステム通知をプッシュ：.
        /// </summary>
        internal static string pushnotificationon {
            get {
                return ResourceManager.GetString("pushnotificationon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSOアップロードアシスタント.
        /// </summary>
        internal static string qsoassistant {
            get {
                return ResourceManager.GetString("qsoassistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コールサイン: {0}, 国: {1} ({8}), グリッド: {9}, 周波数: {10} ({11}), モード: {12}, 時間: {14} ～ {15}, 信号レポート: 送信 &apos;{16}&apos; / 受信 &apos;{17}&apos;.
        /// </summary>
        internal static string qsoconcisetemplate {
            get {
                return ResourceManager.GetString("qsoconcisetemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO完了時.
        /// </summary>
        internal static string qsofinished {
            get {
                return ResourceManager.GetString("qsofinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSOレート：.
        /// </summary>
        internal static string qsorate {
            get {
                return ResourceManager.GetString("qsorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSOアップロード失敗時の再試行回数.
        /// </summary>
        internal static string qsoretrycount {
            get {
                return ResourceManager.GetString("qsoretrycount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSOを同期中....
        /// </summary>
        internal static string qsosyncing {
            get {
                return ResourceManager.GetString("qsosyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSOの同期が成功しました！.
        /// </summary>
        internal static string qsosyncsucc {
            get {
                return ResourceManager.GetString("qsosyncsucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • コールサイン: {0}
        ///• 国: {1} (CQゾーン: {2}, ITUゾーン: {3})
        ///• 大陸: {4}
        ///• 位置: 緯度 {5}°, 経度 {6}° (GMT{7})
        ///• DXCC: {8}
        ///• グリッド: {9}
        ///• 周波数: {10} ({11})
        ///• モード: {12} (親モード: {13})
        ///• 時間: {14} ～ {15}
        ///• 信号レポート: 送信 &apos;{16}&apos; / 受信 &apos;{17}&apos;
        ///• 出力: {18}
        ///• オペレーター: {19}
        ///• 自局コールサイン: {20}
        ///• 自局グリッド: {21}
        ///• 交換情報: 送信 &apos;{22}&apos; / 受信 &apos;{23}&apos;
        ///• 伝搬モード: {24}
        ///• 氏名: {25}
        ///• 備考: {26}
        ///• クライアント: {27}
        ///• アップロード状態: {28}
        ///• 失敗理由: {29}.
        /// </summary>
        internal static string qsotemplate {
            get {
                return ResourceManager.GetString("qsotemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO自動アップロード機能が有効になっていません。.
        /// </summary>
        internal static string qsouploaddisabled {
            get {
                return ResourceManager.GetString("qsouploaddisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSOアップロード完了時.
        /// </summary>
        internal static string qsouploaded {
            get {
                return ResourceManager.GetString("qsouploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTHエイリアス（任意）.
        /// </summary>
        internal static string qthnick {
            get {
                return ResourceManager.GetString("qthnick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTHニックネーム（任意）.
        /// </summary>
        internal static string qthnickname {
            get {
                return ResourceManager.GetString("qthnickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポーリング間隔は1秒以上にしてください！.
        /// </summary>
        internal static string reachminiumpollinterval {
            get {
                return ResourceManager.GetString("reachminiumpollinterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了済みQSO情報.
        /// </summary>
        internal static string recvqso {
            get {
                return ResourceManager.GetString("recvqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択を記憶.
        /// </summary>
        internal static string remembermychoice {
            get {
                return ResourceManager.GetString("remembermychoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送信出力を報告.
        /// </summary>
        internal static string reportpwr {
            get {
                return ResourceManager.GetString("reportpwr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 異周波数（Split）情報を報告.
        /// </summary>
        internal static string reportsplit {
            get {
                return ResourceManager.GetString("reportsplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再試行回数は0より大きい整数でなければなりません！.
        /// </summary>
        internal static string retrycountreq {
            get {
                return ResourceManager.GetString("retrycountreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロードを再試行中.
        /// </summary>
        internal static string retryingqso {
            get {
                return ResourceManager.GetString("retryingqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再送信.
        /// </summary>
        internal static string reuploadsel {
            get {
                return ResourceManager.GetString("reuploadsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一部の無線機は送信出力の読み取りをサポートしていないか、誤ったデータを返すため、この機能はデフォルトで無効になっています。.
        /// </summary>
        internal static string rfpowerhelp {
            get {
                return ResourceManager.GetString("rfpowerhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無線機バックエンド制御システム.
        /// </summary>
        internal static string rigbackendsystem {
            get {
                return ResourceManager.GetString("rigbackendsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigctldコマンドライン引数.
        /// </summary>
        internal static string rigctldcmdarg {
            get {
                return ResourceManager.GetString("rigctldcmdarg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigctldサービスが起動していません。設定を確認してください！.
        /// </summary>
        internal static string rigctldnotstart {
            get {
                return ResourceManager.GetString("rigctldnotstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無線機データ.
        /// </summary>
        internal static string rigdata {
            get {
                return ResourceManager.GetString("rigdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無線機モデル.
        /// </summary>
        internal static string rigmodel {
            get {
                return ResourceManager.GetString("rigmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無線機との通信がタイムアウトしました。接続を確認してください！.
        /// </summary>
        internal static string rigtimeout {
            get {
                return ResourceManager.GetString("rigtimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サンプル数 = .
        /// </summary>
        internal static string samplecount {
            get {
                return ResourceManager.GetString("samplecount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更を適用.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログを保存.
        /// </summary>
        internal static string savelog {
            get {
                return ResourceManager.GetString("savelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログを保存先....
        /// </summary>
        internal static string savelogto {
            get {
                return ResourceManager.GetString("savelogto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて選択.
        /// </summary>
        internal static string selall {
            get {
                return ResourceManager.GetString("selall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密度色を表示.
        /// </summary>
        internal static string showdensitycolor {
            get {
                return ResourceManager.GetString("showdensitycolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロード失敗項目のみ表示.
        /// </summary>
        internal static string showfailonly {
            get {
                return ResourceManager.GetString("showfailonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プログラムを閉じる.
        /// </summary>
        internal static string shutdown {
            get {
                return ResourceManager.GetString("shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信号カウント.
        /// </summary>
        internal static string signalcount {
            get {
                return ResourceManager.GetString("signalcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信号分布極座標プロット.
        /// </summary>
        internal static string signalpolarchart {
            get {
                return ResourceManager.GetString("signalpolarchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字列の前後にスペースは使用できません.
        /// </summary>
        internal static string spacenotallowed {
            get {
                return ResourceManager.GetString("spacenotallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セミコロンで区切られたアドレスには、http(s) の指定が必要です.
        /// </summary>
        internal static string spiltby {
            get {
                return ResourceManager.GetString("spiltby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一部の無線機は異周波数（Split）情報の読み取りをサポートしていないか、誤ったデータを返すため、この機能はデフォルトで無効になっています。.
        /// </summary>
        internal static string splithelp {
            get {
                return ResourceManager.GetString("splithelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLは http:// または https:// で始まる必要があります！.
        /// </summary>
        internal static string startwithhttp {
            get {
                return ResourceManager.GetString("startwithhttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステーション方位分布 - {0}バンド {1}.
        /// </summary>
        internal static string stationbearing {
            get {
                return ResourceManager.GetString("stationbearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステーション距離分布 - {0}バンド {1}.
        /// </summary>
        internal static string stationdistance {
            get {
                return ResourceManager.GetString("stationdistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudlog ステーションID.
        /// </summary>
        internal static string stationid {
            get {
                return ResourceManager.GetString("stationid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステーション名.
        /// </summary>
        internal static string stationname {
            get {
                return ResourceManager.GetString("stationname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デコード済みステーション統計.
        /// </summary>
        internal static string stationstatisticgraph {
            get {
                return ResourceManager.GetString("stationstatisticgraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ストップビット.
        /// </summary>
        internal static string stopbit {
            get {
                return ResourceManager.GetString("stopbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功！.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このQSOは正常にアップロードされました。.
        /// </summary>
        internal static string successqso {
            get {
                return ResourceManager.GetString("successqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同時に無線機情報を次の宛先にも報告.
        /// </summary>
        internal static string syncrigto {
            get {
                return ResourceManager.GetString("syncrigto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロード失敗.
        /// </summary>
        internal static string t_Fail {
            get {
                return ResourceManager.GetString("t_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロードを無視.
        /// </summary>
        internal static string t_Ignored {
            get {
                return ResourceManager.GetString("t_Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待機中....
        /// </summary>
        internal static string t_Pending {
            get {
                return ResourceManager.GetString("t_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再試行中....
        /// </summary>
        internal static string t_Retrying {
            get {
                return ResourceManager.GetString("t_Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロード成功.
        /// </summary>
        internal static string t_Success {
            get {
                return ResourceManager.GetString("t_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロード中...
        /// </summary>
        internal static string t_Uploading {
            get {
                return ResourceManager.GetString("t_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象無線機.
        /// </summary>
        internal static string targetrig {
            get {
                return ResourceManager.GetString("targetrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 設定を変更するたびに、「テスト」をクリックして変更をテスト・適用する必要があります。.
        /// </summary>
        internal static string testandapply {
            get {
                return ResourceManager.GetString("testandapply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テスト.
        /// </summary>
        internal static string testconn {
            get {
                return ResourceManager.GetString("testconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テスト中....
        /// </summary>
        internal static string testing {
            get {
                return ResourceManager.GetString("testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テーマカラー.
        /// </summary>
        internal static string themecolor {
            get {
                return ResourceManager.GetString("themecolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サードパーティログシステム.
        /// </summary>
        internal static string thirdpartylogsys {
            get {
                return ResourceManager.GetString("thirdpartylogsys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string titleerror {
            get {
                return ResourceManager.GetString("titleerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヒント.
        /// </summary>
        internal static string titleinfo {
            get {
                return ResourceManager.GetString("titleinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        internal static string titlesuccess {
            get {
                return ResourceManager.GetString("titlesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意.
        /// </summary>
        internal static string titlewarning {
            get {
                return ResourceManager.GetString("titlewarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツール.
        /// </summary>
        internal static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上位10 DXCC - {0}バンド {1}.
        /// </summary>
        internal static string top10decoded {
            get {
                return ResourceManager.GetString("top10decoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 総デコード数：.
        /// </summary>
        internal static string totaldec {
            get {
                return ResourceManager.GetString("totaldec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 総デコード数 / QSO数：.
        /// </summary>
        internal static string totaldivqso {
            get {
                return ResourceManager.GetString("totaldivqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 記録済み数：.
        /// </summary>
        internal static string totalrec {
            get {
                return ResourceManager.GetString("totalrec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロード済み数：.
        /// </summary>
        internal static string totaluploaded {
            get {
                return ResourceManager.GetString("totaluploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to トレイに最小化.
        /// </summary>
        internal static string totray {
            get {
                return ResourceManager.GetString("totray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TQSLパスワード.
        /// </summary>
        internal static string tqslpassword {
            get {
                return ResourceManager.GetString("tqslpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TQSLパス.
        /// </summary>
        internal static string tqslpath {
            get {
                return ResourceManager.GetString("tqslpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 透明度.
        /// </summary>
        internal static string transparency {
            get {
                return ResourceManager.GetString("transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送信中....
        /// </summary>
        internal static string txing {
            get {
                return ResourceManager.GetString("txing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポート番号はJTDX/wsjt-xの設定と一致させる必要があります。デフォルトは2237です.
        /// </summary>
        internal static string udpporthelp {
            get {
                return ResourceManager.GetString("udpporthelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDPサーバー.
        /// </summary>
        internal static string udpserver {
            get {
                return ResourceManager.GetString("udpserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP接続がタイムアウトしました！.
        /// </summary>
        internal static string udptimeout {
            get {
                return ResourceManager.GetString("udptimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIキーの有効性を確認できません。入力されたアドレスが正しいか確認してください！.
        /// </summary>
        internal static string unable2checkapi {
            get {
                return ResourceManager.GetString("unable2checkapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不明.
        /// </summary>
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サポートされていない無線機周波数：.
        /// </summary>
        internal static string unsupportedrigfreq {
            get {
                return ResourceManager.GetString("unsupportedrigfreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サポートされていない無線機モード：.
        /// </summary>
        internal static string unsupportedrigmode {
            get {
                return ResourceManager.GetString("unsupportedrigmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新コールサインと国データ.
        /// </summary>
        internal static string updatebigcty {
            get {
                return ResourceManager.GetString("updatebigcty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コールサインと国データの更新に失敗しました：{0}！.
        /// </summary>
        internal static string updatebigctyfailed {
            get {
                return ResourceManager.GetString("updatebigctyfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コールサインと国データの更新が成功しました！
        ///コールサイン規則を{0}件、国データを{1}件書き込みました.
        /// </summary>
        internal static string updatebigctysuccess {
            get {
                return ResourceManager.GetString("updatebigctysuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudlogにQSOを自動アップロード.
        /// </summary>
        internal static string upload2cloudlog {
            get {
                return ResourceManager.GetString("upload2cloudlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClublogにQSOを自動アップロード.
        /// </summary>
        internal static string upload2clublog {
            get {
                return ResourceManager.GetString("upload2clublog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HamCQにQSOを自動アップロード.
        /// </summary>
        internal static string upload2hamcq {
            get {
                return ResourceManager.GetString("upload2hamcq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅️ QSOのアップロードに成功しました！.
        /// </summary>
        internal static string uploadedaqso {
            get {
                return ResourceManager.GetString("uploadedaqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☹️ QSOのアップロードに失敗しました！.
        /// </summary>
        internal static string uploadfailedaqso {
            get {
                return ResourceManager.GetString("uploadfailedaqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロード中....
        /// </summary>
        internal static string uploading {
            get {
                return ResourceManager.GetString("uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このQSOをアップロードしています。.
        /// </summary>
        internal static string uploadingqso {
            get {
                return ResourceManager.GetString("uploadingqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無線機情報をアップロード.
        /// </summary>
        internal static string uploadriginfo {
            get {
                return ResourceManager.GetString("uploadriginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 報告ステータス.
        /// </summary>
        internal static string uploadstatus {
            get {
                return ResourceManager.GetString("uploadstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例: http://cloudlog.com.
        /// </summary>
        internal static string urlexample {
            get {
                return ResourceManager.GetString("urlexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL形式が不正です！.
        /// </summary>
        internal static string urlformaterror {
            get {
                return ResourceManager.GetString("urlformaterror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部Rigctldサービスを使用.
        /// </summary>
        internal static string useexternalrigctld {
            get {
                return ResourceManager.GetString("useexternalrigctld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー名.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続待機中...
        /// </summary>
        internal static string waitconn {
            get {
                return ResourceManager.GetString("waitconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 過去5分間の1分あたり平均QSO数。.
        /// </summary>
        internal static string within5min {
            get {
                return ResourceManager.GetString("within5min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヒートマップ - {0}バンド {1}.
        /// </summary>
        internal static string worldheatmap {
            get {
                return ResourceManager.GetString("worldheatmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年間QSO数.
        /// </summary>
        internal static string yearqsos {
            get {
                return ResourceManager.GetString("yearqsos", resourceCulture);
            }
        }
    }
}
