//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudlogHelper.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_zh_hant {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_zh_hant() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudlogHelper.Resources.Language.Language.zh-hant", typeof(Language_zh_hant).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關於.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接受.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 進階設定.
        /// </summary>
        internal static string advancedsettings {
            get {
                return ResourceManager.GetString("advancedsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允許外部控制.
        /// </summary>
        internal static string allowexternalcontrol {
            get {
                return ResourceManager.GetString("allowexternalcontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允許請求代理.
        /// </summary>
        internal static string allowproxy {
            get {
                return ResourceManager.GetString("allowproxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角度權重.
        /// </summary>
        internal static string angweight {
            get {
                return ResourceManager.GetString("angweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API金鑰.
        /// </summary>
        internal static string apikey {
            get {
                return ResourceManager.GetString("apikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動更新台站資訊.
        /// </summary>
        internal static string autopollstatus {
            get {
                return ResourceManager.GetString("autopollstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動上傳QSO.
        /// </summary>
        internal static string autoqsoupload {
            get {
                return ResourceManager.GetString("autoqsoupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動選擇.
        /// </summary>
        internal static string autosel {
            get {
                return ResourceManager.GetString("autosel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電臺數據自動上報.
        /// </summary>
        internal static string autoupdateriginfo {
            get {
                return ResourceManager.GetString("autoupdateriginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動上傳QSO到.
        /// </summary>
        internal static string autoupload2 {
            get {
                return ResourceManager.GetString("autoupload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本資訊.
        /// </summary>
        internal static string basicinfo {
            get {
                return ResourceManager.GetString("basicinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基礎設定.
        /// </summary>
        internal static string basicsettings {
            get {
                return ResourceManager.GetString("basicsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鮑率.
        /// </summary>
        internal static string baudrate {
            get {
                return ResourceManager.GetString("baudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角度（度）.
        /// </summary>
        internal static string bearingdeg {
            get {
                return ResourceManager.GetString("bearingdeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您可以選擇cty.dat或bigcty.dat進行導入。您可以在https://www.country-files.com/找到。.
        /// </summary>
        internal static string bigctyhint {
            get {
                return ResourceManager.GetString("bigctyhint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 啟動失敗！是否嘗試重置所有設定？.
        /// </summary>
        internal static string bootfail {
            get {
                return ResourceManager.GetString("bootfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 計算中....
        /// </summary>
        internal static string calculating {
            get {
                return ResourceManager.GetString("calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 呼號.
        /// </summary>
        internal static string callsign {
            get {
                return ResourceManager.GetString("callsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圖表.
        /// </summary>
        internal static string charts {
            get {
                return ResourceManager.GetString("charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圖表功能被禁用，請在設定中啟用！.
        /// </summary>
        internal static string chartsdisabled {
            get {
                return ResourceManager.GetString("chartsdisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請檢查電臺連線！.
        /// </summary>
        internal static string checkrigconn {
            get {
                return ResourceManager.GetString("checkrigconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudlog Helper能夠連線CLH-Server，自動上報解碼的數據模式資訊和電臺資訊到伺服器。當您使用特定的安卓app連線到伺服器時，伺服器將會推送資訊到您的手機上。.
        /// </summary>
        internal static string clhhintinfo {
            get {
                return ResourceManager.GetString("clhhintinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLH伺服器IP.
        /// </summary>
        internal static string clhseraddr {
            get {
                return ResourceManager.GetString("clhseraddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLH伺服器金鑰.
        /// </summary>
        internal static string clhserkey {
            get {
                return ResourceManager.GetString("clhserkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLH伺服器埠.
        /// </summary>
        internal static string clhserport {
            get {
                return ResourceManager.GetString("clhserport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLH伺服器.
        /// </summary>
        internal static string clhserver {
            get {
                return ResourceManager.GetString("clhserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用TLS.
        /// </summary>
        internal static string clhusetls {
            get {
                return ResourceManager.GetString("clhusetls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉視窗.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您希望最小化到托盤還是關閉本程式？.
        /// </summary>
        internal static string closeormin {
            get {
                return ResourceManager.GetString("closeormin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 填寫您的apikey。這個key需要具備讀/寫許可權。可在主頁賬號的下拉方塊中找到。.
        /// </summary>
        internal static string cloudlogapihelp {
            get {
                return ResourceManager.GetString("cloudlogapihelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以在主頁賬號的下拉方塊中“站點地址”找到。.
        /// </summary>
        internal static string cloudlogstationid {
            get {
                return ResourceManager.GetString("cloudlogstationid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只需填寫網域名稱，不需要包含index.php/api/qso，程式會自動填充。.
        /// </summary>
        internal static string cloudlogurlhelp {
            get {
                return ResourceManager.GetString("cloudlogurlhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clublog設定.
        /// </summary>
        internal static string clublogsettings {
            get {
                return ResourceManager.GetString("clublogsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果此欄位不為空，軟體將使用填寫的內容作為啟動rigctld的預設引數，其他所有配置將被忽略。.
        /// </summary>
        internal static string cmdarghelp {
            get {
                return ResourceManager.GetString("cmdarghelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudlog配置無效，請在設定中修改！.
        /// </summary>
        internal static string confcloudlogfirst {
            get {
                return ResourceManager.GetString("confcloudlogfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLRIG配置有誤，請在設定中修正！.
        /// </summary>
        internal static string confflrigfirst {
            get {
                return ResourceManager.GetString("confflrigfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamlib配置無效，請在設定中修改！.
        /// </summary>
        internal static string confhamlibfirst {
            get {
                return ResourceManager.GetString("confhamlibfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檢測到進程 {replace01} 正在執行，可能影響電臺數據自動上報功能！.
        /// </summary>
        internal static string conflicthamlib {
            get {
                return ResourceManager.GetString("conflicthamlib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請檢查OmniRig配置！.
        /// </summary>
        internal static string confomnifirst {
            get {
                return ResourceManager.GetString("confomnifirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制面板.
        /// </summary>
        internal static string controlpanel {
            get {
                return ResourceManager.GetString("controlpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 當前頻率.
        /// </summary>
        internal static string currentfreq {
            get {
                return ResourceManager.GetString("currentfreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 當前模式.
        /// </summary>
        internal static string currrentmode {
            get {
                return ResourceManager.GetString("currrentmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色模式.
        /// </summary>
        internal static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料位.
        /// </summary>
        internal static string databit {
            get {
                return ResourceManager.GetString("databit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今日QSO數.
        /// </summary>
        internal static string dayqsos {
            get {
                return ResourceManager.GetString("dayqsos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除選中項.
        /// </summary>
        internal static string delsel {
            get {
                return ResourceManager.GetString("delsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拒絕.
        /// </summary>
        internal static string deny {
            get {
                return ResourceManager.GetString("deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 裝置埠.
        /// </summary>
        internal static string deviceport {
            get {
                return ResourceManager.GetString("deviceport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用圖表功能（僅低效能裝置）.
        /// </summary>
        internal static string disablecharts {
            get {
                return ResourceManager.GetString("disablecharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用PTT控制.
        /// </summary>
        internal static string disableptt {
            get {
                return ResourceManager.GetString("disableptt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部分Linux發行版中如果不禁用rts/dtr可能導致PTT無法正確初始化，表現為PTT始終處於觸發狀態。.
        /// </summary>
        internal static string disableptthelp {
            get {
                return ResourceManager.GetString("disableptthelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string discard {
            get {
                return ResourceManager.GetString("discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歡迎使用Cloudlog Helper v{1}!
        ///
        ///在您開始使用前，請先閱讀並同意下方的【免責宣告與使用者協議】
        ///
        ///【免責宣告與使用者協議】
        ///本軟體採用The Unlicense協議開源，按“原樣”提供，僅供技術交流與學習之用。使用者需自行承擔所有風險。
        ///開發者對因使用本軟體而產生的任何數據丟失、裝置損壞或其他損失概不負責。
        ///繼續使用即表示您已閱讀並同意上述條款及專案主頁上的完整免責宣告 (https://github.com/sydneyowl/cloudlog-helper)。
        ///.
        /// </summary>
        internal static string disclaimer {
            get {
                return ResourceManager.GetString("disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 距離（公里）.
        /// </summary>
        internal static string distkm {
            get {
                return ResourceManager.GetString("distkm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 距離權重.
        /// </summary>
        internal static string distweight {
            get {
                return ResourceManager.GetString("distweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雙擊查看更多.
        /// </summary>
        internal static string doubletap2seemore {
            get {
                return ResourceManager.GetString("doubletap2seemore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程式已在執行！.
        /// </summary>
        internal static string dupeinstance {
            get {
                return ResourceManager.GetString("dupeinstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不允許同時啟用兩個電臺後端控制服務！.
        /// </summary>
        internal static string duperigservdetected {
            get {
                return ResourceManager.GetString("duperigservdetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電子郵箱.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 進階設定.
        /// </summary>
        internal static string enableadvanced {
            get {
                return ResourceManager.GetString("enableadvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 啟用CLH伺服器.
        /// </summary>
        internal static string enableclhserver {
            get {
                return ResourceManager.GetString("enableclhserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允許外部連線.
        /// </summary>
        internal static string enableoutsideconn {
            get {
                return ResourceManager.GetString("enableoutsideconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 啟用UDP伺服器.
        /// </summary>
        internal static string enableudpserver {
            get {
                return ResourceManager.GetString("enableudpserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 錯誤.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出錯啦！.
        /// </summary>
        internal static string errorccurred {
            get {
                return ResourceManager.GetString("errorccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匯出.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匯出為adi.
        /// </summary>
        internal static string export2adif {
            get {
                return ResourceManager.GetString("export2adif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigctld服務地址.
        /// </summary>
        internal static string externalrigctldhost {
            get {
                return ResourceManager.GetString("externalrigctldhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失敗！.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此QSO上傳失敗。.
        /// </summary>
        internal static string failedqso {
            get {
                return ResourceManager.GetString("failedqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法獲取電臺數據！.
        /// </summary>
        internal static string failedriginfo {
            get {
                return ResourceManager.GetString("failedriginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法獲取站點資訊！.
        /// </summary>
        internal static string failedstationinfo {
            get {
                return ResourceManager.GetString("failedstationinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法獲取站點數據！.
        /// </summary>
        internal static string failedstationstat {
            get {
                return ResourceManager.GetString("failedstationstat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO同步出錯：.
        /// </summary>
        internal static string failedsyncqso {
            get {
                return ResourceManager.GetString("failedsyncqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法從命令列引數中提取埠號。請顯式使用引數-t指明。.
        /// </summary>
        internal static string failextractinfo {
            get {
                return ResourceManager.GetString("failextractinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 與電臺通訊失敗！.
        /// </summary>
        internal static string failrigcomm {
            get {
                return ResourceManager.GetString("failrigcomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法上傳到{addr}，請檢視日誌！.
        /// </summary>
        internal static string failuploadriginfoto {
            get {
                return ResourceManager.GetString("failuploadriginfoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請完整填寫所有資訊！.
        /// </summary>
        internal static string fillall {
            get {
                return ResourceManager.GetString("fillall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 過濾重複樣本（呼號）.
        /// </summary>
        internal static string filterdupebycallsign {
            get {
                return ResourceManager.GetString("filterdupebycallsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轉發解碼資訊到http伺服器.
        /// </summary>
        internal static string forward2tcp {
            get {
                return ResourceManager.GetString("forward2tcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轉發原始UDP數據包到.
        /// </summary>
        internal static string forwardmsg {
            get {
                return ResourceManager.GetString("forwardmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轉發原始UDP數據包到.
        /// </summary>
        internal static string forwardto {
            get {
                return ResourceManager.GetString("forwardto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 獲取數據中....
        /// </summary>
        internal static string gettinginfo {
            get {
                return ResourceManager.GetString("gettinginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 座標.
        /// </summary>
        internal static string grid {
            get {
                return ResourceManager.GetString("grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 網格座標為空或有誤，請檢查設定！
        ///.
        /// </summary>
        internal static string griderror {
            get {
                return ResourceManager.GetString("griderror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HamCQ設定.
        /// </summary>
        internal static string hamcqsettings {
            get {
                return ResourceManager.GetString("hamcqsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幫助.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 希望您能將出錯資訊反饋到Github，幫助開發者修正此BUG！.
        /// </summary>
        internal static string helpfeedback {
            get {
                return ResourceManager.GetString("helpfeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此QSO已被忽略 - 是不是把所有第三方日誌的上傳功能都關了？.
        /// </summary>
        internal static string ignoreqso {
            get {
                return ResourceManager.GetString("ignoreqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此操作將永久忽略選中的QSO，後續QSO助手掃描本地QSO時將忽略這些項。是否繼續？.
        /// </summary>
        internal static string ignoreqsopermanently {
            get {
                return ResourceManager.GetString("ignoreqsopermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamlib初始化失敗!.
        /// </summary>
        internal static string inithamlibfailed {
            get {
                return ResourceManager.GetString("inithamlibfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例項名稱.
        /// </summary>
        internal static string instancename {
            get {
                return ResourceManager.GetString("instancename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此欄位為軟體註冊到clh-server時使用的名稱。此名稱應當是唯一的。.
        /// </summary>
        internal static string instancenamehint {
            get {
                return ResourceManager.GetString("instancenamehint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您使用的後端服務似乎是{replace01}而不是Cloudlog，因此軟體部分功能可能不支援。.
        /// </summary>
        internal static string instanceuncompitable {
            get {
                return ResourceManager.GetString("instanceuncompitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址無效！.
        /// </summary>
        internal static string invalidaddr {
            get {
                return ResourceManager.GetString("invalidaddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無效的ADIF！.
        /// </summary>
        internal static string invalidadif {
            get {
                return ResourceManager.GetString("invalidadif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此APIKEY無效！.
        /// </summary>
        internal static string invalidapikey {
            get {
                return ResourceManager.GetString("invalidapikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置無效！.
        /// </summary>
        internal static string invalidconf {
            get {
                return ResourceManager.GetString("invalidconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 埠號無效.
        /// </summary>
        internal static string invalidport {
            get {
                return ResourceManager.GetString("invalidport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP伺服器配置無效！.
        /// </summary>
        internal static string invalidudpconf {
            get {
                return ResourceManager.GetString("invalidudpconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL無效！.
        /// </summary>
        internal static string invalidurl {
            get {
                return ResourceManager.GetString("invalidurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K值(KNN).
        /// </summary>
        internal static string kval {
            get {
                return ResourceManager.GetString("kval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIKEY需要讀/寫許可權但提供的apikey只有讀許可權！.
        /// </summary>
        internal static string lackwriteaccess {
            get {
                return ResourceManager.GetString("lackwriteaccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 緯度.
        /// </summary>
        internal static string latitude {
            get {
                return ResourceManager.GetString("latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 淺色模式.
        /// </summary>
        internal static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 經度.
        /// </summary>
        internal static string longitude {
            get {
                return ResourceManager.GetString("longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅️ 完成了一個QSO！.
        /// </summary>
        internal static string madeaqso {
            get {
                return ResourceManager.GetString("madeaqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大取樣點數量.
        /// </summary>
        internal static string maxsamplecount {
            get {
                return ResourceManager.GetString("maxsamplecount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本月QSO數.
        /// </summary>
        internal static string monthqsos {
            get {
                return ResourceManager.GetString("monthqsos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命令列引數必須新增-vvvvv！.
        /// </summary>
        internal static string mustverbose {
            get {
                return ResourceManager.GetString("mustverbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的網格座標.
        /// </summary>
        internal static string mygrid {
            get {
                return ResourceManager.GetString("mygrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下次上報時間.
        /// </summary>
        internal static string nextuploadtime {
            get {
                return ResourceManager.GetString("nextuploadtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （無數據）.
        /// </summary>
        internal static string nodata {
            get {
                return ResourceManager.GetString("nodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意.
        /// </summary>
        internal static string notice {
            get {
                return ResourceManager.GetString("notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此項不能為空！.
        /// </summary>
        internal static string notnull {
            get {
                return ResourceManager.GetString("notnull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請檢查OmniRig是否已正確安裝。另外，OmniRig目前僅在非AOT編譯的Windows平台上支援。.
        /// </summary>
        internal static string omniinitfailed {
            get {
                return ResourceManager.GetString("omniinitfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只需輸入主網域名稱，不允許以/api/qso結尾！.
        /// </summary>
        internal static string onlymaindomain {
            get {
                return ResourceManager.GetString("onlymaindomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作員.
        /// </summary>
        internal static string op {
            get {
                return ResourceManager.GetString("op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開啟.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開啟配置目錄.
        /// </summary>
        internal static string openconfpath {
            get {
                return ResourceManager.GetString("openconfpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開啟快取目錄.
        /// </summary>
        internal static string opentempfolder {
            get {
                return ResourceManager.GetString("opentempfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暫停.
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此QSO正在等待上傳。.
        /// </summary>
        internal static string pendingqso {
            get {
                return ResourceManager.GetString("pendingqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請在設定中開啟“電臺數據自動上報”.
        /// </summary>
        internal static string polldisabled {
            get {
                return ResourceManager.GetString("polldisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輪詢間隔（秒）.
        /// </summary>
        internal static string pollinterval {
            get {
                return ResourceManager.GetString("pollinterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輪詢間隔必須為整數且大於1！.
        /// </summary>
        internal static string pollintervalreq {
            get {
                return ResourceManager.GetString("pollintervalreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 埠號.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允許代理其他應用程式傳送的請求。用於避免同時向rigctld傳送請求時可能造成的衝突。.
        /// </summary>
        internal static string proxyhelp {
            get {
                return ResourceManager.GetString("proxyhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----請選擇----.
        /// </summary>
        internal static string psesel {
            get {
                return ResourceManager.GetString("psesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請先勾選QSO!.
        /// </summary>
        internal static string pseselfirst {
            get {
                return ResourceManager.GetString("pseselfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出現下列情況時推送系統通知：.
        /// </summary>
        internal static string pushnotificationon {
            get {
                return ResourceManager.GetString("pushnotificationon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO上傳助手.
        /// </summary>
        internal static string qsoassistant {
            get {
                return ResourceManager.GetString("qsoassistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 呼號: {0}, 國家: {1} ({8}), 網格: {9},  頻率: {10} ({11}),  模式: {12}, 時間: {14} 至 {15}, 訊號報告: 傳送 &apos;{16}&apos; / 接收 &apos;{17}&apos;.
        /// </summary>
        internal static string qsoconcisetemplate {
            get {
                return ResourceManager.GetString("qsoconcisetemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO完成時.
        /// </summary>
        internal static string qsofinished {
            get {
                return ResourceManager.GetString("qsofinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO速率：.
        /// </summary>
        internal static string qsorate {
            get {
                return ResourceManager.GetString("qsorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO上傳失敗重試次數.
        /// </summary>
        internal static string qsoretrycount {
            get {
                return ResourceManager.GetString("qsoretrycount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在同步QSO....
        /// </summary>
        internal static string qsosyncing {
            get {
                return ResourceManager.GetString("qsosyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO同步成功！.
        /// </summary>
        internal static string qsosyncsucc {
            get {
                return ResourceManager.GetString("qsosyncsucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 呼號: {0}
        ///• 國家: {1} (CQ區: {2}, ITU區: {3})
        ///• 大洲: {4}
        ///• 位置: 緯度 {5}°, 經度 {6}° (GMT{7})
        ///• DXCC: {8}
        ///• 網格: {9}
        ///• 頻率: {10} ({11})
        ///• 模式: {12} (父模式: {13})
        ///• 時間: {14} 至 {15}
        ///• 訊號報告: 傳送 &apos;{16}&apos; / 接收 &apos;{17}&apos;
        ///• 功率: {18}
        ///• 操作員: {19}
        ///• 本機呼號: {20}
        ///• 本機網格: {21}
        ///• 交換資訊: 傳送 &apos;{22}&apos; / 接收 &apos;{23}&apos;
        ///• 傳播模式: {24}
        ///• 姓名: {25}
        ///• 備註: {26}
        ///• 客戶端: {27}
        ///• 上傳狀態: {28}
        ///• 失敗原因: {29}.
        /// </summary>
        internal static string qsotemplate {
            get {
                return ResourceManager.GetString("qsotemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO自動上傳功能未啟用。.
        /// </summary>
        internal static string qsouploaddisabled {
            get {
                return ResourceManager.GetString("qsouploaddisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO上傳完成時.
        /// </summary>
        internal static string qsouploaded {
            get {
                return ResourceManager.GetString("qsouploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTH別名（可選）.
        /// </summary>
        internal static string qthnick {
            get {
                return ResourceManager.GetString("qthnick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTH暱稱（可選）.
        /// </summary>
        internal static string qthnickname {
            get {
                return ResourceManager.GetString("qthnickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輪詢間隔應當大於一秒！.
        /// </summary>
        internal static string reachminiumpollinterval {
            get {
                return ResourceManager.GetString("reachminiumpollinterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已完成的QSO資訊.
        /// </summary>
        internal static string recvqso {
            get {
                return ResourceManager.GetString("recvqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新整理.
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 記住我的選擇.
        /// </summary>
        internal static string remembermychoice {
            get {
                return ResourceManager.GetString("remembermychoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 報告發射功率.
        /// </summary>
        internal static string reportpwr {
            get {
                return ResourceManager.GetString("reportpwr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 報告異頻資訊.
        /// </summary>
        internal static string reportsplit {
            get {
                return ResourceManager.GetString("reportsplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重試次數應為大於0的整數！.
        /// </summary>
        internal static string retrycountreq {
            get {
                return ResourceManager.GetString("retrycountreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在重試上傳.
        /// </summary>
        internal static string retryingqso {
            get {
                return ResourceManager.GetString("retryingqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重傳選中項.
        /// </summary>
        internal static string reuploadsel {
            get {
                return ResourceManager.GetString("reuploadsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部分電臺不支援讀取髮射功率或讀取的數據錯誤，因此本功能預設未開啟。.
        /// </summary>
        internal static string rfpowerhelp {
            get {
                return ResourceManager.GetString("rfpowerhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電臺後端控制系統.
        /// </summary>
        internal static string rigbackendsystem {
            get {
                return ResourceManager.GetString("rigbackendsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigctld命令列引數.
        /// </summary>
        internal static string rigctldcmdarg {
            get {
                return ResourceManager.GetString("rigctldcmdarg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigctld服務未啟動，請檢查設定！.
        /// </summary>
        internal static string rigctldnotstart {
            get {
                return ResourceManager.GetString("rigctldnotstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電臺數據.
        /// </summary>
        internal static string rigdata {
            get {
                return ResourceManager.GetString("rigdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電臺型號.
        /// </summary>
        internal static string rigmodel {
            get {
                return ResourceManager.GetString("rigmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 與電臺通訊超時，請檢查連線！.
        /// </summary>
        internal static string rigtimeout {
            get {
                return ResourceManager.GetString("rigtimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 樣本數 = .
        /// </summary>
        internal static string samplecount {
            get {
                return ResourceManager.GetString("samplecount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 應用更改.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 儲存日誌.
        /// </summary>
        internal static string savelog {
            get {
                return ResourceManager.GetString("savelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 儲存日誌到...
        /// </summary>
        internal static string savelogto {
            get {
                return ResourceManager.GetString("savelogto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全選.
        /// </summary>
        internal static string selall {
            get {
                return ResourceManager.GetString("selall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 展示密度顏色.
        /// </summary>
        internal static string showdensitycolor {
            get {
                return ResourceManager.GetString("showdensitycolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 僅顯示上傳失敗項.
        /// </summary>
        internal static string showfailonly {
            get {
                return ResourceManager.GetString("showfailonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉程式.
        /// </summary>
        internal static string shutdown {
            get {
                return ResourceManager.GetString("shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 訊號計數.
        /// </summary>
        internal static string signalcount {
            get {
                return ResourceManager.GetString("signalcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 訊號分佈極座標圖.
        /// </summary>
        internal static string signalpolarchart {
            get {
                return ResourceManager.GetString("signalpolarchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字串前後不允許空格.
        /// </summary>
        internal static string spacenotallowed {
            get {
                return ResourceManager.GetString("spacenotallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用分號分隔的地址，需指定http(s).
        /// </summary>
        internal static string spiltby {
            get {
                return ResourceManager.GetString("spiltby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部分電臺不支援讀取異頻資訊或讀取的數據錯誤，因此本功能預設未開啟。.
        /// </summary>
        internal static string splithelp {
            get {
                return ResourceManager.GetString("splithelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL 必須以 http:// 或 https:// 開頭！.
        /// </summary>
        internal static string startwithhttp {
            get {
                return ResourceManager.GetString("startwithhttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 站點方位分佈 - {0}波段 {1}.
        /// </summary>
        internal static string stationbearing {
            get {
                return ResourceManager.GetString("stationbearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 站點距離分佈 - {0}波段 {1}.
        /// </summary>
        internal static string stationdistance {
            get {
                return ResourceManager.GetString("stationdistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudlog 站點ID.
        /// </summary>
        internal static string stationid {
            get {
                return ResourceManager.GetString("stationid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 站點名稱.
        /// </summary>
        internal static string stationname {
            get {
                return ResourceManager.GetString("stationname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解碼站點統計.
        /// </summary>
        internal static string stationstatisticgraph {
            get {
                return ResourceManager.GetString("stationstatisticgraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止位.
        /// </summary>
        internal static string stopbit {
            get {
                return ResourceManager.GetString("stopbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功！.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此QSO上傳成功。.
        /// </summary>
        internal static string successqso {
            get {
                return ResourceManager.GetString("successqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同時報告電臺資訊到.
        /// </summary>
        internal static string syncrigto {
            get {
                return ResourceManager.GetString("syncrigto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上傳失敗.
        /// </summary>
        internal static string t_Fail {
            get {
                return ResourceManager.GetString("t_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略上傳.
        /// </summary>
        internal static string t_Ignored {
            get {
                return ResourceManager.GetString("t_Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待中....
        /// </summary>
        internal static string t_Pending {
            get {
                return ResourceManager.GetString("t_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重試中....
        /// </summary>
        internal static string t_Retrying {
            get {
                return ResourceManager.GetString("t_Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上傳成功.
        /// </summary>
        internal static string t_Success {
            get {
                return ResourceManager.GetString("t_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上傳中...
        /// </summary>
        internal static string t_Uploading {
            get {
                return ResourceManager.GetString("t_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目標電臺.
        /// </summary>
        internal static string targetrig {
            get {
                return ResourceManager.GetString("targetrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 每次修改配置後，您必須點選“測試”來測試並應用本次更改。.
        /// </summary>
        internal static string testandapply {
            get {
                return ResourceManager.GetString("testandapply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 測試.
        /// </summary>
        internal static string testconn {
            get {
                return ResourceManager.GetString("testconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 測試中....
        /// </summary>
        internal static string testing {
            get {
                return ResourceManager.GetString("testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主題色.
        /// </summary>
        internal static string themecolor {
            get {
                return ResourceManager.GetString("themecolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第三方日誌系統.
        /// </summary>
        internal static string thirdpartylogsys {
            get {
                return ResourceManager.GetString("thirdpartylogsys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 錯誤.
        /// </summary>
        internal static string titleerror {
            get {
                return ResourceManager.GetString("titleerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string titleinfo {
            get {
                return ResourceManager.GetString("titleinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        internal static string titlesuccess {
            get {
                return ResourceManager.GetString("titlesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意.
        /// </summary>
        internal static string titlewarning {
            get {
                return ResourceManager.GetString("titlewarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具.
        /// </summary>
        internal static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前10 DXCC - {0}波段 {1}.
        /// </summary>
        internal static string top10decoded {
            get {
                return ResourceManager.GetString("top10decoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 總解碼數：.
        /// </summary>
        internal static string totaldec {
            get {
                return ResourceManager.GetString("totaldec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 總解碼數 / QSO數：.
        /// </summary>
        internal static string totaldivqso {
            get {
                return ResourceManager.GetString("totaldivqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已記錄數：.
        /// </summary>
        internal static string totalrec {
            get {
                return ResourceManager.GetString("totalrec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已上傳數：.
        /// </summary>
        internal static string totaluploaded {
            get {
                return ResourceManager.GetString("totaluploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小化到托盤.
        /// </summary>
        internal static string totray {
            get {
                return ResourceManager.GetString("totray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TQSL密碼.
        /// </summary>
        internal static string tqslpassword {
            get {
                return ResourceManager.GetString("tqslpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TQSL路徑.
        /// </summary>
        internal static string tqslpath {
            get {
                return ResourceManager.GetString("tqslpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 透明度.
        /// </summary>
        internal static string transparency {
            get {
                return ResourceManager.GetString("transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 發射中....
        /// </summary>
        internal static string txing {
            get {
                return ResourceManager.GetString("txing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 埠號應與JTDX/wsjt-x中設定的一致.預設為2237.
        /// </summary>
        internal static string udpporthelp {
            get {
                return ResourceManager.GetString("udpporthelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP伺服器.
        /// </summary>
        internal static string udpserver {
            get {
                return ResourceManager.GetString("udpserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP連線超時！.
        /// </summary>
        internal static string udptimeout {
            get {
                return ResourceManager.GetString("udptimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無法檢查apikey的可用性；請檢查輸入的地址是否正確！.
        /// </summary>
        internal static string unable2checkapi {
            get {
                return ResourceManager.GetString("unable2checkapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知.
        /// </summary>
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支援的電臺頻率：.
        /// </summary>
        internal static string unsupportedrigfreq {
            get {
                return ResourceManager.GetString("unsupportedrigfreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支援的電臺模式:.
        /// </summary>
        internal static string unsupportedrigmode {
            get {
                return ResourceManager.GetString("unsupportedrigmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新呼號和國家數據.
        /// </summary>
        internal static string updatebigcty {
            get {
                return ResourceManager.GetString("updatebigcty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新呼號和國家數據失敗：{0}！.
        /// </summary>
        internal static string updatebigctyfailed {
            get {
                return ResourceManager.GetString("updatebigctyfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新呼號和國家數據成功！
        ///寫入呼號規則{0}個，國家數據{1}個.
        /// </summary>
        internal static string updatebigctysuccess {
            get {
                return ResourceManager.GetString("updatebigctysuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動上傳QSO到Cloudlog.
        /// </summary>
        internal static string upload2cloudlog {
            get {
                return ResourceManager.GetString("upload2cloudlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動上傳QSO到Clublog.
        /// </summary>
        internal static string upload2clublog {
            get {
                return ResourceManager.GetString("upload2clublog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動上傳QSO到HamCQ.
        /// </summary>
        internal static string upload2hamcq {
            get {
                return ResourceManager.GetString("upload2hamcq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅️ QSO上傳成功！.
        /// </summary>
        internal static string uploadedaqso {
            get {
                return ResourceManager.GetString("uploadedaqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☹️ QSO 上傳失敗！.
        /// </summary>
        internal static string uploadfailedaqso {
            get {
                return ResourceManager.GetString("uploadfailedaqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上傳中....
        /// </summary>
        internal static string uploading {
            get {
                return ResourceManager.GetString("uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在上傳此QSO。.
        /// </summary>
        internal static string uploadingqso {
            get {
                return ResourceManager.GetString("uploadingqso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上傳電臺資訊.
        /// </summary>
        internal static string uploadriginfo {
            get {
                return ResourceManager.GetString("uploadriginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上報狀態.
        /// </summary>
        internal static string uploadstatus {
            get {
                return ResourceManager.GetString("uploadstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 示例: http://cloudlog.com.
        /// </summary>
        internal static string urlexample {
            get {
                return ResourceManager.GetString("urlexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL格式有誤！.
        /// </summary>
        internal static string urlformaterror {
            get {
                return ResourceManager.GetString("urlformaterror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用外部rigctld服務.
        /// </summary>
        internal static string useexternalrigctld {
            get {
                return ResourceManager.GetString("useexternalrigctld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用者名稱.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待連線...
        /// </summary>
        internal static string waitconn {
            get {
                return ResourceManager.GetString("waitconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5分鐘內取得的每分鐘QSO平均值。.
        /// </summary>
        internal static string within5min {
            get {
                return ResourceManager.GetString("within5min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 熱力圖 - {0}波段 {1}.
        /// </summary>
        internal static string worldheatmap {
            get {
                return ResourceManager.GetString("worldheatmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年度QSO數.
        /// </summary>
        internal static string yearqsos {
            get {
                return ResourceManager.GetString("yearqsos", resourceCulture);
            }
        }
    }
}
