//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudlogHelper.Resources.Language {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language_zh_hant {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_zh_hant() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CloudlogHelper.Resources.Language.Language_zh_hant", typeof(Language_zh_hant).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        public static string advancedsettings {
            get {
                return ResourceManager.GetString("advancedsettings", resourceCulture);
            }
        }
        
        public static string allowexternalcontrol {
            get {
                return ResourceManager.GetString("allowexternalcontrol", resourceCulture);
            }
        }
        
        public static string allowproxy {
            get {
                return ResourceManager.GetString("allowproxy", resourceCulture);
            }
        }
        
        public static string angweight {
            get {
                return ResourceManager.GetString("angweight", resourceCulture);
            }
        }
        
        public static string apikey {
            get {
                return ResourceManager.GetString("apikey", resourceCulture);
            }
        }
        
        public static string autopollstatus {
            get {
                return ResourceManager.GetString("autopollstatus", resourceCulture);
            }
        }
        
        public static string autoqsoupload {
            get {
                return ResourceManager.GetString("autoqsoupload", resourceCulture);
            }
        }
        
        public static string autosel {
            get {
                return ResourceManager.GetString("autosel", resourceCulture);
            }
        }
        
        public static string autoupdateriginfo {
            get {
                return ResourceManager.GetString("autoupdateriginfo", resourceCulture);
            }
        }
        
        public static string autoupload2 {
            get {
                return ResourceManager.GetString("autoupload2", resourceCulture);
            }
        }
        
        public static string basicinfo {
            get {
                return ResourceManager.GetString("basicinfo", resourceCulture);
            }
        }
        
        public static string basicsettings {
            get {
                return ResourceManager.GetString("basicsettings", resourceCulture);
            }
        }
        
        public static string baudrate {
            get {
                return ResourceManager.GetString("baudrate", resourceCulture);
            }
        }
        
        public static string bearingdeg {
            get {
                return ResourceManager.GetString("bearingdeg", resourceCulture);
            }
        }
        
        public static string bootfail {
            get {
                return ResourceManager.GetString("bootfail", resourceCulture);
            }
        }
        
        public static string calculating {
            get {
                return ResourceManager.GetString("calculating", resourceCulture);
            }
        }
        
        public static string callsign {
            get {
                return ResourceManager.GetString("callsign", resourceCulture);
            }
        }
        
        public static string charts {
            get {
                return ResourceManager.GetString("charts", resourceCulture);
            }
        }
        
        public static string chartsdisabled {
            get {
                return ResourceManager.GetString("chartsdisabled", resourceCulture);
            }
        }
        
        public static string checkrigconn {
            get {
                return ResourceManager.GetString("checkrigconn", resourceCulture);
            }
        }
        
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        public static string clhhintinfo {
            get {
                return ResourceManager.GetString("clhhintinfo", resourceCulture);
            }
        }
        
        public static string clhseraddr {
            get {
                return ResourceManager.GetString("clhseraddr", resourceCulture);
            }
        }
        
        public static string clhserkey {
            get {
                return ResourceManager.GetString("clhserkey", resourceCulture);
            }
        }
        
        public static string clhserport {
            get {
                return ResourceManager.GetString("clhserport", resourceCulture);
            }
        }
        
        public static string clhserver {
            get {
                return ResourceManager.GetString("clhserver", resourceCulture);
            }
        }
        
        public static string clhusetls {
            get {
                return ResourceManager.GetString("clhusetls", resourceCulture);
            }
        }
        
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        public static string closeormin {
            get {
                return ResourceManager.GetString("closeormin", resourceCulture);
            }
        }
        
        public static string cloudlogapihelp {
            get {
                return ResourceManager.GetString("cloudlogapihelp", resourceCulture);
            }
        }
        
        public static string cloudlogstationid {
            get {
                return ResourceManager.GetString("cloudlogstationid", resourceCulture);
            }
        }
        
        public static string cloudlogurlhelp {
            get {
                return ResourceManager.GetString("cloudlogurlhelp", resourceCulture);
            }
        }
        
        public static string clublogsettings {
            get {
                return ResourceManager.GetString("clublogsettings", resourceCulture);
            }
        }
        
        public static string cmdarghelp {
            get {
                return ResourceManager.GetString("cmdarghelp", resourceCulture);
            }
        }
        
        public static string confcloudlogfirst {
            get {
                return ResourceManager.GetString("confcloudlogfirst", resourceCulture);
            }
        }
        
        public static string confflrigfirst {
            get {
                return ResourceManager.GetString("confflrigfirst", resourceCulture);
            }
        }
        
        public static string confhamlibfirst {
            get {
                return ResourceManager.GetString("confhamlibfirst", resourceCulture);
            }
        }
        
        public static string conflicthamlib {
            get {
                return ResourceManager.GetString("conflicthamlib", resourceCulture);
            }
        }
        
        public static string confomnifirst {
            get {
                return ResourceManager.GetString("confomnifirst", resourceCulture);
            }
        }
        
        public static string controlpanel {
            get {
                return ResourceManager.GetString("controlpanel", resourceCulture);
            }
        }
        
        public static string currentfreq {
            get {
                return ResourceManager.GetString("currentfreq", resourceCulture);
            }
        }
        
        public static string currrentmode {
            get {
                return ResourceManager.GetString("currrentmode", resourceCulture);
            }
        }
        
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        public static string databit {
            get {
                return ResourceManager.GetString("databit", resourceCulture);
            }
        }
        
        public static string dayqsos {
            get {
                return ResourceManager.GetString("dayqsos", resourceCulture);
            }
        }
        
        public static string delsel {
            get {
                return ResourceManager.GetString("delsel", resourceCulture);
            }
        }
        
        public static string deny {
            get {
                return ResourceManager.GetString("deny", resourceCulture);
            }
        }
        
        public static string deviceport {
            get {
                return ResourceManager.GetString("deviceport", resourceCulture);
            }
        }
        
        public static string disablecharts {
            get {
                return ResourceManager.GetString("disablecharts", resourceCulture);
            }
        }
        
        public static string disableptt {
            get {
                return ResourceManager.GetString("disableptt", resourceCulture);
            }
        }
        
        public static string disableptthelp {
            get {
                return ResourceManager.GetString("disableptthelp", resourceCulture);
            }
        }
        
        public static string discard {
            get {
                return ResourceManager.GetString("discard", resourceCulture);
            }
        }
        
        public static string disclaimer {
            get {
                return ResourceManager.GetString("disclaimer", resourceCulture);
            }
        }
        
        public static string distkm {
            get {
                return ResourceManager.GetString("distkm", resourceCulture);
            }
        }
        
        public static string distweight {
            get {
                return ResourceManager.GetString("distweight", resourceCulture);
            }
        }
        
        public static string doubletap2seemore {
            get {
                return ResourceManager.GetString("doubletap2seemore", resourceCulture);
            }
        }
        
        public static string dupeinstance {
            get {
                return ResourceManager.GetString("dupeinstance", resourceCulture);
            }
        }
        
        public static string duperigservdetected {
            get {
                return ResourceManager.GetString("duperigservdetected", resourceCulture);
            }
        }
        
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        public static string enableadvanced {
            get {
                return ResourceManager.GetString("enableadvanced", resourceCulture);
            }
        }
        
        public static string enableclhserver {
            get {
                return ResourceManager.GetString("enableclhserver", resourceCulture);
            }
        }
        
        public static string enableoutsideconn {
            get {
                return ResourceManager.GetString("enableoutsideconn", resourceCulture);
            }
        }
        
        public static string enableudpserver {
            get {
                return ResourceManager.GetString("enableudpserver", resourceCulture);
            }
        }
        
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        public static string errorccurred {
            get {
                return ResourceManager.GetString("errorccurred", resourceCulture);
            }
        }
        
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        public static string export2adif {
            get {
                return ResourceManager.GetString("export2adif", resourceCulture);
            }
        }
        
        public static string externalrigctldhost {
            get {
                return ResourceManager.GetString("externalrigctldhost", resourceCulture);
            }
        }
        
        public static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        public static string failedqso {
            get {
                return ResourceManager.GetString("failedqso", resourceCulture);
            }
        }
        
        public static string failedriginfo {
            get {
                return ResourceManager.GetString("failedriginfo", resourceCulture);
            }
        }
        
        public static string failedstationinfo {
            get {
                return ResourceManager.GetString("failedstationinfo", resourceCulture);
            }
        }
        
        public static string failedstationstat {
            get {
                return ResourceManager.GetString("failedstationstat", resourceCulture);
            }
        }
        
        public static string failedsyncqso {
            get {
                return ResourceManager.GetString("failedsyncqso", resourceCulture);
            }
        }
        
        public static string failextractinfo {
            get {
                return ResourceManager.GetString("failextractinfo", resourceCulture);
            }
        }
        
        public static string failrigcomm {
            get {
                return ResourceManager.GetString("failrigcomm", resourceCulture);
            }
        }
        
        public static string failuploadriginfoto {
            get {
                return ResourceManager.GetString("failuploadriginfoto", resourceCulture);
            }
        }
        
        public static string fillall {
            get {
                return ResourceManager.GetString("fillall", resourceCulture);
            }
        }
        
        public static string filterdupebycallsign {
            get {
                return ResourceManager.GetString("filterdupebycallsign", resourceCulture);
            }
        }
        
        public static string forward2tcp {
            get {
                return ResourceManager.GetString("forward2tcp", resourceCulture);
            }
        }
        
        public static string forwardmsg {
            get {
                return ResourceManager.GetString("forwardmsg", resourceCulture);
            }
        }
        
        public static string forwardto {
            get {
                return ResourceManager.GetString("forwardto", resourceCulture);
            }
        }
        
        public static string gettinginfo {
            get {
                return ResourceManager.GetString("gettinginfo", resourceCulture);
            }
        }
        
        public static string grid {
            get {
                return ResourceManager.GetString("grid", resourceCulture);
            }
        }
        
        public static string griderror {
            get {
                return ResourceManager.GetString("griderror", resourceCulture);
            }
        }
        
        public static string hamcqsettings {
            get {
                return ResourceManager.GetString("hamcqsettings", resourceCulture);
            }
        }
        
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        public static string helpfeedback {
            get {
                return ResourceManager.GetString("helpfeedback", resourceCulture);
            }
        }
        
        public static string ignoreqso {
            get {
                return ResourceManager.GetString("ignoreqso", resourceCulture);
            }
        }
        
        public static string ignoreqsopermanently {
            get {
                return ResourceManager.GetString("ignoreqsopermanently", resourceCulture);
            }
        }
        
        public static string inithamlibfailed {
            get {
                return ResourceManager.GetString("inithamlibfailed", resourceCulture);
            }
        }
        
        public static string instancename {
            get {
                return ResourceManager.GetString("instancename", resourceCulture);
            }
        }
        
        public static string instancenamehint {
            get {
                return ResourceManager.GetString("instancenamehint", resourceCulture);
            }
        }
        
        public static string instanceuncompitable {
            get {
                return ResourceManager.GetString("instanceuncompitable", resourceCulture);
            }
        }
        
        public static string invalidaddr {
            get {
                return ResourceManager.GetString("invalidaddr", resourceCulture);
            }
        }
        
        public static string invalidadif {
            get {
                return ResourceManager.GetString("invalidadif", resourceCulture);
            }
        }
        
        public static string invalidapikey {
            get {
                return ResourceManager.GetString("invalidapikey", resourceCulture);
            }
        }
        
        public static string invalidconf {
            get {
                return ResourceManager.GetString("invalidconf", resourceCulture);
            }
        }
        
        public static string invalidport {
            get {
                return ResourceManager.GetString("invalidport", resourceCulture);
            }
        }
        
        public static string invalidudpconf {
            get {
                return ResourceManager.GetString("invalidudpconf", resourceCulture);
            }
        }
        
        public static string invalidurl {
            get {
                return ResourceManager.GetString("invalidurl", resourceCulture);
            }
        }
        
        public static string kval {
            get {
                return ResourceManager.GetString("kval", resourceCulture);
            }
        }
        
        public static string lackwriteaccess {
            get {
                return ResourceManager.GetString("lackwriteaccess", resourceCulture);
            }
        }
        
        public static string latitude {
            get {
                return ResourceManager.GetString("latitude", resourceCulture);
            }
        }
        
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        public static string longitude {
            get {
                return ResourceManager.GetString("longitude", resourceCulture);
            }
        }
        
        public static string madeaqso {
            get {
                return ResourceManager.GetString("madeaqso", resourceCulture);
            }
        }
        
        public static string maxsamplecount {
            get {
                return ResourceManager.GetString("maxsamplecount", resourceCulture);
            }
        }
        
        public static string monthqsos {
            get {
                return ResourceManager.GetString("monthqsos", resourceCulture);
            }
        }
        
        public static string mustverbose {
            get {
                return ResourceManager.GetString("mustverbose", resourceCulture);
            }
        }
        
        public static string mygrid {
            get {
                return ResourceManager.GetString("mygrid", resourceCulture);
            }
        }
        
        public static string nextuploadtime {
            get {
                return ResourceManager.GetString("nextuploadtime", resourceCulture);
            }
        }
        
        public static string nodata {
            get {
                return ResourceManager.GetString("nodata", resourceCulture);
            }
        }
        
        public static string notice {
            get {
                return ResourceManager.GetString("notice", resourceCulture);
            }
        }
        
        public static string notnull {
            get {
                return ResourceManager.GetString("notnull", resourceCulture);
            }
        }
        
        public static string omniinitfailed {
            get {
                return ResourceManager.GetString("omniinitfailed", resourceCulture);
            }
        }
        
        public static string onlymaindomain {
            get {
                return ResourceManager.GetString("onlymaindomain", resourceCulture);
            }
        }
        
        public static string op {
            get {
                return ResourceManager.GetString("op", resourceCulture);
            }
        }
        
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        public static string openconfpath {
            get {
                return ResourceManager.GetString("openconfpath", resourceCulture);
            }
        }
        
        public static string opentempfolder {
            get {
                return ResourceManager.GetString("opentempfolder", resourceCulture);
            }
        }
        
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        public static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        public static string pendingqso {
            get {
                return ResourceManager.GetString("pendingqso", resourceCulture);
            }
        }
        
        public static string polldisabled {
            get {
                return ResourceManager.GetString("polldisabled", resourceCulture);
            }
        }
        
        public static string pollinterval {
            get {
                return ResourceManager.GetString("pollinterval", resourceCulture);
            }
        }
        
        public static string pollintervalreq {
            get {
                return ResourceManager.GetString("pollintervalreq", resourceCulture);
            }
        }
        
        public static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        public static string proxyhelp {
            get {
                return ResourceManager.GetString("proxyhelp", resourceCulture);
            }
        }
        
        public static string pseselfirst {
            get {
                return ResourceManager.GetString("pseselfirst", resourceCulture);
            }
        }
        
        public static string pushnotificationon {
            get {
                return ResourceManager.GetString("pushnotificationon", resourceCulture);
            }
        }
        
        public static string qsoassistant {
            get {
                return ResourceManager.GetString("qsoassistant", resourceCulture);
            }
        }
        
        public static string qsoconcisetemplate {
            get {
                return ResourceManager.GetString("qsoconcisetemplate", resourceCulture);
            }
        }
        
        public static string qsofinished {
            get {
                return ResourceManager.GetString("qsofinished", resourceCulture);
            }
        }
        
        public static string qsorate {
            get {
                return ResourceManager.GetString("qsorate", resourceCulture);
            }
        }
        
        public static string qsoretrycount {
            get {
                return ResourceManager.GetString("qsoretrycount", resourceCulture);
            }
        }
        
        public static string qsosyncing {
            get {
                return ResourceManager.GetString("qsosyncing", resourceCulture);
            }
        }
        
        public static string qsosyncsucc {
            get {
                return ResourceManager.GetString("qsosyncsucc", resourceCulture);
            }
        }
        
        public static string qsotemplate {
            get {
                return ResourceManager.GetString("qsotemplate", resourceCulture);
            }
        }
        
        public static string qsouploaddisabled {
            get {
                return ResourceManager.GetString("qsouploaddisabled", resourceCulture);
            }
        }
        
        public static string qsouploaded {
            get {
                return ResourceManager.GetString("qsouploaded", resourceCulture);
            }
        }
        
        public static string qthnick {
            get {
                return ResourceManager.GetString("qthnick", resourceCulture);
            }
        }
        
        public static string qthnickname {
            get {
                return ResourceManager.GetString("qthnickname", resourceCulture);
            }
        }
        
        public static string reachminiumpollinterval {
            get {
                return ResourceManager.GetString("reachminiumpollinterval", resourceCulture);
            }
        }
        
        public static string recvqso {
            get {
                return ResourceManager.GetString("recvqso", resourceCulture);
            }
        }
        
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        public static string remembermychoice {
            get {
                return ResourceManager.GetString("remembermychoice", resourceCulture);
            }
        }
        
        public static string reportpwr {
            get {
                return ResourceManager.GetString("reportpwr", resourceCulture);
            }
        }
        
        public static string reportsplit {
            get {
                return ResourceManager.GetString("reportsplit", resourceCulture);
            }
        }
        
        public static string retrycountreq {
            get {
                return ResourceManager.GetString("retrycountreq", resourceCulture);
            }
        }
        
        public static string retryingqso {
            get {
                return ResourceManager.GetString("retryingqso", resourceCulture);
            }
        }
        
        public static string reuploadsel {
            get {
                return ResourceManager.GetString("reuploadsel", resourceCulture);
            }
        }
        
        public static string rfpowerhelp {
            get {
                return ResourceManager.GetString("rfpowerhelp", resourceCulture);
            }
        }
        
        public static string rigbackendsystem {
            get {
                return ResourceManager.GetString("rigbackendsystem", resourceCulture);
            }
        }
        
        public static string rigctldcmdarg {
            get {
                return ResourceManager.GetString("rigctldcmdarg", resourceCulture);
            }
        }
        
        public static string rigctldnotstart {
            get {
                return ResourceManager.GetString("rigctldnotstart", resourceCulture);
            }
        }
        
        public static string rigdata {
            get {
                return ResourceManager.GetString("rigdata", resourceCulture);
            }
        }
        
        public static string rigmodel {
            get {
                return ResourceManager.GetString("rigmodel", resourceCulture);
            }
        }
        
        public static string rigtimeout {
            get {
                return ResourceManager.GetString("rigtimeout", resourceCulture);
            }
        }
        
        public static string samplecount {
            get {
                return ResourceManager.GetString("samplecount", resourceCulture);
            }
        }
        
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        public static string savelog {
            get {
                return ResourceManager.GetString("savelog", resourceCulture);
            }
        }
        
        public static string savelogto {
            get {
                return ResourceManager.GetString("savelogto", resourceCulture);
            }
        }
        
        public static string selall {
            get {
                return ResourceManager.GetString("selall", resourceCulture);
            }
        }
        
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        public static string showdensitycolor {
            get {
                return ResourceManager.GetString("showdensitycolor", resourceCulture);
            }
        }
        
        public static string showfailonly {
            get {
                return ResourceManager.GetString("showfailonly", resourceCulture);
            }
        }
        
        public static string shutdown {
            get {
                return ResourceManager.GetString("shutdown", resourceCulture);
            }
        }
        
        public static string signalcount {
            get {
                return ResourceManager.GetString("signalcount", resourceCulture);
            }
        }
        
        public static string signalpolarchart {
            get {
                return ResourceManager.GetString("signalpolarchart", resourceCulture);
            }
        }
        
        public static string spacenotallowed {
            get {
                return ResourceManager.GetString("spacenotallowed", resourceCulture);
            }
        }
        
        public static string spiltby {
            get {
                return ResourceManager.GetString("spiltby", resourceCulture);
            }
        }
        
        public static string splithelp {
            get {
                return ResourceManager.GetString("splithelp", resourceCulture);
            }
        }
        
        public static string startwithhttp {
            get {
                return ResourceManager.GetString("startwithhttp", resourceCulture);
            }
        }
        
        public static string stationbearing {
            get {
                return ResourceManager.GetString("stationbearing", resourceCulture);
            }
        }
        
        public static string stationdistance {
            get {
                return ResourceManager.GetString("stationdistance", resourceCulture);
            }
        }
        
        public static string stationid {
            get {
                return ResourceManager.GetString("stationid", resourceCulture);
            }
        }
        
        public static string stationname {
            get {
                return ResourceManager.GetString("stationname", resourceCulture);
            }
        }
        
        public static string stationstatisticgraph {
            get {
                return ResourceManager.GetString("stationstatisticgraph", resourceCulture);
            }
        }
        
        public static string stopbit {
            get {
                return ResourceManager.GetString("stopbit", resourceCulture);
            }
        }
        
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        public static string successqso {
            get {
                return ResourceManager.GetString("successqso", resourceCulture);
            }
        }
        
        public static string syncrigto {
            get {
                return ResourceManager.GetString("syncrigto", resourceCulture);
            }
        }
        
        public static string targetrig {
            get {
                return ResourceManager.GetString("targetrig", resourceCulture);
            }
        }
        
        public static string testandapply {
            get {
                return ResourceManager.GetString("testandapply", resourceCulture);
            }
        }
        
        public static string testconn {
            get {
                return ResourceManager.GetString("testconn", resourceCulture);
            }
        }
        
        public static string testing {
            get {
                return ResourceManager.GetString("testing", resourceCulture);
            }
        }
        
        public static string themecolor {
            get {
                return ResourceManager.GetString("themecolor", resourceCulture);
            }
        }
        
        public static string thirdpartylogsys {
            get {
                return ResourceManager.GetString("thirdpartylogsys", resourceCulture);
            }
        }
        
        public static string titleerror {
            get {
                return ResourceManager.GetString("titleerror", resourceCulture);
            }
        }
        
        public static string titleinfo {
            get {
                return ResourceManager.GetString("titleinfo", resourceCulture);
            }
        }
        
        public static string titlesuccess {
            get {
                return ResourceManager.GetString("titlesuccess", resourceCulture);
            }
        }
        
        public static string titlewarning {
            get {
                return ResourceManager.GetString("titlewarning", resourceCulture);
            }
        }
        
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        public static string top10decoded {
            get {
                return ResourceManager.GetString("top10decoded", resourceCulture);
            }
        }
        
        public static string totaldec {
            get {
                return ResourceManager.GetString("totaldec", resourceCulture);
            }
        }
        
        public static string totaldivqso {
            get {
                return ResourceManager.GetString("totaldivqso", resourceCulture);
            }
        }
        
        public static string totalrec {
            get {
                return ResourceManager.GetString("totalrec", resourceCulture);
            }
        }
        
        public static string totaluploaded {
            get {
                return ResourceManager.GetString("totaluploaded", resourceCulture);
            }
        }
        
        public static string totray {
            get {
                return ResourceManager.GetString("totray", resourceCulture);
            }
        }
        
        public static string tqslpassword {
            get {
                return ResourceManager.GetString("tqslpassword", resourceCulture);
            }
        }
        
        public static string tqslpath {
            get {
                return ResourceManager.GetString("tqslpath", resourceCulture);
            }
        }
        
        public static string transparency {
            get {
                return ResourceManager.GetString("transparency", resourceCulture);
            }
        }
        
        public static string txing {
            get {
                return ResourceManager.GetString("txing", resourceCulture);
            }
        }
        
        public static string t_Fail {
            get {
                return ResourceManager.GetString("t_Fail", resourceCulture);
            }
        }
        
        public static string t_Ignored {
            get {
                return ResourceManager.GetString("t_Ignored", resourceCulture);
            }
        }
        
        public static string t_Pending {
            get {
                return ResourceManager.GetString("t_Pending", resourceCulture);
            }
        }
        
        public static string t_Retrying {
            get {
                return ResourceManager.GetString("t_Retrying", resourceCulture);
            }
        }
        
        public static string t_Success {
            get {
                return ResourceManager.GetString("t_Success", resourceCulture);
            }
        }
        
        public static string t_Uploading {
            get {
                return ResourceManager.GetString("t_Uploading", resourceCulture);
            }
        }
        
        public static string udpporthelp {
            get {
                return ResourceManager.GetString("udpporthelp", resourceCulture);
            }
        }
        
        public static string udpserver {
            get {
                return ResourceManager.GetString("udpserver", resourceCulture);
            }
        }
        
        public static string udptimeout {
            get {
                return ResourceManager.GetString("udptimeout", resourceCulture);
            }
        }
        
        public static string unable2checkapi {
            get {
                return ResourceManager.GetString("unable2checkapi", resourceCulture);
            }
        }
        
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        public static string unsupportedrigfreq {
            get {
                return ResourceManager.GetString("unsupportedrigfreq", resourceCulture);
            }
        }
        
        public static string unsupportedrigmode {
            get {
                return ResourceManager.GetString("unsupportedrigmode", resourceCulture);
            }
        }
        
        public static string upload2cloudlog {
            get {
                return ResourceManager.GetString("upload2cloudlog", resourceCulture);
            }
        }
        
        public static string upload2clublog {
            get {
                return ResourceManager.GetString("upload2clublog", resourceCulture);
            }
        }
        
        public static string upload2hamcq {
            get {
                return ResourceManager.GetString("upload2hamcq", resourceCulture);
            }
        }
        
        public static string uploadedaqso {
            get {
                return ResourceManager.GetString("uploadedaqso", resourceCulture);
            }
        }
        
        public static string uploadfailedaqso {
            get {
                return ResourceManager.GetString("uploadfailedaqso", resourceCulture);
            }
        }
        
        public static string uploading {
            get {
                return ResourceManager.GetString("uploading", resourceCulture);
            }
        }
        
        public static string uploadingqso {
            get {
                return ResourceManager.GetString("uploadingqso", resourceCulture);
            }
        }
        
        public static string uploadriginfo {
            get {
                return ResourceManager.GetString("uploadriginfo", resourceCulture);
            }
        }
        
        public static string uploadstatus {
            get {
                return ResourceManager.GetString("uploadstatus", resourceCulture);
            }
        }
        
        public static string urlexample {
            get {
                return ResourceManager.GetString("urlexample", resourceCulture);
            }
        }
        
        public static string urlformaterror {
            get {
                return ResourceManager.GetString("urlformaterror", resourceCulture);
            }
        }
        
        public static string useexternalrigctld {
            get {
                return ResourceManager.GetString("useexternalrigctld", resourceCulture);
            }
        }
        
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        public static string waitconn {
            get {
                return ResourceManager.GetString("waitconn", resourceCulture);
            }
        }
        
        public static string within5min {
            get {
                return ResourceManager.GetString("within5min", resourceCulture);
            }
        }
        
        public static string worldheatmap {
            get {
                return ResourceManager.GetString("worldheatmap", resourceCulture);
            }
        }
        
        public static string yearqsos {
            get {
                return ResourceManager.GetString("yearqsos", resourceCulture);
            }
        }
        
        public static string updatebigcty {
            get {
                return ResourceManager.GetString("updatebigcty", resourceCulture);
            }
        }
        
        public static string updatebigctysuccess {
            get {
                return ResourceManager.GetString("updatebigctysuccess", resourceCulture);
            }
        }
        
        public static string updatebigctyfailed {
            get {
                return ResourceManager.GetString("updatebigctyfailed", resourceCulture);
            }
        }
        
        public static string psesel {
            get {
                return ResourceManager.GetString("psesel", resourceCulture);
            }
        }
        
        public static string bigctyhint {
            get {
                return ResourceManager.GetString("bigctyhint", resourceCulture);
            }
        }
        
        public static string rightclick2seemore {
            get {
                return ResourceManager.GetString("rightclick2seemore", resourceCulture);
            }
        }
    }
}
