//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudlogHelper.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language_en_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_en_us() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudlogHelper.Resources.Language.Language.en-us", typeof(Language_en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow external control.
        /// </summary>
        public static string AllowExternalControl {
            get {
                return ResourceManager.GetString("AllowExternalControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow proxy requests.
        /// </summary>
        public static string AllowProxy {
            get {
                return ResourceManager.GetString("AllowProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle weight.
        /// </summary>
        public static string AngleWeight {
            get {
                return ResourceManager.GetString("AngleWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto refresh station info.
        /// </summary>
        public static string AutoPollStatus {
            get {
                return ResourceManager.GetString("AutoPollStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto QSO upload.
        /// </summary>
        public static string AutoQsoUpload {
            get {
                return ResourceManager.GetString("AutoQsoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto RIG info upload.
        /// </summary>
        public static string AutoRigUpload {
            get {
                return ResourceManager.GetString("AutoRigUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto selection.
        /// </summary>
        public static string AutoSelect {
            get {
                return ResourceManager.GetString("AutoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto upload rig status.
        /// </summary>
        public static string AutoUpdateRigInfo {
            get {
                return ResourceManager.GetString("AutoUpdateRigInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto upload QSO to.
        /// </summary>
        public static string AutoUploadQsoTo {
            get {
                return ResourceManager.GetString("AutoUploadQsoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto upload QSO to Cloudlog.
        /// </summary>
        public static string AutoUploadQsoToCloudlog {
            get {
                return ResourceManager.GetString("AutoUploadQsoToCloudlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto upload QSO to Clublog.
        /// </summary>
        public static string AutoUploadQsoToClublog {
            get {
                return ResourceManager.GetString("AutoUploadQsoToClublog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto upload QSO to HamCQ.
        /// </summary>
        public static string AutoUploadQsoToHamCq {
            get {
                return ResourceManager.GetString("AutoUploadQsoToHamCq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basical Info.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basical Settings.
        /// </summary>
        public static string BasicSettings {
            get {
                return ResourceManager.GetString("BasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baudrate.
        /// </summary>
        public static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing (degrees).
        /// </summary>
        public static string BearingDegrees {
            get {
                return ResourceManager.GetString("BearingDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose cty.dat or bigcty.dat for import. You can find them at https://www.country-files.com/..
        /// </summary>
        public static string BigCtyHint {
            get {
                return ResourceManager.GetString("BigCtyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start applicaiton. Would you like to reset application?.
        /// </summary>
        public static string BootFailed {
            get {
                return ResourceManager.GetString("BootFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcing...
        /// </summary>
        public static string Calculating {
            get {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callsign.
        /// </summary>
        public static string Callsign {
            get {
                return ResourceManager.GetString("Callsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart feature is disabled, please enable it in settings!.
        /// </summary>
        public static string ChartsDisabled {
            get {
                return ResourceManager.GetString("ChartsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check RIG connection!.
        /// </summary>
        public static string CheckRigConnection {
            get {
                return ResourceManager.GetString("CheckRigConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudlog Helper can connect to CLH-Server and automatically report decoded data mode information and radio information to the server. When you connect to the server using a specific Android app, the server will push information to your phone..
        /// </summary>
        public static string ClhHintInfo {
            get {
                return ResourceManager.GetString("ClhHintInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLH Server.
        /// </summary>
        public static string ClhServer {
            get {
                return ResourceManager.GetString("ClhServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLH Server IP.
        /// </summary>
        public static string ClhServerAddress {
            get {
                return ResourceManager.GetString("ClhServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLH Server key.
        /// </summary>
        public static string ClhServerKey {
            get {
                return ResourceManager.GetString("ClhServerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLH Server Port.
        /// </summary>
        public static string ClhServerPort {
            get {
                return ResourceManager.GetString("ClhServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TLS.
        /// </summary>
        public static string ClhUseTls {
            get {
                return ResourceManager.GetString("ClhUseTls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to minimize to the tray or close the application?.
        /// </summary>
        public static string CloseOrMinimize {
            get {
                return ResourceManager.GetString("CloseOrMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in your api key here. Require Read/Write access.You can find it under API Keys in the Cloudlog dropdown for your account..
        /// </summary>
        public static string CloudlogApiHelp {
            get {
                return ResourceManager.GetString("CloudlogApiHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find it under Station Location in the Cloudlog dropdown for your account..
        /// </summary>
        public static string CloudlogStationId {
            get {
                return ResourceManager.GetString("CloudlogStationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only enter the domain name. There is no need to include index.php/api/qso as the system will automatically complete the path..
        /// </summary>
        public static string CloudlogUrlHelp {
            get {
                return ResourceManager.GetString("CloudlogUrlHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clublog Settings.
        /// </summary>
        public static string ClublogSettings {
            get {
                return ResourceManager.GetString("ClublogSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this field is not empty, the software will use the entered content as the default parameters for launching rigctld, and all other configurations will be ignored..
        /// </summary>
        public static string CommandArgHelp {
            get {
                return ResourceManager.GetString("CommandArgHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cloudlog configuration; Please check them in settings!.
        /// </summary>
        public static string ConfigureCloudlogFirst {
            get {
                return ResourceManager.GetString("ConfigureCloudlogFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in flrig settings - correct them first!.
        /// </summary>
        public static string ConfigureFlRigFirst {
            get {
                return ResourceManager.GetString("ConfigureFlRigFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hamlib configuration; Please check them in settings!.
        /// </summary>
        public static string ConfigureHamlibFirst {
            get {
                return ResourceManager.GetString("ConfigureHamlibFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check OmniRig Settings!.
        /// </summary>
        public static string ConfigureOmniRigFirst {
            get {
                return ResourceManager.GetString("ConfigureOmniRigFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process conflict: {replace01} may disrupt radio data auto-reporting..
        /// </summary>
        public static string ConflictingHamlib {
            get {
                return ResourceManager.GetString("ConflictingHamlib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Frequency.
        /// </summary>
        public static string CurrentFrequency {
            get {
                return ResourceManager.GetString("CurrentFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Mode.
        /// </summary>
        public static string CurrentMode {
            get {
                return ResourceManager.GetString("CurrentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Bit.
        /// </summary>
        public static string DataBit {
            get {
                return ResourceManager.GetString("DataBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSOs today.
        /// </summary>
        public static string DayQsos {
            get {
                return ResourceManager.GetString("DayQsos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoded / Qsos: .
        /// </summary>
        public static string DecodedQsos {
            get {
                return ResourceManager.GetString("DecodedQsos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEL SEL.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Port.
        /// </summary>
        public static string DevicePort {
            get {
                return ResourceManager.GetString("DevicePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable chart feature (low-performance devices only)
        ///
        ///.
        /// </summary>
        public static string DisableCharts {
            get {
                return ResourceManager.GetString("DisableCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable PTT Control.
        /// </summary>
        public static string DisablePtt {
            get {
                return ResourceManager.GetString("DisablePtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In some Linux distributions, if rts/dtr is not disabled, it may prevent PTT from initializing correctly, manifesting as the PTT remaining in a triggered state..
        /// </summary>
        public static string DisablePttHelp {
            get {
                return ResourceManager.GetString("DisablePttHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Cloudlog Helper v{1}!
        ///
        ///This software is open-sourced under The Unlicense and provided &quot;as is&quot;, for technical exchange and learning purposes only. Users must assume all risks associated with its use.
        ///
        ///The developers assume no responsibility for any data loss, device damage, or other losses that may result from the use of this software.
        ///
        ///By continuing, you acknowledge that you have read and agree to the above terms and the full disclaimer on the project homepage (https://github.com/sydneyowl/cloudl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance (km).
        /// </summary>
        public static string DistanceKm {
            get {
                return ResourceManager.GetString("DistanceKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance weight.
        /// </summary>
        public static string DistanceWeight {
            get {
                return ResourceManager.GetString("DistanceWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double tap QSO to see more.
        /// </summary>
        public static string DoubleTapToSeeMore {
            get {
                return ResourceManager.GetString("DoubleTapToSeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program is already running!.
        /// </summary>
        public static string DuplicateInstance {
            get {
                return ResourceManager.GetString("DuplicateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable two radio backend control services simultaneously is not allowed..
        /// </summary>
        public static string DuplicateRigServiceDetected {
            get {
                return ResourceManager.GetString("DuplicateRigServiceDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string EnableAdvanced {
            get {
                return ResourceManager.GetString("EnableAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable CLH Server.
        /// </summary>
        public static string EnableClhServer {
            get {
                return ResourceManager.GetString("EnableClhServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable connection from outside.
        /// </summary>
        public static string EnableOutsideConnection {
            get {
                return ResourceManager.GetString("EnableOutsideConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable plugins.
        /// </summary>
        public static string EnablePlugin {
            get {
                return ResourceManager.GetString("EnablePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable udp server.
        /// </summary>
        public static string EnableUdpServer {
            get {
                return ResourceManager.GetString("EnableUdpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred!.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export adi.
        /// </summary>
        public static string ExportToAdif {
            get {
                return ResourceManager.GetString("ExportToAdif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External rigctld host.
        /// </summary>
        public static string ExternalRigctldHost {
            get {
                return ResourceManager.GetString("ExternalRigctldHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed!.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload this QSO..
        /// </summary>
        public static string FailedQso {
            get {
                return ResourceManager.GetString("FailedQso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch RIG info!.
        /// </summary>
        public static string FailedRigInfo {
            get {
                return ResourceManager.GetString("FailedRigInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch station info!.
        /// </summary>
        public static string FailedStationInfo {
            get {
                return ResourceManager.GetString("FailedStationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch station statistics!.
        /// </summary>
        public static string FailedStationStatistics {
            get {
                return ResourceManager.GetString("FailedStationStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract port number from the command line arguments. Please explicitly specify them using the -t parameters..
        /// </summary>
        public static string FailedToExtractInfo {
            get {
                return ResourceManager.GetString("FailedToExtractInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload rig info to {addr}. See logs for more!.
        /// </summary>
        public static string FailedUploadRigInfoTo {
            get {
                return ResourceManager.GetString("FailedUploadRigInfoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete all required fields..
        /// </summary>
        public static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter dupe samples by callsign.
        /// </summary>
        public static string FilterDuplicatesByCallsign {
            get {
                return ResourceManager.GetString("FilterDuplicatesByCallsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward raw UDP Packet to.
        /// </summary>
        public static string ForwardMessage {
            get {
                return ResourceManager.GetString("ForwardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward raw UDP Packet to.
        /// </summary>
        public static string ForwardTo {
            get {
                return ResourceManager.GetString("ForwardTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send decoded data to HTTP server.
        /// </summary>
        public static string ForwardToTcp {
            get {
                return ResourceManager.GetString("ForwardToTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting info....
        /// </summary>
        public static string GettingInfo {
            get {
                return ResourceManager.GetString("GettingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Square.
        /// </summary>
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid coordinates are empty or invalid, please check settings!.
        /// </summary>
        public static string GridError {
            get {
                return ResourceManager.GetString("GridError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HamCQ Settings.
        /// </summary>
        public static string HamCqSettings {
            get {
                return ResourceManager.GetString("HamCqSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback is valuable! Could you please share the error details on GitHub to assist in resolving this bug?.
        /// </summary>
        public static string HelpFeedback {
            get {
                return ResourceManager.GetString("HelpFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This QSO is ignored - Maybe none of third party log service is enabled?.
        /// </summary>
        public static string IgnoredQso {
            get {
                return ResourceManager.GetString("IgnoredQso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will permanently ignore the selected QSOs, and subsequent QSO Assistant scans will skip these entries. Do you want to continue?.
        /// </summary>
        public static string IgnoreQsoPermanently {
            get {
                return ResourceManager.GetString("IgnoreQsoPermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falied to init hamlib!.
        /// </summary>
        public static string InitHamlibFailed {
            get {
                return ResourceManager.GetString("InitHamlibFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like you&apos;re using {replace01} instead of Cloudlog as the backend service. Some features may not be fully supported..
        /// </summary>
        public static string InstanceIncompatible {
            get {
                return ResourceManager.GetString("InstanceIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Name.
        /// </summary>
        public static string InstanceName {
            get {
                return ResourceManager.GetString("InstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field refers to the name used when the software is registered to the clh-server. This name should be unique..
        /// </summary>
        public static string InstanceNameHint {
            get {
                return ResourceManager.GetString("InstanceNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid host address!.
        /// </summary>
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ADIF!.
        /// </summary>
        public static string InvalidAdif {
            get {
                return ResourceManager.GetString("InvalidAdif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This apikey is invalid!.
        /// </summary>
        public static string InvalidApiKey {
            get {
                return ResourceManager.GetString("InvalidApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration!.
        /// </summary>
        public static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port number..
        /// </summary>
        public static string InvalidPort {
            get {
                return ResourceManager.GetString("InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UDP Server config!.
        /// </summary>
        public static string InvalidUdpConfiguration {
            get {
                return ResourceManager.GetString("InvalidUdpConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is invalid!.
        /// </summary>
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K Value(KNN).
        /// </summary>
        public static string KValue {
            get {
                return ResourceManager.GetString("KValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input domain only;  don&apos;t end with /api/qso!.
        /// </summary>
        public static string MainDomainOnly {
            get {
                return ResourceManager.GetString("MainDomainOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max sample count.
        /// </summary>
        public static string MaxSampleCount {
            get {
                return ResourceManager.GetString("MaxSampleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling interval should be more than 1s!.
        /// </summary>
        public static string MinimumPollIntervalError {
            get {
                return ResourceManager.GetString("MinimumPollIntervalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apikey needs read/write access but only read is given here!.
        /// </summary>
        public static string MissingWriteAccess {
            get {
                return ResourceManager.GetString("MissingWriteAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSOs this month.
        /// </summary>
        public static string MonthQsos {
            get {
                return ResourceManager.GetString("MonthQsos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL must start with http:// or https://.
        /// </summary>
        public static string MustStartWithHttp {
            get {
                return ResourceManager.GetString("MustStartWithHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Grid.
        /// </summary>
        public static string MyGrid {
            get {
                return ResourceManager.GetString("MyGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Upload.
        /// </summary>
        public static string NextUploadTime {
            get {
                return ResourceManager.GetString("NextUploadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No data).
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string NotificationTitleError {
            get {
                return ResourceManager.GetString("NotificationTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string NotificationTitleInfo {
            get {
                return ResourceManager.GetString("NotificationTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string NotificationTitleSuccess {
            get {
                return ResourceManager.GetString("NotificationTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string NotificationTitleWarning {
            get {
                return ResourceManager.GetString("NotificationTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A QSO is made.
        /// </summary>
        public static string NotifyOnQsoFinished {
            get {
                return ResourceManager.GetString("NotifyOnQsoFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A QSO is uploaded.
        /// </summary>
        public static string NotifyOnQsoUploaded {
            get {
                return ResourceManager.GetString("NotifyOnQsoUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check if OmniRig has been installed correctly. Additionally, OmniRig is currently only supported on non-AOT compiled Windows platforms..
        /// </summary>
        public static string OmniRigInitFailed {
            get {
                return ResourceManager.GetString("OmniRigInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open configuration directory.
        /// </summary>
        public static string OpenConfigPath {
            get {
                return ResourceManager.GetString("OpenConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open cache folder.
        /// </summary>
        public static string OpenTempFolder {
            get {
                return ResourceManager.GetString("OpenTempFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This QSO is pending..
        /// </summary>
        public static string PendingQso {
            get {
                return ResourceManager.GetString("PendingQso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----Please select----.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any qso first!.
        /// </summary>
        public static string PleaseSelectFirst {
            get {
                return ResourceManager.GetString("PleaseSelectFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save the settings and close the settings page for the changes to the plugin to take effect.
        ///.
        /// </summary>
        public static string PluginRestartHint {
            get {
                return ResourceManager.GetString("PluginRestartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rig data polling is not enabled！.
        /// </summary>
        public static string PollingDisabled {
            get {
                return ResourceManager.GetString("PollingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll interval (sec).
        /// </summary>
        public static string PollInterval {
            get {
                return ResourceManager.GetString("PollInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polling interval must be an integer and greater than 1.
        /// </summary>
        public static string PollIntervalRequired {
            get {
                return ResourceManager.GetString("PollIntervalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow proxying requests sent by other applications. Used to prevent potential conflicts caused by simultaneous requests to rigctld..
        /// </summary>
        public static string ProxyHelp {
            get {
                return ResourceManager.GetString("ProxyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notifications after:.
        /// </summary>
        public static string PushNotifications {
            get {
                return ResourceManager.GetString("PushNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO Assistant.
        /// </summary>
        public static string QsoAssistant {
            get {
                return ResourceManager.GetString("QsoAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Sign: {0}, Country: {1} ({8}) ,  Grid: {9},  Frequency: {10} ({11}), Mode: {12},  Time: {14} to {15},  Report: Sent &apos;{16}&apos; / Received &apos;{17}&apos;.
        /// </summary>
        public static string QsoConciseTemplate {
            get {
                return ResourceManager.GetString("QsoConciseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅️ A QSO Was made!.
        /// </summary>
        public static string QsoMade {
            get {
                return ResourceManager.GetString("QsoMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO Rate:.
        /// </summary>
        public static string QsoRate {
            get {
                return ResourceManager.GetString("QsoRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO upload failed retry count.
        /// </summary>
        public static string QsoRetryCount {
            get {
                return ResourceManager.GetString("QsoRetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sync QSO: .
        /// </summary>
        public static string QsoSyncFailed {
            get {
                return ResourceManager.GetString("QsoSyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing QSO....
        /// </summary>
        public static string QsoSyncing {
            get {
                return ResourceManager.GetString("QsoSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO Sync finished successfully..
        /// </summary>
        public static string QsoSyncSucceeded {
            get {
                return ResourceManager.GetString("QsoSyncSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Call Sign: {0}
        ///• Country: {1} (CQ Zone: {2}, ITU Zone: {3})
        ///• Continent: {4}
        ///• Location: Lat {5}°, Lon {6}° (GMT{7})
        ///• DXCC: {8}
        ///• Grid: {9}
        ///• Frequency: {10} ({11})
        ///• Mode: {12} (Parent: {13})
        ///• Time: {14} to {15}
        ///• Report: Sent &apos;{16}&apos; / Received &apos;{17}&apos;
        ///• Power: {18}
        ///• Operator: {19}
        ///• My Call: {20}
        ///• My Grid: {21}
        ///• Exchange: Sent &apos;{22}&apos; / Received &apos;{23}&apos;
        ///• Propagation: {24}
        ///• Name: {25}
        ///• Comments: {26}
        ///• Client: {27}
        ///• Upload Status: {28}
        ///• Fail Reason: {29}.
        /// </summary>
        public static string QsoTemplate {
            get {
                return ResourceManager.GetString("QsoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO auto upload is disabled..
        /// </summary>
        public static string QsoUploadDisabled {
            get {
                return ResourceManager.GetString("QsoUploadDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅️ QSO Logged!.
        /// </summary>
        public static string QsoUploaded {
            get {
                return ResourceManager.GetString("QsoUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO Upload Endpoint.
        /// </summary>
        public static string QsoUploadEndpoint {
            get {
                return ResourceManager.GetString("QsoUploadEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☹️ QSO upload failed!.
        /// </summary>
        public static string QsoUploadFailed {
            get {
                return ResourceManager.GetString("QsoUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTH Nickname(optional).
        /// </summary>
        public static string QthNick {
            get {
                return ResourceManager.GetString("QthNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTH Nickname (Optional).
        /// </summary>
        public static string QthNickname {
            get {
                return ResourceManager.GetString("QthNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received QSO Info.
        /// </summary>
        public static string ReceivedQsoInfo {
            get {
                return ResourceManager.GetString("ReceivedQsoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember my choice.
        /// </summary>
        public static string RememberMyChoice {
            get {
                return ResourceManager.GetString("RememberMyChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report RFPOWER.
        /// </summary>
        public static string ReportPower {
            get {
                return ResourceManager.GetString("ReportPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report split info.
        /// </summary>
        public static string ReportSplit {
            get {
                return ResourceManager.GetString("ReportSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cannot be empty!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have -vvvvv in command-line args!.
        /// </summary>
        public static string RequireVerboseLogging {
            get {
                return ResourceManager.GetString("RequireVerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry count should be an integer and larger than 0!.
        /// </summary>
        public static string RetryCountRequired {
            get {
                return ResourceManager.GetString("RetryCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This QSO is being retried..
        /// </summary>
        public static string RetryingQso {
            get {
                return ResourceManager.GetString("RetryingQso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP AGN.
        /// </summary>
        public static string ReuploadSelected {
            get {
                return ResourceManager.GetString("ReuploadSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some radios do not support reading the transmit power, or the data read may be incorrect. Therefore  this feature is disabled by default..
        /// </summary>
        public static string RfPowerHelp {
            get {
                return ResourceManager.GetString("RfPowerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rig Backend System.
        /// </summary>
        public static string RigBackendSystem {
            get {
                return ResourceManager.GetString("RigBackendSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to communicate with rig!.
        /// </summary>
        public static string RigCommunicationFailed {
            get {
                return ResourceManager.GetString("RigCommunicationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigctld cmd args.
        /// </summary>
        public static string RigctldCommandArg {
            get {
                return ResourceManager.GetString("RigctldCommandArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigctld service not started; Please check your configuration!.
        /// </summary>
        public static string RigctldNotStarted {
            get {
                return ResourceManager.GetString("RigctldNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rig Data.
        /// </summary>
        public static string RigData {
            get {
                return ResourceManager.GetString("RigData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click QSO to see more.
        /// </summary>
        public static string RightClickToSeeMore {
            get {
                return ResourceManager.GetString("RightClickToSeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIG Info upload endpoint.
        /// </summary>
        public static string RigInfoUploadEndpoint {
            get {
                return ResourceManager.GetString("RigInfoUploadEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rig Model.
        /// </summary>
        public static string RigModel {
            get {
                return ResourceManager.GetString("RigModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rig communication time out, please check connection!.
        /// </summary>
        public static string RigTimeout {
            get {
                return ResourceManager.GetString("RigTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Configuration Wizard.
        /// </summary>
        public static string RunWizard {
            get {
                return ResourceManager.GetString("RunWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample count = .
        /// </summary>
        public static string SampleCount {
            get {
                return ResourceManager.GetString("SampleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply&amp;Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Log.
        /// </summary>
        public static string SaveLog {
            get {
                return ResourceManager.GetString("SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save log to....
        /// </summary>
        public static string SaveLogTo {
            get {
                return ResourceManager.GetString("SaveLogTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show coast line.
        /// </summary>
        public static string ShowCoastline {
            get {
                return ResourceManager.GetString("ShowCoastline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show density color.
        /// </summary>
        public static string ShowDensityColor {
            get {
                return ResourceManager.GetString("ShowDensityColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show failed only.
        /// </summary>
        public static string ShowFailedOnly {
            get {
                return ResourceManager.GetString("ShowFailedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close App.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal count.
        /// </summary>
        public static string SignalCount {
            get {
                return ResourceManager.GetString("SignalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal distribution.
        /// </summary>
        public static string SignalPolarChart {
            get {
                return ResourceManager.GetString("SignalPolarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string must not have leading or trailing spaces..
        /// </summary>
        public static string SpaceNotAllowed {
            get {
                return ResourceManager.GetString("SpaceNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolon-separated addresses must specify http(s).
        /// </summary>
        public static string SplitBySemicolon {
            get {
                return ResourceManager.GetString("SplitBySemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some radios do not support reading the split data, or the data read may be incorrect. Therefore, this feature is disabled by default..
        /// </summary>
        public static string SplitHelp {
            get {
                return ResourceManager.GetString("SplitHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Bearing Distribution - {0} Band {1}.
        /// </summary>
        public static string StationBearingDistribution {
            get {
                return ResourceManager.GetString("StationBearingDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Distance Distribution - {0} Band {1}.
        /// </summary>
        public static string StationDistanceDistribution {
            get {
                return ResourceManager.GetString("StationDistanceDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudlog Station ID.
        /// </summary>
        public static string StationId {
            get {
                return ResourceManager.GetString("StationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station name.
        /// </summary>
        public static string StationName {
            get {
                return ResourceManager.GetString("StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Station Statistic.
        /// </summary>
        public static string StationStatisticGraph {
            get {
                return ResourceManager.GetString("StationStatisticGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Bit.
        /// </summary>
        public static string StopBit {
            get {
                return ResourceManager.GetString("StopBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This QSO Uploaded successfully..
        /// </summary>
        public static string SuccessfulQso {
            get {
                return ResourceManager.GetString("SuccessfulQso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also upload info to.
        /// </summary>
        public static string SyncRigInfoTo {
            get {
                return ResourceManager.GetString("SyncRigInfoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target RIG.
        /// </summary>
        public static string TargetRig {
            get {
                return ResourceManager.GetString("TargetRig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * After each configuration change, you must click &quot;Test&quot; to test and apply the changes.
        ///.
        /// </summary>
        public static string TestAndApply {
            get {
                return ResourceManager.GetString("TestAndApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test .
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing....
        /// </summary>
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Color.
        /// </summary>
        public static string ThemeColor {
            get {
                return ResourceManager.GetString("ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party Log Systems.
        /// </summary>
        public static string ThirdPartyLogSystem {
            get {
                return ResourceManager.GetString("ThirdPartyLogSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 10 DXCCs - {0} Band {1}.
        /// </summary>
        public static string Top10DecodedDxccs {
            get {
                return ResourceManager.GetString("Top10DecodedDxccs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoded:.
        /// </summary>
        public static string TotalDecoded {
            get {
                return ResourceManager.GetString("TotalDecoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded:.
        /// </summary>
        public static string TotalReceived {
            get {
                return ResourceManager.GetString("TotalReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded:.
        /// </summary>
        public static string TotalUploaded {
            get {
                return ResourceManager.GetString("TotalUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        public static string ToTray {
            get {
                return ResourceManager.GetString("ToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TQSL Password.
        /// </summary>
        public static string TqslPassword {
            get {
                return ResourceManager.GetString("TqslPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TQSL Path.
        /// </summary>
        public static string TqslPath {
            get {
                return ResourceManager.GetString("TqslPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tx....
        /// </summary>
        public static string Transmitting {
            get {
                return ResourceManager.GetString("Transmitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency.
        /// </summary>
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port number should be consistent with the settings in JTDX/wsjt-x. The default is 2237..
        /// </summary>
        public static string UdpPortHelp {
            get {
                return ResourceManager.GetString("UdpPortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP Server.
        /// </summary>
        public static string UdpServer {
            get {
                return ResourceManager.GetString("UdpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP Connection timeout!.
        /// </summary>
        public static string UdpTimeout {
            get {
                return ResourceManager.GetString("UdpTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check apikey availability; Please check whether the url is correct or not!.
        /// </summary>
        public static string UnableToCheckApi {
            get {
                return ResourceManager.GetString("UnableToCheckApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported rig freq:.
        /// </summary>
        public static string UnsupportedRigFrequency {
            get {
                return ResourceManager.GetString("UnsupportedRigFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported rig mode:.
        /// </summary>
        public static string UnsupportedRigMode {
            get {
                return ResourceManager.GetString("UnsupportedRigMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update callsign and country data.
        /// </summary>
        public static string UpdateBigCty {
            get {
                return ResourceManager.GetString("UpdateBigCty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call sign and country data update failed: {0}！.
        /// </summary>
        public static string UpdateBigCtyFailed {
            get {
                return ResourceManager.GetString("UpdateBigCtyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call sign and country data updated successfully!
        ///{0} call sign rules and {1} country data entries written.
        /// </summary>
        public static string UpdateBigCtySuccess {
            get {
                return ResourceManager.GetString("UpdateBigCtySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This QSO is being uploaded.
        /// </summary>
        public static string UploadingQso {
            get {
                return ResourceManager.GetString("UploadingQso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload RIG info.
        /// </summary>
        public static string UploadRigInfo {
            get {
                return ResourceManager.GetString("UploadRigInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Status.
        /// </summary>
        public static string UploadStatus {
            get {
                return ResourceManager.GetString("UploadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string UploadStatusFailed {
            get {
                return ResourceManager.GetString("UploadStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored.
        /// </summary>
        public static string UploadStatusIgnored {
            get {
                return ResourceManager.GetString("UploadStatusIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending....
        /// </summary>
        public static string UploadStatusPending {
            get {
                return ResourceManager.GetString("UploadStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying....
        /// </summary>
        public static string UploadStatusRetrying {
            get {
                return ResourceManager.GetString("UploadStatusRetrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string UploadStatusSuccess {
            get {
                return ResourceManager.GetString("UploadStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string UploadStatusUploading {
            get {
                return ResourceManager.GetString("UploadStatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. http://cloudlog.com.
        /// </summary>
        public static string UrlExample {
            get {
                return ResourceManager.GetString("UrlExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Format error!.
        /// </summary>
        public static string UrlFormatError {
            get {
                return ResourceManager.GetString("UrlFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use external rigctld.
        /// </summary>
        public static string UseExternalRigctld {
            get {
                return ResourceManager.GetString("UseExternalRigctld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for connection....
        /// </summary>
        public static string WaitingConnection {
            get {
                return ResourceManager.GetString("WaitingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average number of QSOs per minute achieved within 5 minutes..
        /// </summary>
        public static string WithinFiveMinutes {
            get {
                return ResourceManager.GetString("WithinFiveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can fill in your Maidenhead grid now, or leave it empty and configure later..
        /// </summary>
        public static string WizardBasicHint {
            get {
                return ResourceManager.GetString("WizardBasicHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Settings.
        /// </summary>
        public static string WizardBasicTitle {
            get {
                return ResourceManager.GetString("WizardBasicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your device has low performance, disable this option..
        /// </summary>
        public static string WizardChartFeatureHint {
            get {
                return ResourceManager.GetString("WizardChartFeatureHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable chart features.
        /// </summary>
        public static string WizardChartFeatureLabel {
            get {
                return ResourceManager.GetString("WizardChartFeatureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string WizardCloudlogApiKey {
            get {
                return ResourceManager.GetString("WizardCloudlogApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected:.
        /// </summary>
        public static string WizardCloudlogDetectedInstance {
            get {
                return ResourceManager.GetString("WizardCloudlogDetectedInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Cloudlog / Wavelog now.
        /// </summary>
        public static string WizardCloudlogEnable {
            get {
                return ResourceManager.GetString("WizardCloudlogEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose whether you want to connect Cloudlog/Wavelog now..
        /// </summary>
        public static string WizardCloudlogHint {
            get {
                return ResourceManager.GetString("WizardCloudlogHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string WizardCloudlogStation {
            get {
                return ResourceManager.GetString("WizardCloudlogStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a station profile..
        /// </summary>
        public static string WizardCloudlogStationRequired {
            get {
                return ResourceManager.GetString("WizardCloudlogStationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please test the Cloudlog/Wavelog connection before continuing..
        /// </summary>
        public static string WizardCloudlogTestRequired {
            get {
                return ResourceManager.GetString("WizardCloudlogTestRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudlog / Wavelog.
        /// </summary>
        public static string WizardCloudlogTitle {
            get {
                return ResourceManager.GetString("WizardCloudlogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string WizardCloudlogUrl {
            get {
                return ResourceManager.GetString("WizardCloudlogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string WizardFinish {
            get {
                return ResourceManager.GetString("WizardFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there!.
        /// </summary>
        public static string WizardHiThere {
            get {
                return ResourceManager.GetString("WizardHiThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string WizardNext {
            get {
                return ResourceManager.GetString("WizardNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OmniRig is not available on this device..
        /// </summary>
        public static string WizardOmniRigUnavailable {
            get {
                return ResourceManager.GetString("WizardOmniRigUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string WizardPrevious {
            get {
                return ResourceManager.GetString("WizardPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current rig backend.
        /// </summary>
        public static string WizardRigBackendLabel {
            get {
                return ResourceManager.GetString("WizardRigBackendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLRig.
        /// </summary>
        public static string WizardRigFlRig {
            get {
                return ResourceManager.GetString("WizardRigFlRig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamlib.
        /// </summary>
        public static string WizardRigHamlib {
            get {
                return ResourceManager.GetString("WizardRigHamlib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your current rig backend and configure it. You can also skip this step..
        /// </summary>
        public static string WizardRigHint {
            get {
                return ResourceManager.GetString("WizardRigHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip for now.
        /// </summary>
        public static string WizardRigNone {
            get {
                return ResourceManager.GetString("WizardRigNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OmniRig.
        /// </summary>
        public static string WizardRigOmniRig {
            get {
                return ResourceManager.GetString("WizardRigOmniRig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rig Backend.
        /// </summary>
        public static string WizardRigTitle {
            get {
                return ResourceManager.GetString("WizardRigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip setup.
        /// </summary>
        public static string WizardSkip {
            get {
                return ResourceManager.GetString("WizardSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure third-party log services now, or leave them disabled and set them later..
        /// </summary>
        public static string WizardThirdPartyHint {
            get {
                return ResourceManager.GetString("WizardThirdPartyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-Party Logs.
        /// </summary>
        public static string WizardThirdPartyTitle {
            get {
                return ResourceManager.GetString("WizardThirdPartyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First-Run Setup.
        /// </summary>
        public static string WizardTitle {
            get {
                return ResourceManager.GetString("WizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Cloudlog Helper! This wizard will help you quickly complete the initial setup of the software. You can also run it again later by clicking About -&gt; Run Wizard..
        /// </summary>
        public static string WizardWelcomeMessage {
            get {
                return ResourceManager.GetString("WizardWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WizardWelcomeTitle {
            get {
                return ResourceManager.GetString("WizardWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Heatmap - {0} Band {1}.
        /// </summary>
        public static string WorldHeatmap {
            get {
                return ResourceManager.GetString("WorldHeatmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSOs this year.
        /// </summary>
        public static string YearQsos {
            get {
                return ResourceManager.GetString("YearQsos", resourceCulture);
            }
        }
    }
}
