//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudlogHelper.Resources.Language {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language_ja_jp {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_ja_jp() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CloudlogHelper.Resources.Language.Language_ja_jp", typeof(Language_ja_jp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        public static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        public static string AllowExternalControl {
            get {
                return ResourceManager.GetString("AllowExternalControl", resourceCulture);
            }
        }
        
        public static string AllowProxy {
            get {
                return ResourceManager.GetString("AllowProxy", resourceCulture);
            }
        }
        
        public static string AngleWeight {
            get {
                return ResourceManager.GetString("AngleWeight", resourceCulture);
            }
        }
        
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        public static string AutoPollStatus {
            get {
                return ResourceManager.GetString("AutoPollStatus", resourceCulture);
            }
        }
        
        public static string AutoQsoUpload {
            get {
                return ResourceManager.GetString("AutoQsoUpload", resourceCulture);
            }
        }
        
        public static string AutoSelect {
            get {
                return ResourceManager.GetString("AutoSelect", resourceCulture);
            }
        }
        
        public static string AutoUpdateRigInfo {
            get {
                return ResourceManager.GetString("AutoUpdateRigInfo", resourceCulture);
            }
        }
        
        public static string AutoUploadQsoTo {
            get {
                return ResourceManager.GetString("AutoUploadQsoTo", resourceCulture);
            }
        }
        
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        public static string BasicSettings {
            get {
                return ResourceManager.GetString("BasicSettings", resourceCulture);
            }
        }
        
        public static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        public static string BearingDegrees {
            get {
                return ResourceManager.GetString("BearingDegrees", resourceCulture);
            }
        }
        
        public static string BootFailed {
            get {
                return ResourceManager.GetString("BootFailed", resourceCulture);
            }
        }
        
        public static string Calculating {
            get {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        
        public static string Callsign {
            get {
                return ResourceManager.GetString("Callsign", resourceCulture);
            }
        }
        
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        public static string ChartsDisabled {
            get {
                return ResourceManager.GetString("ChartsDisabled", resourceCulture);
            }
        }
        
        public static string CheckRigConnection {
            get {
                return ResourceManager.GetString("CheckRigConnection", resourceCulture);
            }
        }
        
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        public static string ClhHintInfo {
            get {
                return ResourceManager.GetString("ClhHintInfo", resourceCulture);
            }
        }
        
        public static string ClhServerAddress {
            get {
                return ResourceManager.GetString("ClhServerAddress", resourceCulture);
            }
        }
        
        public static string ClhServerKey {
            get {
                return ResourceManager.GetString("ClhServerKey", resourceCulture);
            }
        }
        
        public static string ClhServerPort {
            get {
                return ResourceManager.GetString("ClhServerPort", resourceCulture);
            }
        }
        
        public static string ClhServer {
            get {
                return ResourceManager.GetString("ClhServer", resourceCulture);
            }
        }
        
        public static string ClhUseTls {
            get {
                return ResourceManager.GetString("ClhUseTls", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string CloseOrMinimize {
            get {
                return ResourceManager.GetString("CloseOrMinimize", resourceCulture);
            }
        }
        
        public static string CloudlogApiHelp {
            get {
                return ResourceManager.GetString("CloudlogApiHelp", resourceCulture);
            }
        }
        
        public static string CloudlogStationId {
            get {
                return ResourceManager.GetString("CloudlogStationId", resourceCulture);
            }
        }
        
        public static string CloudlogUrlHelp {
            get {
                return ResourceManager.GetString("CloudlogUrlHelp", resourceCulture);
            }
        }
        
        public static string ClublogSettings {
            get {
                return ResourceManager.GetString("ClublogSettings", resourceCulture);
            }
        }
        
        public static string CommandArgHelp {
            get {
                return ResourceManager.GetString("CommandArgHelp", resourceCulture);
            }
        }
        
        public static string ConfigureCloudlogFirst {
            get {
                return ResourceManager.GetString("ConfigureCloudlogFirst", resourceCulture);
            }
        }
        
        public static string ConfigureFlRigFirst {
            get {
                return ResourceManager.GetString("ConfigureFlRigFirst", resourceCulture);
            }
        }
        
        public static string ConfigureHamlibFirst {
            get {
                return ResourceManager.GetString("ConfigureHamlibFirst", resourceCulture);
            }
        }
        
        public static string ConflictingHamlib {
            get {
                return ResourceManager.GetString("ConflictingHamlib", resourceCulture);
            }
        }
        
        public static string ConfigureOmniRigFirst {
            get {
                return ResourceManager.GetString("ConfigureOmniRigFirst", resourceCulture);
            }
        }
        
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        public static string CurrentFrequency {
            get {
                return ResourceManager.GetString("CurrentFrequency", resourceCulture);
            }
        }
        
        public static string CurrentMode {
            get {
                return ResourceManager.GetString("CurrentMode", resourceCulture);
            }
        }
        
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        public static string DataBit {
            get {
                return ResourceManager.GetString("DataBit", resourceCulture);
            }
        }
        
        public static string DayQsos {
            get {
                return ResourceManager.GetString("DayQsos", resourceCulture);
            }
        }
        
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        public static string DevicePort {
            get {
                return ResourceManager.GetString("DevicePort", resourceCulture);
            }
        }
        
        public static string DisableCharts {
            get {
                return ResourceManager.GetString("DisableCharts", resourceCulture);
            }
        }
        
        public static string DisablePtt {
            get {
                return ResourceManager.GetString("DisablePtt", resourceCulture);
            }
        }
        
        public static string DisablePttHelp {
            get {
                return ResourceManager.GetString("DisablePttHelp", resourceCulture);
            }
        }
        
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        public static string DistanceKm {
            get {
                return ResourceManager.GetString("DistanceKm", resourceCulture);
            }
        }
        
        public static string DistanceWeight {
            get {
                return ResourceManager.GetString("DistanceWeight", resourceCulture);
            }
        }
        
        public static string DoubleTapToSeeMore {
            get {
                return ResourceManager.GetString("DoubleTapToSeeMore", resourceCulture);
            }
        }
        
        public static string DuplicateInstance {
            get {
                return ResourceManager.GetString("DuplicateInstance", resourceCulture);
            }
        }
        
        public static string DuplicateRigServiceDetected {
            get {
                return ResourceManager.GetString("DuplicateRigServiceDetected", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string EnableAdvanced {
            get {
                return ResourceManager.GetString("EnableAdvanced", resourceCulture);
            }
        }
        
        public static string EnableClhServer {
            get {
                return ResourceManager.GetString("EnableClhServer", resourceCulture);
            }
        }
        
        public static string EnableOutsideConnection {
            get {
                return ResourceManager.GetString("EnableOutsideConnection", resourceCulture);
            }
        }
        
        public static string EnableUdpServer {
            get {
                return ResourceManager.GetString("EnableUdpServer", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        public static string ExportToAdif {
            get {
                return ResourceManager.GetString("ExportToAdif", resourceCulture);
            }
        }
        
        public static string ExternalRigctldHost {
            get {
                return ResourceManager.GetString("ExternalRigctldHost", resourceCulture);
            }
        }
        
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        public static string FailedQso {
            get {
                return ResourceManager.GetString("FailedQso", resourceCulture);
            }
        }
        
        public static string FailedRigInfo {
            get {
                return ResourceManager.GetString("FailedRigInfo", resourceCulture);
            }
        }
        
        public static string FailedStationInfo {
            get {
                return ResourceManager.GetString("FailedStationInfo", resourceCulture);
            }
        }
        
        public static string FailedStationStatistics {
            get {
                return ResourceManager.GetString("FailedStationStatistics", resourceCulture);
            }
        }
        
        public static string QsoSyncFailed {
            get {
                return ResourceManager.GetString("QsoSyncFailed", resourceCulture);
            }
        }
        
        public static string FailedToExtractInfo {
            get {
                return ResourceManager.GetString("FailedToExtractInfo", resourceCulture);
            }
        }
        
        public static string RigCommunicationFailed {
            get {
                return ResourceManager.GetString("RigCommunicationFailed", resourceCulture);
            }
        }
        
        public static string FailedUploadRigInfoTo {
            get {
                return ResourceManager.GetString("FailedUploadRigInfoTo", resourceCulture);
            }
        }
        
        public static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        public static string FilterDuplicatesByCallsign {
            get {
                return ResourceManager.GetString("FilterDuplicatesByCallsign", resourceCulture);
            }
        }
        
        public static string ForwardToTcp {
            get {
                return ResourceManager.GetString("ForwardToTcp", resourceCulture);
            }
        }
        
        public static string ForwardMessage {
            get {
                return ResourceManager.GetString("ForwardMessage", resourceCulture);
            }
        }
        
        public static string ForwardTo {
            get {
                return ResourceManager.GetString("ForwardTo", resourceCulture);
            }
        }
        
        public static string GettingInfo {
            get {
                return ResourceManager.GetString("GettingInfo", resourceCulture);
            }
        }
        
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        public static string GridError {
            get {
                return ResourceManager.GetString("GridError", resourceCulture);
            }
        }
        
        public static string HamCqSettings {
            get {
                return ResourceManager.GetString("HamCqSettings", resourceCulture);
            }
        }
        
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        public static string HelpFeedback {
            get {
                return ResourceManager.GetString("HelpFeedback", resourceCulture);
            }
        }
        
        public static string IgnoredQso {
            get {
                return ResourceManager.GetString("IgnoredQso", resourceCulture);
            }
        }
        
        public static string IgnoreQsoPermanently {
            get {
                return ResourceManager.GetString("IgnoreQsoPermanently", resourceCulture);
            }
        }
        
        public static string InitHamlibFailed {
            get {
                return ResourceManager.GetString("InitHamlibFailed", resourceCulture);
            }
        }
        
        public static string InstanceName {
            get {
                return ResourceManager.GetString("InstanceName", resourceCulture);
            }
        }
        
        public static string InstanceNameHint {
            get {
                return ResourceManager.GetString("InstanceNameHint", resourceCulture);
            }
        }
        
        public static string InstanceIncompatible {
            get {
                return ResourceManager.GetString("InstanceIncompatible", resourceCulture);
            }
        }
        
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        public static string InvalidAdif {
            get {
                return ResourceManager.GetString("InvalidAdif", resourceCulture);
            }
        }
        
        public static string InvalidApiKey {
            get {
                return ResourceManager.GetString("InvalidApiKey", resourceCulture);
            }
        }
        
        public static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        public static string InvalidPort {
            get {
                return ResourceManager.GetString("InvalidPort", resourceCulture);
            }
        }
        
        public static string InvalidUdpConfiguration {
            get {
                return ResourceManager.GetString("InvalidUdpConfiguration", resourceCulture);
            }
        }
        
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        public static string KValue {
            get {
                return ResourceManager.GetString("KValue", resourceCulture);
            }
        }
        
        public static string MissingWriteAccess {
            get {
                return ResourceManager.GetString("MissingWriteAccess", resourceCulture);
            }
        }
        
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        public static string QsoMade {
            get {
                return ResourceManager.GetString("QsoMade", resourceCulture);
            }
        }
        
        public static string MaxSampleCount {
            get {
                return ResourceManager.GetString("MaxSampleCount", resourceCulture);
            }
        }
        
        public static string MonthQsos {
            get {
                return ResourceManager.GetString("MonthQsos", resourceCulture);
            }
        }
        
        public static string RequireVerboseLogging {
            get {
                return ResourceManager.GetString("RequireVerboseLogging", resourceCulture);
            }
        }
        
        public static string MyGrid {
            get {
                return ResourceManager.GetString("MyGrid", resourceCulture);
            }
        }
        
        public static string NextUploadTime {
            get {
                return ResourceManager.GetString("NextUploadTime", resourceCulture);
            }
        }
        
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        public static string OmniRigInitFailed {
            get {
                return ResourceManager.GetString("OmniRigInitFailed", resourceCulture);
            }
        }
        
        public static string MainDomainOnly {
            get {
                return ResourceManager.GetString("MainDomainOnly", resourceCulture);
            }
        }
        
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string OpenConfigPath {
            get {
                return ResourceManager.GetString("OpenConfigPath", resourceCulture);
            }
        }
        
        public static string OpenTempFolder {
            get {
                return ResourceManager.GetString("OpenTempFolder", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        public static string PendingQso {
            get {
                return ResourceManager.GetString("PendingQso", resourceCulture);
            }
        }
        
        public static string PollingDisabled {
            get {
                return ResourceManager.GetString("PollingDisabled", resourceCulture);
            }
        }
        
        public static string PollInterval {
            get {
                return ResourceManager.GetString("PollInterval", resourceCulture);
            }
        }
        
        public static string PollIntervalRequired {
            get {
                return ResourceManager.GetString("PollIntervalRequired", resourceCulture);
            }
        }
        
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        public static string ProxyHelp {
            get {
                return ResourceManager.GetString("ProxyHelp", resourceCulture);
            }
        }
        
        public static string PleaseSelectFirst {
            get {
                return ResourceManager.GetString("PleaseSelectFirst", resourceCulture);
            }
        }
        
        public static string PushNotifications {
            get {
                return ResourceManager.GetString("PushNotifications", resourceCulture);
            }
        }
        
        public static string QsoAssistant {
            get {
                return ResourceManager.GetString("QsoAssistant", resourceCulture);
            }
        }
        
        public static string QsoConciseTemplate {
            get {
                return ResourceManager.GetString("QsoConciseTemplate", resourceCulture);
            }
        }
        
        public static string NotifyOnQsoFinished {
            get {
                return ResourceManager.GetString("NotifyOnQsoFinished", resourceCulture);
            }
        }
        
        public static string QsoRate {
            get {
                return ResourceManager.GetString("QsoRate", resourceCulture);
            }
        }
        
        public static string QsoRetryCount {
            get {
                return ResourceManager.GetString("QsoRetryCount", resourceCulture);
            }
        }
        
        public static string QsoSyncing {
            get {
                return ResourceManager.GetString("QsoSyncing", resourceCulture);
            }
        }
        
        public static string QsoSyncSucceeded {
            get {
                return ResourceManager.GetString("QsoSyncSucceeded", resourceCulture);
            }
        }
        
        public static string QsoTemplate {
            get {
                return ResourceManager.GetString("QsoTemplate", resourceCulture);
            }
        }
        
        public static string QsoUploadDisabled {
            get {
                return ResourceManager.GetString("QsoUploadDisabled", resourceCulture);
            }
        }
        
        public static string NotifyOnQsoUploaded {
            get {
                return ResourceManager.GetString("NotifyOnQsoUploaded", resourceCulture);
            }
        }
        
        public static string QthNick {
            get {
                return ResourceManager.GetString("QthNick", resourceCulture);
            }
        }
        
        public static string QthNickname {
            get {
                return ResourceManager.GetString("QthNickname", resourceCulture);
            }
        }
        
        public static string MinimumPollIntervalError {
            get {
                return ResourceManager.GetString("MinimumPollIntervalError", resourceCulture);
            }
        }
        
        public static string ReceivedQsoInfo {
            get {
                return ResourceManager.GetString("ReceivedQsoInfo", resourceCulture);
            }
        }
        
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        public static string RememberMyChoice {
            get {
                return ResourceManager.GetString("RememberMyChoice", resourceCulture);
            }
        }
        
        public static string ReportPower {
            get {
                return ResourceManager.GetString("ReportPower", resourceCulture);
            }
        }
        
        public static string ReportSplit {
            get {
                return ResourceManager.GetString("ReportSplit", resourceCulture);
            }
        }
        
        public static string RetryCountRequired {
            get {
                return ResourceManager.GetString("RetryCountRequired", resourceCulture);
            }
        }
        
        public static string RetryingQso {
            get {
                return ResourceManager.GetString("RetryingQso", resourceCulture);
            }
        }
        
        public static string ReuploadSelected {
            get {
                return ResourceManager.GetString("ReuploadSelected", resourceCulture);
            }
        }
        
        public static string RfPowerHelp {
            get {
                return ResourceManager.GetString("RfPowerHelp", resourceCulture);
            }
        }
        
        public static string RigBackendSystem {
            get {
                return ResourceManager.GetString("RigBackendSystem", resourceCulture);
            }
        }
        
        public static string RigctldCommandArg {
            get {
                return ResourceManager.GetString("RigctldCommandArg", resourceCulture);
            }
        }
        
        public static string RigctldNotStarted {
            get {
                return ResourceManager.GetString("RigctldNotStarted", resourceCulture);
            }
        }
        
        public static string RigData {
            get {
                return ResourceManager.GetString("RigData", resourceCulture);
            }
        }
        
        public static string RigModel {
            get {
                return ResourceManager.GetString("RigModel", resourceCulture);
            }
        }
        
        public static string RigTimeout {
            get {
                return ResourceManager.GetString("RigTimeout", resourceCulture);
            }
        }
        
        public static string SampleCount {
            get {
                return ResourceManager.GetString("SampleCount", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string SaveLog {
            get {
                return ResourceManager.GetString("SaveLog", resourceCulture);
            }
        }
        
        public static string SaveLogTo {
            get {
                return ResourceManager.GetString("SaveLogTo", resourceCulture);
            }
        }
        
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string ShowDensityColor {
            get {
                return ResourceManager.GetString("ShowDensityColor", resourceCulture);
            }
        }
        
        public static string ShowFailedOnly {
            get {
                return ResourceManager.GetString("ShowFailedOnly", resourceCulture);
            }
        }
        
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        public static string SignalCount {
            get {
                return ResourceManager.GetString("SignalCount", resourceCulture);
            }
        }
        
        public static string SignalPolarChart {
            get {
                return ResourceManager.GetString("SignalPolarChart", resourceCulture);
            }
        }
        
        public static string SpaceNotAllowed {
            get {
                return ResourceManager.GetString("SpaceNotAllowed", resourceCulture);
            }
        }
        
        public static string SplitBySemicolon {
            get {
                return ResourceManager.GetString("SplitBySemicolon", resourceCulture);
            }
        }
        
        public static string SplitHelp {
            get {
                return ResourceManager.GetString("SplitHelp", resourceCulture);
            }
        }
        
        public static string MustStartWithHttp {
            get {
                return ResourceManager.GetString("MustStartWithHttp", resourceCulture);
            }
        }
        
        public static string StationBearingDistribution {
            get {
                return ResourceManager.GetString("StationBearingDistribution", resourceCulture);
            }
        }
        
        public static string StationDistanceDistribution {
            get {
                return ResourceManager.GetString("StationDistanceDistribution", resourceCulture);
            }
        }
        
        public static string StationId {
            get {
                return ResourceManager.GetString("StationId", resourceCulture);
            }
        }
        
        public static string StationName {
            get {
                return ResourceManager.GetString("StationName", resourceCulture);
            }
        }
        
        public static string StationStatisticGraph {
            get {
                return ResourceManager.GetString("StationStatisticGraph", resourceCulture);
            }
        }
        
        public static string StopBit {
            get {
                return ResourceManager.GetString("StopBit", resourceCulture);
            }
        }
        
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        public static string SuccessfulQso {
            get {
                return ResourceManager.GetString("SuccessfulQso", resourceCulture);
            }
        }
        
        public static string SyncRigInfoTo {
            get {
                return ResourceManager.GetString("SyncRigInfoTo", resourceCulture);
            }
        }
        
        public static string TargetRig {
            get {
                return ResourceManager.GetString("TargetRig", resourceCulture);
            }
        }
        
        public static string TestAndApply {
            get {
                return ResourceManager.GetString("TestAndApply", resourceCulture);
            }
        }
        
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        public static string ThemeColor {
            get {
                return ResourceManager.GetString("ThemeColor", resourceCulture);
            }
        }
        
        public static string ThirdPartyLogSystem {
            get {
                return ResourceManager.GetString("ThirdPartyLogSystem", resourceCulture);
            }
        }
        
        public static string NotificationTitleError {
            get {
                return ResourceManager.GetString("NotificationTitleError", resourceCulture);
            }
        }
        
        public static string NotificationTitleInfo {
            get {
                return ResourceManager.GetString("NotificationTitleInfo", resourceCulture);
            }
        }
        
        public static string NotificationTitleSuccess {
            get {
                return ResourceManager.GetString("NotificationTitleSuccess", resourceCulture);
            }
        }
        
        public static string NotificationTitleWarning {
            get {
                return ResourceManager.GetString("NotificationTitleWarning", resourceCulture);
            }
        }
        
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        public static string Top10DecodedDxccs {
            get {
                return ResourceManager.GetString("Top10DecodedDxccs", resourceCulture);
            }
        }
        
        public static string TotalDecoded {
            get {
                return ResourceManager.GetString("TotalDecoded", resourceCulture);
            }
        }
        
        public static string DecodedQsos {
            get {
                return ResourceManager.GetString("DecodedQsos", resourceCulture);
            }
        }
        
        public static string TotalReceived {
            get {
                return ResourceManager.GetString("TotalReceived", resourceCulture);
            }
        }
        
        public static string TotalUploaded {
            get {
                return ResourceManager.GetString("TotalUploaded", resourceCulture);
            }
        }
        
        public static string ToTray {
            get {
                return ResourceManager.GetString("ToTray", resourceCulture);
            }
        }
        
        public static string TqslPassword {
            get {
                return ResourceManager.GetString("TqslPassword", resourceCulture);
            }
        }
        
        public static string TqslPath {
            get {
                return ResourceManager.GetString("TqslPath", resourceCulture);
            }
        }
        
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        public static string Transmitting {
            get {
                return ResourceManager.GetString("Transmitting", resourceCulture);
            }
        }
        
        public static string UploadStatusFailed {
            get {
                return ResourceManager.GetString("UploadStatusFailed", resourceCulture);
            }
        }
        
        public static string UploadStatusIgnored {
            get {
                return ResourceManager.GetString("UploadStatusIgnored", resourceCulture);
            }
        }
        
        public static string UploadStatusPending {
            get {
                return ResourceManager.GetString("UploadStatusPending", resourceCulture);
            }
        }
        
        public static string UploadStatusRetrying {
            get {
                return ResourceManager.GetString("UploadStatusRetrying", resourceCulture);
            }
        }
        
        public static string UploadStatusSuccess {
            get {
                return ResourceManager.GetString("UploadStatusSuccess", resourceCulture);
            }
        }
        
        public static string UploadStatusUploading {
            get {
                return ResourceManager.GetString("UploadStatusUploading", resourceCulture);
            }
        }
        
        public static string UdpPortHelp {
            get {
                return ResourceManager.GetString("UdpPortHelp", resourceCulture);
            }
        }
        
        public static string UdpServer {
            get {
                return ResourceManager.GetString("UdpServer", resourceCulture);
            }
        }
        
        public static string UdpTimeout {
            get {
                return ResourceManager.GetString("UdpTimeout", resourceCulture);
            }
        }
        
        public static string UnableToCheckApi {
            get {
                return ResourceManager.GetString("UnableToCheckApi", resourceCulture);
            }
        }
        
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        public static string UnsupportedRigFrequency {
            get {
                return ResourceManager.GetString("UnsupportedRigFrequency", resourceCulture);
            }
        }
        
        public static string UnsupportedRigMode {
            get {
                return ResourceManager.GetString("UnsupportedRigMode", resourceCulture);
            }
        }
        
        public static string AutoUploadQsoToCloudlog {
            get {
                return ResourceManager.GetString("AutoUploadQsoToCloudlog", resourceCulture);
            }
        }
        
        public static string AutoUploadQsoToClublog {
            get {
                return ResourceManager.GetString("AutoUploadQsoToClublog", resourceCulture);
            }
        }
        
        public static string AutoUploadQsoToHamCq {
            get {
                return ResourceManager.GetString("AutoUploadQsoToHamCq", resourceCulture);
            }
        }
        
        public static string QsoUploaded {
            get {
                return ResourceManager.GetString("QsoUploaded", resourceCulture);
            }
        }
        
        public static string QsoUploadFailed {
            get {
                return ResourceManager.GetString("QsoUploadFailed", resourceCulture);
            }
        }
        
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        public static string UploadingQso {
            get {
                return ResourceManager.GetString("UploadingQso", resourceCulture);
            }
        }
        
        public static string UploadRigInfo {
            get {
                return ResourceManager.GetString("UploadRigInfo", resourceCulture);
            }
        }
        
        public static string UploadStatus {
            get {
                return ResourceManager.GetString("UploadStatus", resourceCulture);
            }
        }
        
        public static string UrlExample {
            get {
                return ResourceManager.GetString("UrlExample", resourceCulture);
            }
        }
        
        public static string UrlFormatError {
            get {
                return ResourceManager.GetString("UrlFormatError", resourceCulture);
            }
        }
        
        public static string UseExternalRigctld {
            get {
                return ResourceManager.GetString("UseExternalRigctld", resourceCulture);
            }
        }
        
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        public static string WaitingConnection {
            get {
                return ResourceManager.GetString("WaitingConnection", resourceCulture);
            }
        }
        
        public static string WithinFiveMinutes {
            get {
                return ResourceManager.GetString("WithinFiveMinutes", resourceCulture);
            }
        }
        
        public static string WorldHeatmap {
            get {
                return ResourceManager.GetString("WorldHeatmap", resourceCulture);
            }
        }
        
        public static string YearQsos {
            get {
                return ResourceManager.GetString("YearQsos", resourceCulture);
            }
        }
        
        public static string UpdateBigCty {
            get {
                return ResourceManager.GetString("UpdateBigCty", resourceCulture);
            }
        }
        
        public static string UpdateBigCtySuccess {
            get {
                return ResourceManager.GetString("UpdateBigCtySuccess", resourceCulture);
            }
        }
        
        public static string UpdateBigCtyFailed {
            get {
                return ResourceManager.GetString("UpdateBigCtyFailed", resourceCulture);
            }
        }
        
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        public static string BigCtyHint {
            get {
                return ResourceManager.GetString("BigCtyHint", resourceCulture);
            }
        }
        
        public static string RightClickToSeeMore {
            get {
                return ResourceManager.GetString("RightClickToSeeMore", resourceCulture);
            }
        }
        
        public static string AutoRigUpload {
            get {
                return ResourceManager.GetString("AutoRigUpload", resourceCulture);
            }
        }
        
        public static string QsoUploadEndpoint {
            get {
                return ResourceManager.GetString("QsoUploadEndpoint", resourceCulture);
            }
        }
        
        public static string RigInfoUploadEndpoint {
            get {
                return ResourceManager.GetString("RigInfoUploadEndpoint", resourceCulture);
            }
        }
        
        public static string EnablePlugin {
            get {
                return ResourceManager.GetString("EnablePlugin", resourceCulture);
            }
        }
        
        public static string ShowCoastline {
            get {
                return ResourceManager.GetString("ShowCoastline", resourceCulture);
            }
        }
        
        public static string WizardTitle {
            get {
                return ResourceManager.GetString("WizardTitle", resourceCulture);
            }
        }
        
        public static string WizardWelcomeTitle {
            get {
                return ResourceManager.GetString("WizardWelcomeTitle", resourceCulture);
            }
        }
        
        public static string WizardBasicTitle {
            get {
                return ResourceManager.GetString("WizardBasicTitle", resourceCulture);
            }
        }
        
        public static string WizardCloudlogTitle {
            get {
                return ResourceManager.GetString("WizardCloudlogTitle", resourceCulture);
            }
        }
        
        public static string WizardThirdPartyTitle {
            get {
                return ResourceManager.GetString("WizardThirdPartyTitle", resourceCulture);
            }
        }
        
        public static string WizardRigTitle {
            get {
                return ResourceManager.GetString("WizardRigTitle", resourceCulture);
            }
        }
        
        public static string WizardWelcomeMessage {
            get {
                return ResourceManager.GetString("WizardWelcomeMessage", resourceCulture);
            }
        }
        
        public static string WizardBasicHint {
            get {
                return ResourceManager.GetString("WizardBasicHint", resourceCulture);
            }
        }
        
        public static string WizardChartFeatureLabel {
            get {
                return ResourceManager.GetString("WizardChartFeatureLabel", resourceCulture);
            }
        }
        
        public static string WizardChartFeatureHint {
            get {
                return ResourceManager.GetString("WizardChartFeatureHint", resourceCulture);
            }
        }
        
        public static string WizardCloudlogHint {
            get {
                return ResourceManager.GetString("WizardCloudlogHint", resourceCulture);
            }
        }
        
        public static string WizardCloudlogEnable {
            get {
                return ResourceManager.GetString("WizardCloudlogEnable", resourceCulture);
            }
        }
        
        public static string WizardCloudlogUrl {
            get {
                return ResourceManager.GetString("WizardCloudlogUrl", resourceCulture);
            }
        }
        
        public static string WizardCloudlogApiKey {
            get {
                return ResourceManager.GetString("WizardCloudlogApiKey", resourceCulture);
            }
        }
        
        public static string WizardCloudlogStation {
            get {
                return ResourceManager.GetString("WizardCloudlogStation", resourceCulture);
            }
        }
        
        public static string WizardCloudlogTestRequired {
            get {
                return ResourceManager.GetString("WizardCloudlogTestRequired", resourceCulture);
            }
        }
        
        public static string WizardCloudlogStationRequired {
            get {
                return ResourceManager.GetString("WizardCloudlogStationRequired", resourceCulture);
            }
        }

        public static string WizardCloudlogDetectedInstance {
            get {
                return ResourceManager.GetString("WizardCloudlogDetectedInstance", resourceCulture);
            }
        }
        
        public static string WizardThirdPartyHint {
            get {
                return ResourceManager.GetString("WizardThirdPartyHint", resourceCulture);
            }
        }
        
        public static string WizardRigHint {
            get {
                return ResourceManager.GetString("WizardRigHint", resourceCulture);
            }
        }
        
        public static string WizardRigBackendLabel {
            get {
                return ResourceManager.GetString("WizardRigBackendLabel", resourceCulture);
            }
        }
        
        public static string WizardRigNone {
            get {
                return ResourceManager.GetString("WizardRigNone", resourceCulture);
            }
        }
        
        public static string WizardRigHamlib {
            get {
                return ResourceManager.GetString("WizardRigHamlib", resourceCulture);
            }
        }
        
        public static string WizardRigFlRig {
            get {
                return ResourceManager.GetString("WizardRigFlRig", resourceCulture);
            }
        }
        
        public static string WizardRigOmniRig {
            get {
                return ResourceManager.GetString("WizardRigOmniRig", resourceCulture);
            }
        }
        
        public static string WizardOmniRigUnavailable {
            get {
                return ResourceManager.GetString("WizardOmniRigUnavailable", resourceCulture);
            }
        }
        
        public static string WizardSkip {
            get {
                return ResourceManager.GetString("WizardSkip", resourceCulture);
            }
        }
        
        public static string WizardNext {
            get {
                return ResourceManager.GetString("WizardNext", resourceCulture);
            }
        }
        
        public static string WizardPrevious {
            get {
                return ResourceManager.GetString("WizardPrevious", resourceCulture);
            }
        }
        
        public static string WizardFinish {
            get {
                return ResourceManager.GetString("WizardFinish", resourceCulture);
            }
        }
        
        public static string RunWizard {
            get {
                return ResourceManager.GetString("RunWizard", resourceCulture);
            }
        }
        
        public static string WizardHiThere {
            get {
                return ResourceManager.GetString("WizardHiThere", resourceCulture);
            }
        }
    }
}
